from __future__ import annotations

import json
import os
import secrets
import sqlite3
from datetime import datetime, timezone
from html import escape
from pathlib import Path
from urllib.parse import quote

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import HTMLResponse, JSONResponse
from pydantic import BaseModel, Field

from .aura_live_overlay_studio import SOURCE_TOKEN_BYTES, _ensure_profile, _hash_token
from .branding import PRODUCT_FULL_NAME

router = APIRouter(tags=["Aura LIVE Stream Overlay Effects"])
DB_PATH = Path(os.getenv("AURA_LIVE_OVERLAY_DB", "data/aura_live_overlay.sqlite3"))
EVENT_LIMIT = 1000
MAX_EFFECTS_PER_EVENT = 12

EVENT_TYPES = {
    "viewer_joined", "follow", "subscribe", "gift", "share", "like", "like_milestone", "comment",
    "battle_start", "battle_progress", "battle_end", "poll", "treasure_chest", "question", "pinned_message",
    "live_shopping", "intro", "super_fan", "shared_stream", "custom",
}


def _fx(
    effect_id: str,
    name: str,
    category: str,
    primitive: str,
    symbol: str,
    events: tuple[str, ...],
    description: str,
    *,
    default: bool = False,
) -> dict:
    return {
        "id": effect_id,
        "name": name,
        "category": category,
        "primitive": primitive,
        "symbol": symbol,
        "events": list(events),
        "description": description,
        "default_enabled": default,
    }


# Every catalogue entry below has an executable renderer primitive in the transparent browser
# source. These are not placeholder names: enabling an item changes the live browser-source
# output when one of its bounded trigger events arrives.
EFFECT_CATALOG = [
    # Gifts / supporters
    _fx("gift_cannon", "Gift Cannon", "Gifts & Supporters", "fountain", "🎁", ("gift",), "Launch gift particles upward from the bottom of the LIVE.", default=True),
    _fx("coin_rain", "Coin Rain", "Gifts & Supporters", "rain", "✦", ("gift",), "Rain golden supporter particles across the scene."),
    _fx("rose_shower", "Rose Shower", "Gifts & Supporters", "rain", "✿", ("gift",), "Soft flower shower for gift reactions."),
    _fx("diamond_spark", "Diamond Spark", "Gifts & Supporters", "burst", "◆", ("gift",), "Diamond-shaped radial gift burst."),
    _fx("supporter_halo", "Supporter Halo", "Gifts & Supporters", "ring", "◎", ("gift", "super_fan"), "Expanding halo for a supporter event."),
    _fx("supporter_spotlight", "Supporter Spotlight", "Gifts & Supporters", "spotlight", "★", ("gift", "super_fan"), "Brief radial spotlight around the supporter name."),
    _fx("gift_combo_streak", "Gift Combo Streak", "Gifts & Supporters", "banner", "×", ("gift",), "Animated supporter banner for gift streak activity."),
    _fx("golden_crown", "Golden Crown", "Gifts & Supporters", "burst", "♛", ("gift", "super_fan"), "Crown burst for high-energy supporter moments."),

    # Likes / reactions
    _fx("heart_fountain", "Heart Fountain", "Likes & Reactions", "fountain", "♥", ("like", "like_milestone"), "Heart fountain for likes and like milestones.", default=True),
    _fx("heart_rain", "Heart Rain", "Likes & Reactions", "rain", "♥", ("like_milestone",), "Full-scene heart rain at a milestone."),
    _fx("like_ripple", "Like Ripple", "Likes & Reactions", "ring", "◉", ("like", "like_milestone"), "Expanding ripple generated by like activity."),
    _fx("reaction_pop", "Reaction Pop", "Likes & Reactions", "burst", "❤", ("like_milestone",), "Radial reaction symbols around the scene centre."),
    _fx("applause_burst", "Applause Burst", "Likes & Reactions", "burst", "👏", ("like_milestone",), "Applause burst for larger audience moments."),
    _fx("like_wave", "Like Wave", "Likes & Reactions", "flash", "≈", ("like_milestone",), "Fast translucent wave across the complete overlay."),

    # Followers / subscribers / arrivals
    _fx("follower_confetti", "Follower Confetti", "Follows & Subscribers", "confetti", "◆", ("follow",), "Confetti celebration when somebody follows.", default=True),
    _fx("follower_name_pop", "Follower Name Pop", "Follows & Subscribers", "banner", "+", ("follow",), "Follower name banner with a short entrance animation."),
    _fx("subscriber_fireworks", "Subscriber Fireworks", "Follows & Subscribers", "confetti", "✦", ("subscribe",), "Large celebratory particle field for subscribers.", default=True),
    _fx("subscriber_crown", "Subscriber Crown", "Follows & Subscribers", "burst", "♛", ("subscribe",), "Crown burst around a subscriber event."),
    _fx("vip_portal", "VIP Portal", "Follows & Subscribers", "ring", "◎", ("subscribe", "super_fan"), "Layered portal rings for VIP arrivals."),
    _fx("community_welcome", "Community Welcome", "Follows & Subscribers", "spotlight", "★", ("viewer_joined", "follow", "subscribe"), "Subtle welcome spotlight for community arrivals."),
    _fx("arrival_sparkles", "Arrival Sparkles", "Follows & Subscribers", "burst", "✧", ("viewer_joined",), "Light sparkle burst for viewer arrivals."),

    # Shares / community movement
    _fx("share_wave", "Share Wave", "Shares & Community", "flash", "↗", ("share", "shared_stream"), "Scene-wide pulse when the LIVE is shared.", default=True),
    _fx("share_ribbon", "Share Ribbon", "Shares & Community", "banner", "↗", ("share", "shared_stream"), "Slide-in share acknowledgement ribbon."),
    _fx("community_stars", "Community Stars", "Shares & Community", "burst", "★", ("share", "shared_stream"), "Star burst for community amplification."),
    _fx("community_ripple", "Community Ripple", "Shares & Community", "ring", "◌", ("share", "shared_stream"), "Expanding community ripple for share events."),

    # Goals / milestones
    _fx("goal_confetti", "Goal Confetti", "Goals & Milestones", "confetti", "◆", ("like_milestone", "treasure_chest"), "Confetti layer for milestone and goal moments."),
    _fx("goal_fireworks", "Goal Fireworks", "Goals & Milestones", "confetti", "✦", ("like_milestone", "treasure_chest"), "Higher-density fireworks-style particle celebration."),
    _fx("milestone_shockwave", "Milestone Shockwave", "Goals & Milestones", "ring", "◎", ("like_milestone", "treasure_chest"), "Large expanding milestone ring."),
    _fx("progress_glow", "Progress Glow", "Goals & Milestones", "frame", "▣", ("like_milestone", "gift"), "Reactive border glow for progress events."),
    _fx("trophy_burst", "Trophy Burst", "Goals & Milestones", "burst", "🏆", ("like_milestone", "treasure_chest"), "Trophy burst for completed milestones."),

    # Battles / matches
    _fx("battle_neon_frame", "Battle Neon Frame", "Battles & Matches", "frame", "▣", ("battle_start", "battle_progress", "battle_end"), "Reactive frame during LIVE Match events.", default=True),
    _fx("battle_clash", "Battle Clash", "Battles & Matches", "shake", "⚡", ("battle_start", "battle_end"), "Short bounded scene shake for battle transitions."),
    _fx("score_surge", "Score Surge", "Battles & Matches", "zoom", "▲", ("battle_progress",), "Brief zoom pulse for score progress."),
    _fx("victory_fireworks", "Victory Fireworks", "Battles & Matches", "confetti", "✦", ("battle_end",), "End-of-battle fireworks celebration."),
    _fx("battle_lightning", "Battle Lightning", "Battles & Matches", "flash", "⚡", ("battle_start", "battle_progress"), "Fast battle energy flash."),
    _fx("versus_shockwave", "Versus Shockwave", "Battles & Matches", "ring", "VS", ("battle_start",), "Layered versus ring at match start."),

    # Chat / polls / shopping
    _fx("comment_spark", "Comment Spark", "Chat & Interactive", "burst", "✧", ("comment",), "Small spark reaction for chat activity."),
    _fx("question_pop", "Question Pop", "Chat & Interactive", "banner", "?", ("question",), "Question banner for Q&A moments."),
    _fx("pinned_glow", "Pinned Message Glow", "Chat & Interactive", "frame", "◆", ("pinned_message",), "Glow frame when a pinned message changes."),
    _fx("poll_pulse", "Poll Pulse", "Chat & Interactive", "ring", "◉", ("poll",), "Pulse ring for poll updates."),
    _fx("shopping_shimmer", "Shopping Shimmer", "Chat & Interactive", "flash", "✦", ("live_shopping",), "Subtle shimmer for shopping cards or product moments."),
    _fx("chat_celebration", "Chat Celebration", "Chat & Interactive", "confetti", "✧", ("custom",), "Host-triggered celebration using a synthetic/custom event."),

    # Motion / camera / scene energy
    _fx("camera_neon_pulse", "Camera Neon Pulse", "Motion & Camera", "frame", "▣", ("gift", "follow", "subscribe", "like_milestone"), "Camera-edge pulse tied to supporter events."),
    _fx("cyber_glitch", "Cyber Glitch", "Motion & Camera", "glitch", "⌁", ("gift", "battle_start", "battle_end"), "Short visual glitch with no arbitrary script execution."),
    _fx("hologram_sweep", "Hologram Sweep", "Motion & Camera", "flash", "▱", ("follow", "subscribe", "share"), "Translucent hologram-style screen sweep."),
    _fx("zoom_pop", "Zoom Pop", "Motion & Camera", "zoom", "+", ("gift", "subscribe"), "Brief bounded scene zoom."),
    _fx("screen_shake", "Screen Shake", "Motion & Camera", "shake", "⚡", ("gift", "battle_end"), "Short controlled shake for high-energy moments."),
    _fx("bounce_scene", "Bounce Scene", "Motion & Camera", "bounce", "↑", ("follow", "like_milestone"), "Gentle scene bounce on selected events."),
    _fx("spotlight_sweep", "Spotlight Sweep", "Motion & Camera", "spotlight", "◉", ("subscribe", "super_fan"), "Radial spotlight sweep for featured supporters."),

    # Ambient layers. These remain continuously visible while enabled and do not need event input.
    _fx("cosmic_dust", "Cosmic Dust", "Ambient Layers", "ambient", "·", ("ambient",), "Low-density drifting cosmic particles."),
    _fx("star_drift", "Star Drift", "Ambient Layers", "ambient", "✦", ("ambient",), "Slow star drift across transparent scene space."),
    _fx("sparkle_field", "Sparkle Field", "Ambient Layers", "ambient", "✧", ("ambient",), "Subtle field of animated sparkles."),
    _fx("aurora_sweep", "Aurora Sweep", "Ambient Layers", "ambient_band", "≈", ("ambient",), "Soft moving translucent energy band."),
    _fx("bubble_drift", "Bubble Drift", "Ambient Layers", "ambient", "○", ("ambient",), "Slow floating bubble layer."),
    _fx("floating_hearts", "Floating Hearts", "Ambient Layers", "ambient", "♥", ("ambient",), "Low-density floating heart layer."),

    # Universal celebration / host-triggered extras
    _fx("confetti_storm", "Confetti Storm", "Celebrations", "confetti", "◆", ("custom", "subscribe", "battle_end"), "Large reusable confetti celebration."),
    _fx("firework_wall", "Firework Wall", "Celebrations", "confetti", "✦", ("custom", "subscribe", "battle_end"), "Full-width fireworks-style particle wall."),
    _fx("stardust_swirl", "Stardust Swirl", "Celebrations", "fountain", "✧", ("custom", "gift", "follow"), "Upward stardust swirl."),
    _fx("celebration_flash", "Celebration Flash", "Celebrations", "flash", "✦", ("custom", "subscribe", "like_milestone"), "Quick full-scene celebration pulse."),
    _fx("celebration_banner", "Celebration Banner", "Celebrations", "banner", "★", ("custom", "subscribe", "battle_end"), "Large event-aware celebration banner."),
]

EFFECT_BY_ID = {item["id"]: item for item in EFFECT_CATALOG}
DEFAULT_ENABLED = [item["id"] for item in EFFECT_CATALOG if item["default_enabled"]]


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _connect() -> sqlite3.Connection:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    con = sqlite3.connect(DB_PATH)
    con.row_factory = sqlite3.Row
    con.execute("PRAGMA foreign_keys=ON")
    con.execute("PRAGMA journal_mode=WAL")
    return con


def _init_schema() -> None:
    with _connect() as con:
        con.executescript(
            """
            CREATE TABLE IF NOT EXISTS live_overlay_effect_preferences (
                user_id TEXT PRIMARY KEY,
                enabled_json TEXT NOT NULL,
                intensity REAL NOT NULL DEFAULT 1.0,
                max_effects_per_event INTEGER NOT NULL DEFAULT 6,
                reduced_motion INTEGER NOT NULL DEFAULT 0,
                updated_at TEXT NOT NULL
            );
            """
        )


_init_schema()


def _member(request: Request):
    member = getattr(request.state, "member", None)
    if member is None:
        raise HTTPException(401, "Sign in required")
    return member


def _user_for_source(token: str) -> str:
    digest = _hash_token(token)
    with _connect() as con:
        row = con.execute(
            "SELECT user_id FROM live_overlay_profiles WHERE source_token_hash=?",
            (digest,),
        ).fetchone()
    if not row:
        raise HTTPException(404, "Overlay source not found")
    return str(row["user_id"])


def _preferences(user_id: str) -> dict:
    with _connect() as con:
        row = con.execute(
            "SELECT * FROM live_overlay_effect_preferences WHERE user_id=?",
            (user_id,),
        ).fetchone()
        if not row:
            con.execute(
                """INSERT INTO live_overlay_effect_preferences(
                       user_id,enabled_json,intensity,max_effects_per_event,reduced_motion,updated_at
                   ) VALUES(?,?,1.0,6,0,?)""",
                (user_id, json.dumps(DEFAULT_ENABLED), _now()),
            )
            row = con.execute(
                "SELECT * FROM live_overlay_effect_preferences WHERE user_id=?",
                (user_id,),
            ).fetchone()
    try:
        enabled = json.loads(str(row["enabled_json"]))
    except Exception:
        enabled = list(DEFAULT_ENABLED)
    enabled = [effect_id for effect_id in enabled if effect_id in EFFECT_BY_ID]
    return {
        "enabled_effects": enabled,
        "intensity": max(0.25, min(float(row["intensity"]), 2.0)),
        "max_effects_per_event": max(1, min(int(row["max_effects_per_event"]), MAX_EFFECTS_PER_EVENT)),
        "reduced_motion": bool(row["reduced_motion"]),
        "updated_at": row["updated_at"],
    }


def effect_state_for_user(user_id: str) -> dict:
    prefs = _preferences(user_id)
    enabled = set(prefs["enabled_effects"])
    return {
        **prefs,
        "catalog": [{**item, "enabled": item["id"] in enabled} for item in EFFECT_CATALOG],
        "effect_count": len(EFFECT_CATALOG),
        "all_effects_selectable": True,
        "event_input": "normalized_live_overlay_events",
        "browser_source_runtime": True,
        "arbitrary_javascript_execution": False,
    }


class EffectsUpdate(BaseModel):
    enabled_effects: list[str] | None = Field(default=None, max_length=128)
    intensity: float | None = Field(default=None, ge=0.25, le=2.0)
    max_effects_per_event: int | None = Field(default=None, ge=1, le=MAX_EFFECTS_PER_EVENT)
    reduced_motion: bool | None = None


class EffectTest(BaseModel):
    event_type: str = Field(pattern="^(viewer_joined|follow|subscribe|gift|share|like|like_milestone|comment|battle_start|battle_progress|battle_end|poll|treasure_chest|question|pinned_message|live_shopping|intro|super_fan|shared_stream|custom)$")


@router.get("/api/live-overlays/effects")
def get_effects(request: Request):
    member = _member(request)
    _ensure_profile(member.user_id)
    return effect_state_for_user(member.user_id)


@router.put("/api/live-overlays/effects")
def update_effects(body: EffectsUpdate, request: Request):
    member = _member(request)
    _ensure_profile(member.user_id)
    current = _preferences(member.user_id)
    enabled = current["enabled_effects"]
    if body.enabled_effects is not None:
        enabled = list(dict.fromkeys(body.enabled_effects))
        unknown = [effect_id for effect_id in enabled if effect_id not in EFFECT_BY_ID]
        if unknown:
            raise HTTPException(400, f"Unknown LIVE overlay effect: {unknown[0]}")
    intensity = body.intensity if body.intensity is not None else current["intensity"]
    max_per_event = body.max_effects_per_event if body.max_effects_per_event is not None else current["max_effects_per_event"]
    reduced_motion = body.reduced_motion if body.reduced_motion is not None else current["reduced_motion"]
    with _connect() as con:
        con.execute(
            """INSERT INTO live_overlay_effect_preferences(
                   user_id,enabled_json,intensity,max_effects_per_event,reduced_motion,updated_at
               ) VALUES(?,?,?,?,?,?)
               ON CONFLICT(user_id) DO UPDATE SET
                 enabled_json=excluded.enabled_json,
                 intensity=excluded.intensity,
                 max_effects_per_event=excluded.max_effects_per_event,
                 reduced_motion=excluded.reduced_motion,
                 updated_at=excluded.updated_at""",
            (member.user_id, json.dumps(enabled), float(intensity), int(max_per_event), int(bool(reduced_motion)), _now()),
        )
    return effect_state_for_user(member.user_id)


@router.post("/api/live-overlays/effects/test")
def test_effect_event(body: EffectTest, request: Request):
    member = _member(request)
    _ensure_profile(member.user_id)
    payload = {
        "username": "Aura Test Viewer",
        "display_name": "Aura Test Viewer",
        "gift_name": "Rose",
        "gift_count": 5,
        "coins": 50,
        "message": "LIVE overlay effect preview",
        "likes": 1000,
        "progress": 1,
        "target": 1000,
        "synthetic": True,
    }
    with _connect() as con:
        con.execute(
            "INSERT INTO live_overlay_events(user_id,event_type,payload_json,created_at) VALUES(?,?,?,?)",
            (member.user_id, body.event_type, json.dumps(payload, separators=(",", ":")), _now()),
        )
        con.execute(
            """DELETE FROM live_overlay_events
               WHERE user_id=? AND id NOT IN (
                   SELECT id FROM live_overlay_events WHERE user_id=? ORDER BY id DESC LIMIT ?
               )""",
            (member.user_id, member.user_id, EVENT_LIMIT),
        )
    return {"queued": True, "synthetic": True, "event_type": body.event_type, "goal_state_changed": False}


@router.post("/api/live-overlays/effects/rotate-source")
def rotate_effects_source(request: Request):
    member = _member(request)
    _ensure_profile(member.user_id)
    raw = secrets.token_urlsafe(SOURCE_TOKEN_BYTES)
    with _connect() as con:
        con.execute(
            "UPDATE live_overlay_profiles SET source_token_hash=?,updated_at=? WHERE user_id=?",
            (_hash_token(raw), _now(), member.user_id),
        )
    base = str(request.base_url).rstrip("/")
    return JSONResponse(
        {
            "source_url": f"{base}/live-overlay/source/effects/{quote(raw, safe='')}",
            "rotated": True,
            "invalidates_previous_overlay_source_urls": True,
        },
        headers={"Cache-Control": "private, no-store", "Referrer-Policy": "no-referrer"},
    )


@router.get("/live-overlay/source/effects/{token}/state", include_in_schema=False)
def effects_source_state(token: str):
    user_id = _user_for_source(token)
    return JSONResponse(
        effect_state_for_user(user_id),
        headers={"Cache-Control": "no-store", "Referrer-Policy": "no-referrer"},
    )


@router.get("/live-overlay/source/effects/{token}/events", include_in_schema=False)
def effects_source_events(token: str, after: int = 0):
    user_id = _user_for_source(token)
    after = max(0, min(int(after), 2_147_483_647))
    with _connect() as con:
        rows = con.execute(
            "SELECT id,event_type,payload_json,created_at FROM live_overlay_events WHERE user_id=? AND id>? ORDER BY id ASC LIMIT 100",
            (user_id, after),
        ).fetchall()
    events = []
    for row in rows:
        try:
            payload = json.loads(str(row["payload_json"]))
        except Exception:
            payload = {}
        events.append(
            {
                "id": int(row["id"]),
                "event_type": str(row["event_type"]),
                "payload": payload if isinstance(payload, dict) else {},
                "created_at": row["created_at"],
            }
        )
    return JSONResponse(
        {"events": events},
        headers={"Cache-Control": "no-store", "Referrer-Policy": "no-referrer"},
    )


def _catalog_html() -> str:
    categories: dict[str, list[dict]] = {}
    for item in EFFECT_CATALOG:
        categories.setdefault(item["category"], []).append(item)
    chunks = []
    for category, items in categories.items():
        rows = "".join(
            f"<label class='fx'><input type='checkbox' data-fx='{escape(item['id'], quote=True)}'>"
            f"<span><b>{escape(item['name'])}</b><small>{escape(item['description'])}</small>"
            f"<em>{escape(', '.join(item['events']))}</em></span></label>"
            for item in items
        )
        chunks.append(f"<section class='group'><h2>{escape(category)}</h2><div class='grid'>{rows}</div></section>")
    return "".join(chunks)


@router.get("/live-overlay-studio/effects", response_class=HTMLResponse, include_in_schema=False)
def effects_control_room(request: Request):
    member = _member(request)
    _ensure_profile(member.user_id)
    catalog_html = _catalog_html()
    return HTMLResponse(
        f"""<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><meta name='robots' content='noindex,nofollow'><title>LIVE Overlay Effects Library</title><style>
body{{margin:0;background:#070812;color:#fff;font-family:Inter,system-ui,sans-serif}}main{{width:min(1180px,calc(100% - 28px));margin:auto;padding:30px 0 60px}}a{{color:#fff}}h1{{font-size:clamp(2.4rem,6vw,4.8rem);margin:.1em 0}}.muted{{color:#b9c2d5;line-height:1.55}}.panel,.group{{background:#111526;border:1px solid #ffffff20;border-radius:18px;padding:18px;margin:14px 0}}.grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}}.fx{{display:flex;gap:10px;padding:12px;background:#ffffff08;border:1px solid #ffffff12;border-radius:12px;cursor:pointer}}.fx input{{margin-top:4px}}.fx small,.fx em{{display:block;color:#b9c2d5;margin-top:5px;font-size:.8rem;font-style:normal}}.fx em{{color:#e8bd62}}button,input{{font:inherit}}button{{background:#191d31;color:#fff;border:1px solid #ffffff25;border-radius:10px;padding:11px 14px;cursor:pointer;font-weight:850}}button.primary{{background:linear-gradient(120deg,#efc96b,#9b72ff);color:#13091d;border:0}}.row{{display:flex;gap:10px;align-items:center;flex-wrap:wrap}}code{{color:#efc96b;word-break:break-all}}@media(max-width:880px){{.grid{{grid-template-columns:1fr}}}}
</style></head><body><main><a href='/live-overlay-studio'>← Stream Studio control room</a><p class='muted'>Shared Sky Streaming Studios · Aura LIVE</p><h1>LIVE Overlay Effects Library</h1><p class='muted'>Every effect shown here is executable in the transparent LIVE browser source. Enable the effects you want, add the private source to TikTok LIVE Studio, OBS or Streamlabs, and normalized LIVE events trigger them while you are live. The library never executes arbitrary JavaScript supplied by viewers or connectors.</p><div class='panel'><h2>Private effects browser source</h2><p class='muted'>Generate a private source URL, then add it as a Link/Browser Source above your camera or gameplay. Rotating this secret also invalidates your previous Aura LIVE overlay source URLs.</p><button id='rotate' class='primary'>Generate / rotate effects source</button><p id='source'><code>Generate a private URL to reveal it here.</code></p></div><div class='panel'><h2>Performance controls</h2><div class='row'><label>Intensity <input id='intensity' type='range' min='.25' max='2' step='.05' value='1'></label><label>Maximum simultaneous effects <input id='maxFx' type='number' min='1' max='{MAX_EFFECTS_PER_EVENT}' value='6'></label><label><input id='reduced' type='checkbox'> Reduced motion</label><button id='save' class='primary'>Save LIVE effects</button><button id='all'>Enable all</button><button id='none'>Disable all</button></div><p id='status' class='muted'></p></div><div class='panel'><h2>Test before going LIVE</h2><div class='row' id='tests'></div><p class='muted'>Tests are synthetic overlay events only. They do not change goal totals or claim provider LIVE data.</p></div>{catalog_html}</main><script>
const $=x=>document.getElementById(x);let state=null;
async function load(){{const r=await fetch('/api/live-overlays/effects',{{cache:'no-store'}});if(!r.ok)return;$('status').textContent='Loading…';state=await r.json();document.querySelectorAll('[data-fx]').forEach(x=>x.checked=state.enabled_effects.includes(x.dataset.fx));$('intensity').value=state.intensity;$('maxFx').value=state.max_effects_per_event;$('reduced').checked=state.reduced_motion;$('status').textContent=`${{state.effect_count}} executable effects available · ${{state.enabled_effects.length}} enabled`;}}
$('save').onclick=async()=>{{const enabled=[...document.querySelectorAll('[data-fx]:checked')].map(x=>x.dataset.fx);const r=await fetch('/api/live-overlays/effects',{{method:'PUT',headers:{{'content-type':'application/json'}},body:JSON.stringify({{enabled_effects:enabled,intensity:Number($('intensity').value),max_effects_per_event:Number($('maxFx').value),reduced_motion:$('reduced').checked}})}});const d=await r.json();if(!r.ok)return alert(d.detail||'Unable to save effects');state=d;$('status').textContent=`Saved · ${{d.enabled_effects.length}} effects enabled for LIVE use`;}};
$('all').onclick=()=>document.querySelectorAll('[data-fx]').forEach(x=>x.checked=true);$('none').onclick=()=>document.querySelectorAll('[data-fx]').forEach(x=>x.checked=false);
$('rotate').onclick=async()=>{{const r=await fetch('/api/live-overlays/effects/rotate-source',{{method:'POST'}});const d=await r.json();if(!r.ok)return alert(d.detail||'Unable to rotate source');$('source').innerHTML='<code>'+d.source_url.replaceAll('&','&amp;').replaceAll('<','&lt;')+'</code>';}};
const testTypes=['gift','like_milestone','follow','subscribe','share','battle_start','battle_end','poll','custom'];for(const t of testTypes){{const b=document.createElement('button');b.textContent='Test '+t.replaceAll('_',' ');b.onclick=async()=>{{await fetch('/api/live-overlays/effects/test',{{method:'POST',headers:{{'content-type':'application/json'}},body:JSON.stringify({{event_type:t}})}})}};$('tests').appendChild(b)}}load();
</script></body></html>""",
        headers={"Cache-Control": "private, no-store", "Referrer-Policy": "no-referrer", "X-Robots-Tag": "noindex, nofollow"},
    )


@router.get("/live-overlay/source/effects/{token}", response_class=HTMLResponse, include_in_schema=False)
def effects_browser_source(token: str):
    _user_for_source(token)
    token_js = json.dumps(token)
    html = r"""<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><meta name='robots' content='noindex,nofollow'><style>
html,body{margin:0;width:100%;height:100%;background:transparent;overflow:hidden;font-family:Inter,Arial,sans-serif;color:#fff}#fx,#ambient{position:absolute;inset:0;pointer-events:none}.p{position:absolute;font-weight:900;text-shadow:0 2px 10px #0008;will-change:transform,opacity}.fountain{animation:fountain 2.5s ease-out forwards}.rain{animation:rain 2.8s linear forwards}.burst{animation:burst 1.9s ease-out forwards}.confetti{animation:confetti 2.8s ease-out forwards}.ring{position:absolute;left:50%;top:50%;width:80px;height:80px;border:5px solid currentColor;border-radius:50%;transform:translate(-50%,-50%) scale(.2);animation:ring 1.3s ease-out forwards}.flash{position:absolute;inset:0;background:radial-gradient(circle at center,#ffffff66,transparent 68%);animation:fade 750ms ease-out forwards}.frame{position:absolute;inset:2%;border:8px solid #ffffffcc;border-radius:28px;box-shadow:0 0 32px #ffffffaa inset,0 0 45px #ffffff99;animation:frame 1.25s ease-out forwards}.banner{position:absolute;left:50%;top:14%;transform:translate(-50%,-25px) scale(.96);padding:15px 22px;max-width:82%;border:1px solid #ffffff45;border-radius:18px;background:#0b1022e8;box-shadow:0 15px 55px #0008;text-align:center;font-size:clamp(18px,3vw,34px);font-weight:900;animation:banner 3.2s ease-in-out forwards}.spotlight{position:absolute;inset:-10%;background:radial-gradient(circle at 50% 45%,#ffffff55 0,transparent 35%);animation:fade 1.4s ease-out forwards}.ambient{position:absolute;animation:ambient 8s linear infinite;opacity:.6}.ambientBand{position:absolute;left:-30%;top:25%;width:160%;height:28%;background:linear-gradient(90deg,transparent,#ffffff16,#ffffff35,#ffffff12,transparent);filter:blur(18px);animation:band 9s ease-in-out infinite}.shake{animation:shake .55s ease-out}.zoom{animation:zoom .75s ease-out}.bounce{animation:bounce .8s ease-out}.glitch{animation:glitch .7s steps(2,end)}
@keyframes fountain{0%{opacity:0;transform:translateY(40px) scale(.7)}18%{opacity:1}100%{opacity:0;transform:translate(var(--dx),-440px) rotate(var(--rot)) scale(1.15)}}@keyframes rain{0%{opacity:0;transform:translateY(-70px) rotate(0)}15%{opacity:1}100%{opacity:0;transform:translate(var(--dx),110vh) rotate(var(--rot))}}@keyframes burst{0%{opacity:0;transform:translate(-50%,-50%) scale(.3)}15%{opacity:1}100%{opacity:0;transform:translate(calc(-50% + var(--dx)),calc(-50% + var(--dy))) rotate(var(--rot)) scale(1.25)}}@keyframes confetti{0%{opacity:0;transform:translateY(-50px) rotate(0)}12%{opacity:1}100%{opacity:0;transform:translate(var(--dx),105vh) rotate(var(--rot))}}@keyframes ring{0%{opacity:0;transform:translate(-50%,-50%) scale(.2)}20%{opacity:1}100%{opacity:0;transform:translate(-50%,-50%) scale(8)}}@keyframes fade{0%{opacity:0}20%{opacity:1}100%{opacity:0}}@keyframes frame{0%{opacity:0;transform:scale(.96)}25%{opacity:1}100%{opacity:0;transform:scale(1.01)}}@keyframes banner{0%{opacity:0;transform:translate(-50%,-28px) scale(.96)}12%,75%{opacity:1;transform:translate(-50%,0) scale(1)}100%{opacity:0;transform:translate(-50%,-12px) scale(.98)}}@keyframes ambient{0%{transform:translateY(105vh) translateX(0)}100%{transform:translateY(-15vh) translateX(var(--dx))}}@keyframes band{0%,100%{transform:translateX(-10%) rotate(-5deg);opacity:.2}50%{transform:translateX(10%) rotate(5deg);opacity:.6}}@keyframes shake{0%,100%{transform:translate(0)}20%{transform:translate(-10px,5px)}40%{transform:translate(9px,-5px)}60%{transform:translate(-7px,4px)}80%{transform:translate(5px,-3px)}}@keyframes zoom{0%,100%{transform:scale(1)}45%{transform:scale(1.045)}}@keyframes bounce{0%,100%{transform:translateY(0)}40%{transform:translateY(-18px)}70%{transform:translateY(8px)}}@keyframes glitch{0%,100%{filter:none;transform:translate(0)}20%{filter:hue-rotate(60deg) contrast(1.5);transform:translate(8px,-3px)}45%{filter:hue-rotate(-80deg) contrast(1.8);transform:translate(-7px,4px)}70%{filter:contrast(1.4);transform:translate(4px,2px)}}
</style></head><body><div id='ambient'></div><div id='fx'></div><script>'use strict';
const TOKEN=__TOKEN__;let after=0,state={catalog:[],enabled_effects:[],intensity:1,max_effects_per_event:6,reduced_motion:false};const fx=document.getElementById('fx'),ambient=document.getElementById('ambient');const clean=v=>String(v??'').slice(0,180);const rnd=(a,b)=>a+Math.random()*(b-a);
function titleFor(e,p){const u=clean(p.username||p.display_name||'Viewer');if(e==='gift')return `${u} sent ${clean(p.gift_name||'a gift')}`;if(e==='follow')return `${u} followed`;if(e==='subscribe')return `${u} subscribed`;if(e==='share'||e==='shared_stream')return `${u} shared the LIVE`;if(e==='like_milestone')return 'Like milestone reached!';if(e==='battle_start')return 'LIVE Match started';if(e==='battle_end')return 'LIVE Match complete';if(e==='question')return clean(p.message||'New question');if(e==='poll')return clean(p.title||p.message||'Poll update');if(e==='pinned_message')return clean(p.message||'Pinned message');return `${u} · ${clean(e.replaceAll('_',' '))}`}
function add(node,ms=3000){fx.appendChild(node);setTimeout(()=>node.remove(),ms)}function particle(spec,cls,x,y){const n=document.createElement('div');n.className='p '+cls;n.textContent=clean(spec.symbol||'✦');n.style.left=x+'%';n.style.top=y+'%';n.style.fontSize=(18+rnd(0,24)*state.intensity)+'px';n.style.setProperty('--dx',rnd(-260,260)+'px');n.style.setProperty('--dy',rnd(-260,260)+'px');n.style.setProperty('--rot',rnd(-240,240)+'deg');return n}
function run(spec,e,p){const reduced=!!state.reduced_motion;const mult=Math.max(.25,Math.min(2,Number(state.intensity||1)));let count=Math.max(2,Math.min(28,Math.round(8*mult)));if(reduced)count=Math.min(count,4);const prim=spec.primitive;if(prim==='ambient'||prim==='ambient_band')return;if(prim==='fountain'){for(let i=0;i<count;i++){const n=particle(spec,'fountain',rnd(6,94),92);n.style.top='auto';n.style.bottom='0';add(n,2800)}}else if(prim==='rain'||prim==='confetti'){for(let i=0;i<count+(prim==='confetti'?5:0);i++){const n=particle(spec,prim,rnd(2,98),-8);add(n,3100)}}else if(prim==='burst'){for(let i=0;i<count;i++){const n=particle(spec,'burst',50,50);add(n,2200)}}else if(prim==='ring'){for(let i=0;i<(reduced?1:3);i++){const n=document.createElement('div');n.className='ring';n.textContent='';n.style.animationDelay=(i*100)+'ms';add(n,1800)}}else if(prim==='flash'){const n=document.createElement('div');n.className='flash';add(n,1000)}else if(prim==='frame'){const n=document.createElement('div');n.className='frame';add(n,1500)}else if(prim==='banner'){const n=document.createElement('div');n.className='banner';n.textContent=titleFor(e,p);add(n,3400)}else if(prim==='spotlight'){const n=document.createElement('div');n.className='spotlight';add(n,1700)}else if(['shake','zoom','bounce','glitch'].includes(prim)){if(reduced)return;document.body.classList.remove(prim);void document.body.offsetWidth;document.body.classList.add(prim);setTimeout(()=>document.body.classList.remove(prim),900)}}
function renderAmbient(){ambient.innerHTML='';if(state.reduced_motion)return;const enabled=new Set(state.enabled_effects||[]);for(const spec of state.catalog||[]){if(!enabled.has(spec.id)||!spec.events.includes('ambient'))continue;if(spec.primitive==='ambient_band'){const n=document.createElement('div');n.className='ambientBand';ambient.appendChild(n);continue}for(let i=0;i<6;i++){const n=document.createElement('div');n.className='p ambient';n.textContent=clean(spec.symbol||'✦');n.style.left=rnd(2,98)+'%';n.style.bottom=rnd(-40,70)+'%';n.style.fontSize=rnd(12,28)+'px';n.style.animationDelay=(-rnd(0,8))+'s';n.style.animationDuration=rnd(7,14)+'s';n.style.setProperty('--dx',rnd(-120,120)+'px');ambient.appendChild(n)}}}
function handle(ev){const enabled=new Set(state.enabled_effects||[]);const eligible=(state.catalog||[]).filter(s=>enabled.has(s.id)&&s.events.includes(ev.event_type));const cap=Math.max(1,Math.min(12,Number(state.max_effects_per_event||6)));for(const spec of eligible.slice(0,cap))run(spec,ev.event_type,ev.payload||{})}
async function refresh(){try{const r=await fetch('/live-overlay/source/effects/'+encodeURIComponent(TOKEN)+'/state',{cache:'no-store'});if(r.ok){state=await r.json();renderAmbient()}}catch{}}async function poll(){try{const r=await fetch('/live-overlay/source/effects/'+encodeURIComponent(TOKEN)+'/events?after='+after,{cache:'no-store'});if(r.ok){const d=await r.json();for(const ev of d.events){after=Math.max(after,ev.id);handle(ev)}}}catch{}finally{setTimeout(poll,650)}}refresh().then(poll);setInterval(refresh,5000);
</script></body></html>""".replace("__TOKEN__", token_js)
    return HTMLResponse(
        html,
        headers={
            "Cache-Control": "no-store",
            "Referrer-Policy": "no-referrer",
            "X-Robots-Tag": "noindex, nofollow",
            "Content-Security-Policy": "default-src 'self'; connect-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src 'self' data:; media-src 'self' blob:",
        },
    )


__all__ = [
    "DEFAULT_ENABLED",
    "EFFECT_BY_ID",
    "EFFECT_CATALOG",
    "effect_state_for_user",
    "effects_browser_source",
    "effects_control_room",
    "router",
]
