from __future__ import annotations

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["Aura Workpage UI"])


@router.get("/aura", response_class=HTMLResponse)
def aura_workpage(request: Request):
    member = getattr(request.state, "member", None)
    if not member:
        return HTMLResponse("Sign in required", status_code=401)

    html = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Aura — AI Workpage</title>
<style>
:root{--bg:#09060e;--panel:#130d1b;--panel2:#1c1227;--line:#382747;--text:#fff;--muted:#bfb2ca;--gold:#edc66e;--purple:#b168e2;--good:#84e6ad;--danger:#ff9baa}
*{box-sizing:border-box}html,body{height:100%;margin:0}body{background:radial-gradient(circle at 50% -20%,#35134d 0,#0a0610 45%);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;overflow:hidden}
button,input,textarea,select{font:inherit}.shell{display:grid;grid-template-columns:290px minmax(0,1fr) 300px;height:100vh}.side,.inspector{background:#0d0913eF;backdrop-filter:blur(16px);border-color:var(--line);overflow:auto}.side{border-right:1px solid var(--line);padding:16px}.inspector{border-left:1px solid var(--line);padding:16px}.main{display:grid;grid-template-rows:auto minmax(0,1fr) auto;min-width:0}
.brand{display:flex;align-items:center;gap:10px;font-weight:900;margin-bottom:18px}.orb{width:34px;height:34px;border-radius:50%;background:radial-gradient(circle at 35% 30%,#fff 0 6%,#f7cf75 8%,#b44ce2 38%,#321245 70%,#11071a 100%);box-shadow:0 0 28px #c95aff99}.small{font-size:.78rem;color:var(--muted)}
.btn{border:1px solid var(--line);background:#1b1225;color:#fff;border-radius:12px;padding:10px 13px;cursor:pointer;font-weight:800}.btn:hover{border-color:#8b5dad}.btn.primary{background:linear-gradient(135deg,#f0cd77,#c59338);color:#180f20;border:0}.btn.full{width:100%}.threads{margin-top:14px}.thread{display:block;width:100%;text-align:left;border:0;background:transparent;color:#ddd;padding:10px;border-radius:10px;cursor:pointer;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.thread:hover,.thread.active{background:#21152d;color:white}.topbar{height:66px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 20px;background:#0b0710cc;backdrop-filter:blur(12px)}.title{font-weight:900}.top-actions{display:flex;gap:8px;align-items:center}.pill{border:1px solid var(--line);border-radius:99px;padding:6px 10px;color:var(--muted);font-size:.78rem}
.messages{overflow:auto;padding:32px max(22px,calc((100% - 860px)/2));scroll-behavior:smooth}.empty{max-width:760px;margin:10vh auto;text-align:center}.empty .aura-stage{width:150px;height:220px;border-radius:80px 80px 45px 45px;margin:0 auto 28px;background:radial-gradient(ellipse at 50% 24%,#f6dda0 0 3%,#be71e5 12%,#44235b 33%,#130b1d 69%);box-shadow:0 0 80px #a448d244;position:relative}.aura-stage:after{content:"AURA";position:absolute;bottom:20px;left:0;right:0;color:#f1d68d;letter-spacing:.25em;font-size:.7rem;font-weight:900}.empty h1{font-size:2.25rem;margin:0 0 12px}.empty p{color:var(--muted);line-height:1.6}.quick{display:flex;flex-wrap:wrap;gap:9px;justify-content:center;margin-top:22px}.quick button{max-width:240px}
.msg{max-width:860px;margin:0 auto 24px;display:grid;grid-template-columns:34px minmax(0,1fr);gap:12px}.avatar{width:34px;height:34px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:900}.msg.user .avatar{background:#38264b}.msg.assistant .avatar{background:radial-gradient(circle,#e9c76f,#9d4dcf 60%,#2b123c)}.bubble{line-height:1.62;white-space:pre-wrap;word-break:break-word}.meta{font-size:.72rem;color:#8f829b;margin-top:8px}.tool-event{margin-top:8px;padding:8px 10px;border:1px solid #463253;border-radius:10px;background:#130c1b;color:#cbbdd5;font-size:.8rem}.attachments-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.attach-chip{border:1px solid var(--line);border-radius:9px;padding:5px 8px;font-size:.75rem;color:#d8cadf}
.composer-wrap{padding:14px max(18px,calc((100% - 900px)/2)) 20px;background:linear-gradient(180deg,transparent,#09060e 24%)}.uploads{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:8px}.composer{border:1px solid #4b3659;background:#15101c;border-radius:22px;padding:10px;box-shadow:0 18px 60px #0008}.composer textarea{width:100%;min-height:74px;max-height:220px;resize:none;border:0;outline:0;background:transparent;color:#fff;padding:9px 10px;line-height:1.45}.composer-bottom{display:flex;justify-content:space-between;align-items:center;gap:10px}.composer-actions{display:flex;gap:7px;align-items:center}.icon-btn{width:40px;height:40px;padding:0;border-radius:50%}.send{width:42px;height:42px;border-radius:50%;font-size:1.15rem}.status{font-size:.78rem;color:var(--muted)}
.panel{border:1px solid var(--line);background:#15101c;border-radius:16px;padding:14px;margin-bottom:14px}.panel h3{margin:0 0 9px;font-size:.94rem}.tools{display:flex;flex-wrap:wrap;gap:7px}.tool{font-size:.72rem;border:1px solid #44304f;background:#1a1024;border-radius:99px;padding:6px 8px}.tool.on{border-color:#7c5598;color:#f2defe}.tool.off{opacity:.45}.mode-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.mode{padding:8px;border-radius:9px;border:1px solid var(--line);background:#130d1a;color:#ddd;cursor:pointer}.mode.active{border-color:var(--gold);color:var(--gold)}
select.locale{max-width:145px;background:#17101f;color:#fff;border:1px solid var(--line);border-radius:10px;padding:7px}.mobile-toggle{display:none}
@media(max-width:1050px){.shell{grid-template-columns:250px minmax(0,1fr)}.inspector{display:none}}@media(max-width:720px){body{overflow:auto}.shell{display:block;height:auto;min-height:100vh}.side{display:none}.main{min-height:100vh}.messages{padding:22px 14px}.topbar{position:sticky;top:0;z-index:5}.mobile-toggle{display:inline-block}.composer-wrap{padding:12px}.empty{margin-top:5vh}}
</style></head><body>
<div class="shell">
<aside class="side"><div class="brand"><div class="orb"></div><div>Aura<div class="small">Sovereign AI Companion</div></div></div><button class="btn primary full" id="newChat">＋ New conversation</button><div class="threads" id="threads"></div></aside>
<main class="main"><header class="topbar"><div><div class="title" id="conversationTitle">Aura Workpage</div><div class="small" id="contextLine">Creative workspace</div></div><div class="top-actions"><select class="locale" id="locale"></select><span class="pill" id="planPill">Loading…</span></div></header>
<section class="messages" id="messages"><div class="empty" id="empty"><div class="aura-stage" id="auraStage" title="3D Aura rendering surface"></div><h1>What shall we create?</h1><p>Aura can talk, research, plan, write and operate the creative tools your account is allowed to use. Your conversations, project context and explicit memories stay attached to your account.</p><div class="quick"><button class="btn" data-prompt="Help me create a complete original song from an idea.">🎵 Create a song</button><button class="btn" data-prompt="Help me plan and generate a professional music video.">🎬 Create a music video</button><button class="btn" data-prompt="Research this topic thoroughly and cite the useful sources: ">🌐 Research</button><button class="btn" data-prompt="Review my current creative project and tell me what to improve next.">✨ Review project</button></div></div></section>
<div class="composer-wrap"><div class="uploads" id="uploads"></div><div class="composer"><textarea id="prompt" placeholder="Message Aura…" autocomplete="off"></textarea><div class="composer-bottom"><div class="composer-actions"><label class="btn icon-btn" title="Attach files">＋<input id="fileInput" type="file" multiple hidden accept="image/*,audio/*,video/*,.pdf,.txt,.md,.csv,.json,.yaml,.yml,.doc,.docx,.ppt,.pptx,.xls,.xlsx"></label><button class="btn icon-btn" id="mic" title="Talk to Aura">🎙</button><span class="status" id="status">Ready</span></div><button class="btn primary send" id="send" title="Send">↑</button></div></div></div></main>
<aside class="inspector"><div class="panel"><h3>Aura mode</h3><div class="mode-grid"><button class="mode active" data-mode="auto">Auto</button><button class="mode" data-mode="create">Create</button><button class="mode" data-mode="research">Research</button><button class="mode" data-mode="studio">Studio</button></div></div><div class="panel"><h3>Available tools</h3><div class="tools" id="tools"><span class="small">Loading capabilities…</span></div></div><div class="panel"><h3>Access context</h3><div class="small" id="access">Loading…</div></div><div class="panel"><h3>Workspace</h3><div class="small">Persistent chat · voice input · live translation · attachments · project context · memory · generation results · role-aware site tools.</div></div></aside>
</div>
<script>
const state={thread:null,attachments:[],mode:'auto',recording:false,recorder:null,chunks:[],cap:null};
const $=s=>document.querySelector(s); const esc=s=>(s??'').toString().replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url,opts={}){const r=await fetch(url,opts);let data=null;try{data=await r.json()}catch{}if(!r.ok)throw new Error(data?.detail||data?.message||('Request failed '+r.status));return data}
function setStatus(t){$('#status').textContent=t}
async function loadCapabilities(){const c=await api('/api/aura/capabilities');state.cap=c;$('#planPill').textContent=(c.plan||'').toUpperCase()+(c.roles?.length?' · '+c.roles.join('/'):'');$('#access').innerHTML=`Plan: <b>${esc(c.plan)}</b><br>ESP: <b>${esc(c.esp_status)}</b><br>Roles: ${esc((c.roles||[]).join(', ')||'creative user')}<br>Locale: ${esc(c.locale)}<br><br>${esc(c.role_boundary)}`;const tools=c.tools||[];$('#tools').innerHTML=tools.length?tools.map(x=>`<span class="tool on">${esc(x.replaceAll('_',' '))}</span>`).join(''):'<span class="small">Conversation only</span>';}
async function loadLocales(){const [langs,pref]=await Promise.all([api('/localization/languages'),api('/localization/preference')]);const sel=$('#locale');sel.innerHTML=langs.languages.map(l=>`<option value="${esc(l.locale)}">${esc(l.native_name)} · ${esc(l.english_name)}</option>`).join('');sel.value=pref.locale||'en';document.documentElement.dir=pref.direction||'ltr';sel.onchange=async()=>{const r=await api('/localization/preference',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({locale:sel.value})});document.documentElement.dir=r.direction||'ltr';setStatus('Language saved');};}
async function loadThreads(){const d=await api('/api/aura/threads');const root=$('#threads');root.innerHTML=(d.threads||[]).map(t=>`<button class="thread ${state.thread===t.id?'active':''}" data-id="${t.id}" title="${esc(t.title)}">${esc(t.title)}</button>`).join('')||'<div class="small" style="padding:12px">No conversations yet.</div>';root.querySelectorAll('.thread').forEach(b=>b.onclick=()=>openThread(b.dataset.id));}
function renderMessage(m){const role=m.role==='assistant'?'assistant':'user';const meta=m.metadata||{};let tools='';if(meta.tool_events?.length){tools=meta.tool_events.map(e=>`<div class="tool-event">${e.status==='completed'?'✓':'⚠'} ${esc(e.tool||'tool')} · ${esc(e.status||'')}</div>`).join('')}return `<article class="msg ${role}"><div class="avatar">${role==='assistant'?'A':'You'.slice(0,1)}</div><div><div class="bubble">${esc(m.content)}</div>${tools}<div class="meta">${esc(meta.provider||'')}</div></div></article>`}
async function openThread(id){state.thread=id;const d=await api(`/api/aura/threads/${id}/messages`);$('#conversationTitle').textContent=d.thread.title||'Aura';$('#contextLine').textContent=d.thread.scope?.replaceAll('_',' ')||'Creative workspace';$('#empty').style.display='none';$('#messages').innerHTML=(d.messages||[]).map(renderMessage).join('');$('#messages').scrollTop=$('#messages').scrollHeight;await loadThreads();}
function resetChat(){state.thread=null;state.attachments=[];$('#uploads').innerHTML='';$('#conversationTitle').textContent='Aura Workpage';$('#contextLine').textContent='Creative workspace';$('#messages').innerHTML=`<div class="empty" id="empty"><div class="aura-stage"></div><h1>What shall we create?</h1><p>Start a new conversation with Aura.</p></div>`;loadThreads();$('#prompt').focus();}
function renderUploads(){const root=$('#uploads');root.innerHTML=state.attachments.map(a=>`<span class="attach-chip">📎 ${esc(a.name)} <button data-rm="${a.id}" style="border:0;background:transparent;color:#aaa;cursor:pointer">×</button></span>`).join('');root.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{state.attachments=state.attachments.filter(a=>a.id!==b.dataset.rm);renderUploads()});}
async function uploadFiles(files){for(const file of files){setStatus('Uploading '+file.name+'…');const fd=new FormData();fd.append('file',file);if(state.thread)fd.append('thread_id',state.thread);const a=await api('/api/aura/attachments',{method:'POST',body:fd});state.attachments.push(a);renderUploads();}setStatus('Ready')}
async function send(){const box=$('#prompt');const message=box.value.trim();if(!message)return;box.value='';setStatus('Aura is working…');const temp={role:'user',content:message,metadata:{}};const empty=$('#empty');if(empty)empty.style.display='none';$('#messages').insertAdjacentHTML('beforeend',renderMessage(temp));$('#messages').scrollTop=$('#messages').scrollHeight;try{const d=await api('/api/aura/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,thread_id:state.thread,attachment_ids:state.attachments.map(a=>a.id),execute_tools:true,workspace_mode:state.mode})});state.thread=d.thread.id;state.attachments=[];renderUploads();$('#conversationTitle').textContent=d.thread.title||'Aura';$('#messages').insertAdjacentHTML('beforeend',renderMessage(d.message));$('#messages').scrollTop=$('#messages').scrollHeight;await loadThreads();setStatus('Ready')}catch(e){$('#messages').insertAdjacentHTML('beforeend',`<div class="msg assistant"><div class="avatar">A</div><div class="bubble">⚠ ${esc(e.message)}</div></div>`);setStatus('Error')}}
async function toggleMic(){if(state.recording){state.recorder.stop();return}if(!navigator.mediaDevices?.getUserMedia){setStatus('Microphone unavailable');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});state.chunks=[];const rec=new MediaRecorder(stream);state.recorder=rec;rec.ondataavailable=e=>{if(e.data.size)state.chunks.push(e.data)};rec.onstop=async()=>{state.recording=false;$('#mic').textContent='🎙';stream.getTracks().forEach(t=>t.stop());const blob=new Blob(state.chunks,{type:rec.mimeType||'audio/webm'});const fd=new FormData();fd.append('audio',blob,'aura-voice.webm');fd.append('target_locale',$('#locale').value||'en');fd.append('source_locale','auto');fd.append('speak_translation','false');try{setStatus('Understanding speech…');const d=await api('/speech/live-translate/chunk',{method:'POST',body:fd});$('#prompt').value=(d.translated_text||d.translation||d.transcript||d.source_transcript||'').trim();setStatus('Ready')}catch(e){setStatus(e.message)}};rec.start();state.recording=true;$('#mic').textContent='■';setStatus('Listening…')}catch(e){setStatus('Microphone permission denied')}}
$('#newChat').onclick=resetChat;$('#send').onclick=send;$('#prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$('#fileInput').onchange=e=>uploadFiles([...e.target.files]);$('#mic').onclick=toggleMic;document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode});document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('#prompt').value=b.dataset.prompt;$('#prompt').focus()});
Promise.all([loadCapabilities(),loadLocales(),loadThreads()]).catch(e=>setStatus(e.message));
</script></body></html>"""
    return HTMLResponse(html)
