from __future__ import annotations

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse

from .branding import ENDORSEMENT
from .esp_niche import require_esp_social_member

router = APIRouter()

CSS = r"""
:root{--bg:#03040a;--panel:#0c1020;--line:#ffffff1d;--text:#fff;--muted:#b8bfd2;--gold:#edca72;--violet:#9d70ff;--cyan:#58ddff;--green:#74dfa8}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 8% 0,#3b1766,transparent 29%),radial-gradient(circle at 94% 0,#123e72,transparent 26%),#03040a;color:var(--text);font-family:Inter,ui-sans-serif,system-ui,sans-serif}a{color:inherit;text-decoration:none}button,input,textarea,select{font:inherit}.wrap{width:min(1360px,calc(100% - 28px));margin:auto}.nav{position:sticky;top:0;z-index:10;border-bottom:1px solid var(--line);background:#05070deb;backdrop-filter:blur(18px)}.navin{min-height:70px;display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.brand{font-weight:950}.brand small{display:block;color:var(--gold);font-size:.64rem;letter-spacing:.08em;text-transform:uppercase}.btn{border:1px solid var(--line);border-radius:11px;padding:9px 12px;background:#ffffff08;color:#fff;font-weight:850;cursor:pointer}.primary{border:0;background:linear-gradient(115deg,var(--gold),var(--violet));color:#160d1e}.hero{padding:48px 0 22px}.eyebrow{font-size:.7rem;letter-spacing:.17em;text-transform:uppercase;color:var(--gold);font-weight:950}h1{font-size:clamp(2.7rem,7vw,5.5rem);line-height:.92;letter-spacing:-.06em;margin:.15em 0 .2em}.lead,.muted{color:var(--muted);line-height:1.6}.layout{display:grid;grid-template-columns:.88fr 1.12fr;gap:12px;padding-bottom:55px}.card{border:1px solid var(--line);border-radius:19px;background:linear-gradient(145deg,#11162a,#080b15);padding:15px}.stack{display:grid;gap:8px}.field{width:100%;border:1px solid var(--line);border-radius:11px;padding:10px;background:#060912;color:#fff;outline:none}.field:focus{border-color:var(--gold)}.elements{display:grid;grid-template-columns:1fr 1fr;gap:8px}.element,.variant{border:1px solid var(--line);border-radius:13px;padding:10px;background:#ffffff04}.element.current{border-color:#74dfa84c}.pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:4px 7px;font-size:.66rem;margin:2px}.pill.good{color:var(--green);border-color:#74dfa84c}.variants{display:grid;gap:8px}.row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.notice{display:none;border:1px solid var(--line);border-radius:11px;padding:10px;margin:10px 0}.notice.show{display:block}.notice.bad{color:#ffd7de;border-color:#ff90a455}.footer{border-top:1px solid var(--line);padding:28px 0 44px;color:var(--muted);font-size:.82rem}@media(max-width:900px){.layout,.row,.elements{grid-template-columns:1fr}}
"""

SCRIPT = r"""
const SOCIAL='/command-center/api/social',CREATIVE='/creative';let spaces=[],projects=[],caps={},manifest=null;const $=id=>document.getElementById(id);function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function pretty(v){return String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}function note(m,b=false){const n=$('notice');n.textContent=m;n.className='notice show'+(b?' bad':'');clearTimeout(window._n);window._n=setTimeout(()=>n.className='notice',6000)}async function req(u,o={}){const r=await fetch(u,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(o.headers||{})},...o});let b={};try{b=await r.json()}catch(_){}if(!r.ok)throw new Error(b.detail||`Request failed (${r.status})`);return b}
async function boot(){try{const[s,p,c]=await Promise.all([req(SOCIAL+'/spaces'),req(CREATIVE+'/projects'),req(SOCIAL+'/platforms')]);spaces=s.spaces||[];projects=p.projects||[];caps=c.capabilities||{};$('space').innerHTML='<option value="">Choose ESP Social House</option>'+spaces.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');$('project').innerHTML='<option value="">Choose Creative House project</option>'+projects.filter(x=>x.creative_manifest).map(x=>`<option value="${esc(x.project_name)}">${esc(x.title)} · ${esc(x.project_name)}</option>`).join('');$('platforms').innerHTML=Object.entries(caps).filter(([,s])=>s.planning!==false).map(([name])=>`<label class="pill"><input type="checkbox" data-platform="${esc(name)}"> ${esc(pretty(name))}</label>`).join('')}catch(e){note(e.message,true)}}
async function loadProject(){const name=$('project').value;manifest=null;$('elements').innerHTML='<div class="muted">Choose a project.</div>';if(!name)return;try{const d=await req(`${CREATIVE}/projects/${encodeURIComponent(name)}/manifest`);manifest=d.manifest;const active=new Set(manifest.active_element_ids||[]);const rows=(manifest.elements||[]).filter(e=>active.has(e.id)&&['image','video','audio','music','voice'].includes(e.kind));$('elements').innerHTML=rows.length?rows.map(e=>`<label class="element current"><input type="checkbox" data-element="${esc(e.id)}"><b>${esc(e.label)}</b><div><span class="pill good">CURRENT</span><span class="pill">${esc(e.kind)}</span></div><div class="muted" style="font-size:.68rem">${esc(e.id)}</div></label>`).join(''):'<div class="muted">No active media/music Creative Elements found.</div>'}catch(e){note(e.message,true)}}
function buildVariants(){const selected=[...document.querySelectorAll('[data-platform]:checked')].map(x=>x.dataset.platform);$('variants').innerHTML=selected.map(name=>{const spec=caps[name]||{},types=spec.content_types||[];return `<div class="variant" data-variant="${esc(name)}"><b>${esc(pretty(name))}</b><div class="muted" style="font-size:.68rem">${spec.caption_limit==null?'No registry caption cap':spec.caption_limit+' chars'} · ${spec.max_media==null?'No registry media cap':'max '+spec.max_media+' media'}</div><div class="stack" style="margin-top:7px"><select class="field" data-type>${types.map(t=>`<option value="${esc(t)}">${esc(pretty(t))}</option>`).join('')}</select><textarea class="field" data-caption placeholder="${esc(pretty(name))} launch caption"></textarea><input class="field" data-tags placeholder="Hashtags, spaces or commas"><div class="row"><input class="field" data-schedule type="datetime-local"><input class="field" data-zone value="${esc(Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC')}" placeholder="Timezone"></div></div></div>`}).join('')||'<div class="muted">Select one or more platforms.</div>'}
function tags(v){return String(v||'').split(/[\s,]+/).map(x=>x.replace(/^#+/,'').trim()).filter(Boolean).slice(0,100)}function date(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
async function createLaunch(){const space=$('space').value,project=$('project').value,title=$('title').value.trim(),sourceIds=[...document.querySelectorAll('[data-element]:checked')].map(x=>x.dataset.element),cards=[...document.querySelectorAll('[data-variant]')];if(!space)return note('Choose an ESP Social House.',true);if(!project)return note('Choose a Creative House project.',true);if(!title)return note('Enter a launch title.',true);if(!sourceIds.length)return note('Choose at least one current Creative DNA element.',true);if(!cards.length)return note('Choose at least one social platform.',true);const variants=cards.map(card=>({platform:card.dataset.variant,content_type:card.querySelector('[data-type]').value,caption:card.querySelector('[data-caption]').value.trim(),hashtags:tags(card.querySelector('[data-tags]').value),scheduled_at:date(card.querySelector('[data-schedule]').value),timezone:card.querySelector('[data-zone]').value.trim()||null,media_refs:[],auto_publish:false}));const approval=$('approval').checked,anyScheduled=variants.some(v=>v.scheduled_at),status=approval?'pending_approval':(anyScheduled?'scheduled':'draft');try{await req(`${SOCIAL}/spaces/${encodeURIComponent(space)}/content`,{method:'POST',body:JSON.stringify({title,status,approval_required:approval,content_pillars:[],variants,source_creative_project:project,source_creative_element_ids:sourceIds,notes:'Created from Creative → Social Launch provenance bridge.'})});note(`Launch plan created with ${variants.length} platform variant${variants.length===1?'':'s'} and ${sourceIds.length} Creative DNA source${sourceIds.length===1?'':'s'}.`);setTimeout(()=>location.href='/command-center/social',1000)}catch(e){note(e.message,true)}}
$('project').addEventListener('change',loadProject);$('platforms').addEventListener('change',buildVariants);$('create').onclick=createLaunch;boot();
"""


@router.get("/command-center/social/creative-launch", response_class=HTMLResponse, include_in_schema=False)
def creative_social_launch(request: Request):
    require_esp_social_member(request)
    html = f"""<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><meta name='robots' content='noindex,nofollow'><title>Creative → Social Launch</title><style>{CSS}</style></head><body><nav class='nav'><div class='wrap navin'><a class='brand' href='/command-center/social'>Elevate Souls Productions<small>Creative → Social Launch</small></a><div><a class='btn' href='/creative-house'>Creative House</a> <a class='btn' href='/command-center/social'>Social House</a></div></div></nav><main class='wrap'><section class='hero'><div class='eyebrow'>Creative DNA provenance bridge</div><h1>Turn a creation into a <span style='color:var(--gold)'>launch plan.</span></h1><p class='lead'>Link an ESP social content item to the exact current Creative DNA elements that produced it, then prepare destination-specific launch variants. This stores project/element IDs as provenance; it does not copy arbitrary server paths or publish externally.</p><div id='notice' class='notice'></div></section><section class='layout'><div class='card'><div class='eyebrow'>1 · Source</div><div class='stack'><select id='space' class='field'></select><select id='project' class='field'></select><div id='elements' class='elements'><div class='muted'>Choose a Creative House project.</div></div></div></div><div class='card'><div class='eyebrow'>2 · Launch variants</div><div class='stack'><input id='title' class='field' maxlength='300' placeholder='Launch / content title'><label class='muted'><input id='approval' type='checkbox'> Require approval before publishing</label><div id='platforms'></div><div id='variants' class='variants'><div class='muted'>Select one or more platforms.</div></div><button id='create' class='btn primary'>Create linked launch plan</button><div class='muted' style='font-size:.68rem'>Planning only: variants are saved with auto_publish=false. Media attachment and official platform publishing remain separate authorised steps.</div></div></div></section></main><footer class='footer'><div class='wrap'>{ENDORSEMENT}</div></footer><script>{SCRIPT}</script></body></html>"""
    return HTMLResponse(html)


__all__ = ["router", "SCRIPT"]
