from __future__ import annotations

from html import escape

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse, RedirectResponse

from .branding import PRODUCT_FULL_NAME
from .plans import GAME_CREATE

router = APIRouter(tags=["Aura Game Adventure Portal"])


@router.get("/game-creation/adventure/{game_id}", response_class=HTMLResponse, include_in_schema=False)
def adventure_portal(game_id: str, request: Request):
    member = getattr(request.state, "member", None)
    if member is None:
        return RedirectResponse(f"/signin?next=/game-creation/adventure/{escape(game_id, quote=True)}", status_code=303)
    if not member.plan.has(GAME_CREATE):
        return RedirectResponse("/game-creation", status_code=303)
    safe_game_id = escape(game_id, quote=True)
    safe_brand = escape(PRODUCT_FULL_NAME)
    html = r"""<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><meta name='robots' content='noindex,nofollow'><title>Adventure State — __BRAND__</title><style>
:root{--bg:#04050b;--panel:#0c1120;--line:#ffffff22;--gold:#efca6d;--violet:#986cff;--cyan:#5be1ff;--green:#79dda5;--red:#ff8fa5;--muted:#bcc5d5}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 8% 0,#4a176a66,transparent 34%),radial-gradient(circle at 92% 8%,#12445f55,transparent 30%),var(--bg);color:#fff;font-family:Inter,system-ui,sans-serif}.wrap{width:min(1420px,calc(100% - 24px));margin:auto}.nav{position:sticky;top:0;z-index:30;background:#05070eef;border-bottom:1px solid var(--line);backdrop-filter:blur(14px)}.navin{min-height:66px;display:flex;align-items:center;justify-content:space-between;gap:9px;flex-wrap:wrap}.brand{font-weight:950;color:#fff;text-decoration:none}.brand small{display:block;color:var(--gold);font-size:.65rem;letter-spacing:.12em;text-transform:uppercase}.hero{padding:32px 0 16px}.eyebrow{color:var(--gold);font-size:.68rem;font-weight:950;letter-spacing:.14em;text-transform:uppercase}h1{font-size:clamp(2.4rem,6vw,5rem);letter-spacing:-.05em;line-height:.92;margin:.12em 0}.muted{color:var(--muted);line-height:1.55}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;padding-bottom:70px}.card{border:1px solid var(--line);border-radius:18px;background:linear-gradient(145deg,#111729e9,#090d18ee);padding:15px}.row{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}.form{display:grid;gap:8px;margin-top:10px}.two{display:grid;grid-template-columns:1fr 1fr;gap:8px}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}input,select,textarea,button{font:inherit}input,select,textarea{width:100%;border:1px solid var(--line);background:#070a12;color:#fff;border-radius:10px;padding:9px}textarea{min-height:76px;resize:vertical}button,.btn{border:1px solid var(--line);background:#ffffff08;color:#fff;border-radius:10px;padding:9px 11px;font-weight:850;cursor:pointer;text-decoration:none}.primary{border:0;background:linear-gradient(120deg,var(--gold),var(--violet));color:#160c1d}.danger{border-color:#ff8fa566;color:#ffd8df}.entry{border:1px solid var(--line);border-radius:12px;padding:10px;margin-top:8px;background:#ffffff05}.entry h3{margin:3px 0}.mini{font-size:.75rem;color:var(--muted)}.pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:3px 7px;font-size:.68rem}.notice{display:none;margin:10px 0;padding:10px;border:1px solid var(--line);border-radius:10px}.notice.show{display:block}.privacy{border-left:3px solid var(--green);padding-left:11px}.empty{color:var(--muted);padding:14px;border:1px dashed #ffffff2c;border-radius:10px}.sectionList{max-height:360px;overflow:auto}.wide{grid-column:1/-1}@media(max-width:900px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}}@media(max-width:560px){.two,.three{grid-template-columns:1fr}.navin>div{display:flex;gap:5px;flex-wrap:wrap}}
</style></head><body><nav class='nav'><div class='wrap navin'><a class='brand' href='/game-creation'>__BRAND__<small>Aura Game Forge · Adventure State</small></a><div><a class='btn' href='/game-creation/gameplay/__GAME_ID__'>Gameplay & Physics</a> <button id='scanBtn'>Scan</button> <button id='buildBtn' class='primary'>Build & Play</button></div></div></nav><main class='wrap'><section class='hero'><div class='eyebrow'>Integrity-bound no-code adventure systems</div><h1 id='title'>Adventure State</h1><p class='muted'>Author objectives, inventory, dialogue choices, gates and state flags as typed Game Forge data. Runtime progress saves only in the player’s browser and is version-bound to the current game integrity hash.</p><div id='notice' class='notice'></div></section><section class='grid'>
<div class='card'><div class='eyebrow'>Inventory definitions</div><h2>Items</h2><form id='itemForm' class='form'><input id='itemName' maxlength='120' placeholder='Item name' required><textarea id='itemDescription' maxlength='600' placeholder='Description'></textarea><div class='two'><input id='itemStack' type='number' min='1' max='9999' value='99' aria-label='Max stack'><label><input id='itemConsumable' type='checkbox' style='width:auto'> Consumable</label></div><button class='primary'>Add item</button></form><div id='items' class='sectionList'></div></div>
<div class='card'><div class='eyebrow'>Quest progression</div><h2>Objectives</h2><form id='objectiveForm' class='form'><input id='objectiveTitle' maxlength='160' placeholder='Objective title' required><textarea id='objectiveDescription' maxlength='800' placeholder='Description'></textarea><div class='two'><select id='objectiveKind'><option value='collect'>Collect</option><option value='reach'>Reach</option><option value='talk'>Talk</option><option value='flag'>State flag</option><option value='timer'>Timer</option></select><input id='objectiveTarget' maxlength='160' placeholder='Target entity ID / blank for flag or timer'></div><div class='three'><input id='objectiveCount' type='number' min='1' value='1' aria-label='Target count'><input id='objectiveFlag' maxlength='120' placeholder='Flag name'><input id='objectiveSeconds' type='number' min='.1' step='.1' placeholder='Seconds'></div><div class='two'><select id='objectiveReward'><option value=''>No item reward</option></select><input id='objectiveCompleteFlag' maxlength='120' placeholder='Completion flag'></div><button class='primary'>Add objective</button></form><div id='objectives' class='sectionList'></div></div>
<div class='card'><div class='eyebrow'>Character interaction</div><h2>Dialogue</h2><form id='dialogueForm' class='form'><div class='two'><input id='dialogueEntity' maxlength='160' placeholder='Trigger entity ID' required><input id='dialogueSpeaker' maxlength='120' placeholder='Speaker' value='Character'></div><textarea id='dialogueLines' placeholder='Dialogue lines — one line per paragraph' required></textarea><div class='two'><input id='dialogueFlag' maxlength='120' placeholder='Completion flag'><label><input id='dialogueOnce' type='checkbox' style='width:auto' checked> Once only</label></div><button class='primary'>Add dialogue</button></form><div id='dialogues' class='sectionList'></div></div>
<div class='card'><div class='eyebrow'>Conditional world access</div><h2>Gates & doors</h2><form id='gateForm' class='form'><input id='gateLabel' maxlength='120' placeholder='Gate label' required><div class='two'><input id='gateTrigger' maxlength='160' placeholder='Trigger entity ID' required><input id='gateDoor' maxlength='160' placeholder='Door entity ID (optional)'></div><div class='two'><input id='gateFlag' maxlength='120' placeholder='Required flag'><select id='gateItem'><option value=''>No required item</option></select></div><div class='two'><input id='gateOpenFlag' maxlength='120' placeholder='Set flag when opened'><label><input id='gateConsume' type='checkbox' style='width:auto'> Consume required item</label></div><button class='primary'>Add gate</button></form><div id='gates' class='sectionList'></div></div>
<div class='card wide privacy'><div class='eyebrow'>Save/privacy contract</div><h2>Browser-local play state</h2><div id='runtimeInfo' class='muted'>Loading Adventure runtime contract…</div><p class='mini'>The authored Adventure DNA lives with the private game project and participates in integrity checks. Player progress is not uploaded to the Command Center, contains no profile/personal fields, and old saves are automatically isolated when the game integrity hash changes.</p></div>
</section></main><script>
'use strict';const GAME_ID='__GAME_ID__';const $=id=>document.getElementById(id);function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function notice(v,bad=false){const e=$('notice');e.textContent=v;e.className='notice show';e.style.borderColor=bad?'#ff8fa566':'#79dda566';clearTimeout(window.__advNotice);window.__advNotice=setTimeout(()=>e.className='notice',6500)}async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(typeof b.detail==='string'?b.detail:(b.detail?.message||`Request failed (${r.status})`));return b}function delButton(collection,id){return`<button class='danger' data-delete='${esc(collection)}' data-id='${esc(id)}'>Delete</button>`}function entry(title,meta,collection,id){return`<article class='entry'><div class='row'><div><h3>${esc(title)}</h3><div class='mini'>${esc(meta)}</div></div>${delButton(collection,id)}</div></article>`}
let STATE=null;function render(s){STATE=s;const a=s.adventure||{},items=a.items||[],objectives=a.objectives||[],dialogues=a.dialogues||[],gates=a.gates||[];$('items').innerHTML=items.map(x=>entry(x.name,`${x.description||'No description'} · max ${x.max_stack}${x.consumable?' · consumable':''}`,'items',x.id)).join('')||'<div class="empty">No items authored.</div>';$('objectives').innerHTML=objectives.map(x=>entry(x.title,`${x.kind}${x.target_entity_id?' · '+x.target_entity_id:''}${x.flag?' · flag '+x.flag:''}`,'objectives',x.id)).join('')||'<div class="empty">No objectives authored.</div>';$('dialogues').innerHTML=dialogues.map(x=>entry(x.speaker,`${x.trigger_entity_id} · ${x.lines.length} line(s)`,'dialogues',x.id)).join('')||'<div class="empty">No dialogue authored.</div>';$('gates').innerHTML=gates.map(x=>entry(x.label,`${x.trigger_entity_id}${x.requires_flag?' · flag '+x.requires_flag:''}${x.requires_item_id?' · item required':''}`,'gates',x.id)).join('')||'<div class="empty">No gates authored.</div>';for(const id of ['objectiveReward','gateItem']){const sel=$(id),current=sel.value;const first=id==='objectiveReward'?'No item reward':'No required item';sel.innerHTML=`<option value=''>${first}</option>`+items.map(x=>`<option value='${esc(x.id)}'>${esc(x.name)}</option>`).join('');sel.value=current}const p=s.runtime?.save_policy||{};$('runtimeInfo').innerHTML=`Adventure revision <b>${esc(a.revision)}</b><br>Storage: <b>${esc(p.storage||'browser_local_only')}</b> · server sync: <b>${p.server_sync?'on':'off'}</b> · personal data: <b>${p.personal_data?'yes':'no'}</b><br>Arbitrary creator script source: <b>${s.runtime?.arbitrary_script_source_allowed?'enabled':'disabled'}</b>`}
async function load(){try{const [game,state]=await Promise.all([api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}`),api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/adventure`)]);$('title').textContent=`${game.title} · Adventure State`;render(state)}catch(e){notice(e.message,true)}}
$('itemForm').addEventListener('submit',async e=>{e.preventDefault();try{const s=await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/adventure/items`,{method:'POST',body:JSON.stringify({name:$('itemName').value,description:$('itemDescription').value,max_stack:Number($('itemStack').value||99),consumable:$('itemConsumable').checked})});notice('Item added; previous build/rating invalidated.');$('itemName').value='';render(s)}catch(err){notice(err.message,true)}});
$('objectiveForm').addEventListener('submit',async e=>{e.preventDefault();try{const kind=$('objectiveKind').value,target=$('objectiveTarget').value.trim(),flag=$('objectiveFlag').value.trim(),seconds=$('objectiveSeconds').value;const body={title:$('objectiveTitle').value,description:$('objectiveDescription').value,kind,target_entity_id:target||null,target_count:Number($('objectiveCount').value||1),flag:flag||null,seconds:seconds?Number(seconds):null,reward_item_id:$('objectiveReward').value||null,completion_flag:$('objectiveCompleteFlag').value.trim()||null};const s=await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/adventure/objectives`,{method:'POST',body:JSON.stringify(body)});notice('Objective added.');render(s)}catch(err){notice(err.message,true)}});
$('dialogueForm').addEventListener('submit',async e=>{e.preventDefault();try{const lines=$('dialogueLines').value.split(/\n+/).map(x=>x.trim()).filter(Boolean);const s=await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/adventure/dialogues`,{method:'POST',body:JSON.stringify({trigger_entity_id:$('dialogueEntity').value,speaker:$('dialogueSpeaker').value||'Character',lines,choices:[],once:$('dialogueOnce').checked,completion_flag:$('dialogueFlag').value.trim()||null})});notice('Dialogue added.');render(s)}catch(err){notice(err.message,true)}});
$('gateForm').addEventListener('submit',async e=>{e.preventDefault();try{const s=await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/adventure/gates`,{method:'POST',body:JSON.stringify({trigger_entity_id:$('gateTrigger').value,door_entity_id:$('gateDoor').value.trim()||null,label:$('gateLabel').value,requires_flag:$('gateFlag').value.trim()||null,requires_item_id:$('gateItem').value||null,consume_item:$('gateConsume').checked,open_flag:$('gateOpenFlag').value.trim()||null})});notice('Gate added.');render(s)}catch(err){notice(err.message,true)}});
document.querySelector('.grid').addEventListener('click',async e=>{const b=e.target.closest('button[data-delete]');if(!b)return;if(!confirm('Delete this Adventure State entry?'))return;try{const s=await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/adventure/${encodeURIComponent(b.dataset.delete)}/${encodeURIComponent(b.dataset.id)}`,{method:'DELETE'});notice('Adventure State entry deleted.');render(s)}catch(err){notice(err.message,true)}});
$('scanBtn').addEventListener('click',async()=>{try{const r=await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/scan`,{method:'POST'});notice(r.public_test_allowed?'Integrity/rating scan passed.':`Scan completed with ${(r.blockers||[]).length} blocker(s).`,!r.public_test_allowed)}catch(e){notice(e.message,true)}});$('buildBtn').addEventListener('click',async()=>{try{const r=await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/build`,{method:'POST'});notice(`Built ${r.runtime}. Opening private playtest…`);window.open(r.private_playtest_url,'_blank','noopener')}catch(e){notice(e.message,true)}});load();
</script></body></html>"""
    return HTMLResponse(html.replace("__BRAND__", safe_brand).replace("__GAME_ID__", safe_game_id))


__all__ = ["router"]