from __future__ import annotations

from html import escape

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse, RedirectResponse

from .branding import PRODUCT_FULL_NAME
from .plans import GAME_CREATE

router = APIRouter(tags=["Aura Game World Logic Portal"])


@router.get("/game-creation/world-logic/{game_id}", response_class=HTMLResponse, include_in_schema=False)
def world_logic_portal(game_id: str, request: Request):
    member = getattr(request.state, "member", None)
    if member is None:
        return RedirectResponse(f"/signin?next=/game-creation/world-logic/{escape(game_id, quote=True)}", status_code=303)
    if not member.plan.has(GAME_CREATE):
        return RedirectResponse("/game-creation", status_code=303)
    safe_game_id = escape(game_id, quote=True)
    safe_brand = escape(PRODUCT_FULL_NAME)
    html = r"""<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><meta name='robots' content='noindex,nofollow'><title>Advanced World Logic — __BRAND__</title><style>
:root{--bg:#04050b;--panel:#0c1120;--line:#ffffff22;--gold:#efca6d;--violet:#986cff;--cyan:#5be1ff;--green:#79dda5;--red:#ff8fa5;--muted:#bcc5d5}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 7% 0,#40165f66,transparent 34%),radial-gradient(circle at 93% 5%,#10465d55,transparent 30%),var(--bg);color:#fff;font-family:Inter,system-ui,sans-serif}.wrap{width:min(1300px,calc(100% - 24px));margin:auto}.nav{position:sticky;top:0;z-index:20;background:#05070eef;border-bottom:1px solid var(--line);backdrop-filter:blur(14px)}.navin{min-height:66px;display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}.brand{font-weight:950;color:#fff;text-decoration:none}.brand small{display:block;color:var(--gold);font-size:.65rem;letter-spacing:.12em;text-transform:uppercase}.hero{padding:34px 0 18px}.eyebrow{color:var(--gold);font-size:.68rem;font-weight:950;letter-spacing:.14em;text-transform:uppercase}h1{font-size:clamp(2.5rem,6vw,5.2rem);line-height:.92;letter-spacing:-.05em;margin:.12em 0}.muted{color:var(--muted);line-height:1.55}.grid{display:grid;grid-template-columns:.85fr 1.15fr;gap:12px;padding-bottom:70px}.card{border:1px solid var(--line);border-radius:18px;background:linear-gradient(145deg,#111729e9,#090d18ee);padding:15px}.form{display:grid;gap:8px;margin-top:10px}.two{display:grid;grid-template-columns:1fr 1fr;gap:8px}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}input,select,button{font:inherit}input,select{width:100%;border:1px solid var(--line);background:#070a12;color:#fff;border-radius:10px;padding:9px}button,.btn{border:1px solid var(--line);background:#ffffff08;color:#fff;border-radius:10px;padding:9px 11px;font-weight:850;cursor:pointer;text-decoration:none}.primary{border:0;background:linear-gradient(120deg,var(--gold),var(--violet));color:#160c1d}.entry{border:1px solid var(--line);border-radius:12px;padding:11px;margin-top:8px;background:#ffffff05}.mini{font-size:.75rem;color:var(--muted)}.pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:3px 7px;font-size:.68rem;margin:2px}.notice{display:none;margin:10px 0;padding:10px;border:1px solid var(--line);border-radius:10px}.notice.show{display:block}.empty{color:var(--muted);padding:14px;border:1px dashed #ffffff2c;border-radius:10px}.privacy{border-left:3px solid var(--green);margin-top:12px}@media(max-width:900px){.grid{grid-template-columns:1fr}}@media(max-width:560px){.two,.three{grid-template-columns:1fr}}
</style></head><body><nav class='nav'><div class='wrap navin'><a class='brand' href='/game-creation'>__BRAND__<small>Aura Game Forge · Advanced World Logic</small></a><div><a class='btn' href='/game-creation/gameplay/__GAME_ID__'>Gameplay & Physics</a> <a class='btn' href='/game-creation/adventure/__GAME_ID__'>Adventure State</a> <button id='scanBtn'>Scan</button> <button id='buildBtn' class='primary'>Build & Play</button></div></div></nav><main class='wrap'><section class='hero'><div class='eyebrow'>Closed, typed World DNA automation</div><h1 id='title'>Advanced World Logic</h1><p class='muted'>Create bounded NPC followers/escorts, timed triggers and proximity-driven automatic doors. Aura executes only the allow-listed DNA below—no creator JavaScript or Python and no runtime network access.</p><div id='notice' class='notice'></div></section><section class='grid'><div><div class='card'><div class='eyebrow'>Create safe logic entity</div><h2>Preset builder</h2><form id='createForm' class='form'><input id='name' maxlength='160' placeholder='Entity name' required><select id='preset'><option value='npc_follow'>NPC Follow / Escort</option><option value='timed_trigger'>Timed Trigger</option><option value='auto_door'>Automatic Door</option></select><div class='three'><input id='x' type='number' step='.1' value='0' aria-label='X'><input id='y' type='number' step='.1' value='0' aria-label='Y'><input id='z' type='number' step='.1' value='0' aria-label='Z'></div><button class='primary'>Add to World DNA</button></form></div><div class='card privacy'><div class='eyebrow'>Safety contract</div><h3>Integrity-bound logic</h3><p class='muted'>Followers must point to an existing World entity and use kinematic/dynamic Physics DNA. Doors require kinematic Physics DNA. Every edit invalidates stale builds and ratings before public testing.</p></div></div><div><div class='card'><div class='eyebrow'>Current logic</div><h2>World DNA entities</h2><div id='logic'><div class='empty'>Loading…</div></div></div><div class='card' style='margin-top:12px'><div class='eyebrow'>Apply preset to existing entity</div><h3>Convert a non-core World entity</h3><form id='applyForm' class='form'><select id='entity'><option value=''>Choose World entity</option></select><select id='applyPreset'><option value='npc_follow'>NPC Follow / Escort</option><option value='timed_trigger'>Timed Trigger</option><option value='auto_door'>Automatic Door</option></select><button>Apply safe preset</button></form></div></div></section></main><script>
'use strict';const GAME_ID='__GAME_ID__';const $=id=>document.getElementById(id);function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function notice(v,bad=false){const e=$('notice');e.textContent=v;e.className='notice show';e.style.borderColor=bad?'#ff8fa566':'#79dda566';clearTimeout(window.__logicNotice);window.__logicNotice=setTimeout(()=>e.className='notice',6500)}async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(typeof b.detail==='string'?b.detail:(b.detail?.message||`Request failed (${r.status})`));return b}
function renderLogic(state){const rows=state.entities||[];$('logic').innerHTML=rows.map(row=>{const ops=(row.behaviors||[]).map(b=>b.op).join(', ');return`<article class='entry'><b>${esc(row.name)}</b><div class='mini'>${esc(row.id)}</div><span class='pill'>${esc(row.kind)}</span><span class='pill'>${esc(ops||'logic')}</span><div class='mini'>Physics: ${esc(row.physics?.mode||'none')}</div></article>`}).join('')||'<div class="empty">No Advanced World Logic entities yet.</div>'}
async function load(){try{const [game,state,world]=await Promise.all([api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}`),api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/world-logic`),api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/world`)]);$('title').textContent=`${game.title} · Advanced World Logic`;renderLogic(state);const current=$('entity').value;$('entity').innerHTML='<option value="">Choose World entity</option>'+(world.world?.entities||[]).filter(e=>!['player','camera'].includes(e.id)).map(e=>`<option value='${esc(e.id)}'>${esc(e.name)} · ${esc(e.id)}</option>`).join('');$('entity').value=current}catch(e){notice(e.message,true)}}
$('createForm').addEventListener('submit',async e=>{e.preventDefault();try{await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/world-logic/entities`,{method:'POST',body:JSON.stringify({name:$('name').value,preset:$('preset').value,position:{x:Number($('x').value||0),y:Number($('y').value||0),z:Number($('z').value||0)},scale:{x:1,y:1,z:1}})});notice('Advanced World Logic entity added; previous build/rating invalidated.');$('name').value='';await load()}catch(err){notice(err.message,true)}});
$('applyForm').addEventListener('submit',async e=>{e.preventDefault();if(!$('entity').value)return notice('Choose a World entity first.',true);try{await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/world-logic/entities/${encodeURIComponent($('entity').value)}/preset`,{method:'POST',body:JSON.stringify({preset:$('applyPreset').value})});notice('Safe World Logic preset applied.');await load()}catch(err){notice(err.message,true)}});
$('scanBtn').addEventListener('click',async()=>{try{const r=await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/scan`,{method:'POST'});notice(r.public_test_allowed?'Integrity/rating scan passed.':`Scan completed with ${(r.blockers||[]).length} blocker(s).`,!r.public_test_allowed)}catch(e){notice(e.message,true)}});$('buildBtn').addEventListener('click',async()=>{try{const r=await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/build`,{method:'POST'});notice(`Built ${r.runtime}. Opening private playtest…`);window.open(r.private_playtest_url,'_blank','noopener')}catch(e){notice(e.message,true)}});load();
</script></body></html>"""
    return HTMLResponse(html.replace("__BRAND__", safe_brand).replace("__GAME_ID__", safe_game_id))


__all__ = ["router"]
