from __future__ import annotations

import json
from html import escape

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse, RedirectResponse

from .branding import PRODUCT_FULL_NAME
from .plans import GAME_CREATE

router = APIRouter(tags=["Aura Game State Machine Portal"])


@router.get("/game-creation/state-machines/{game_id}", response_class=HTMLResponse, include_in_schema=False)
def state_machine_portal(game_id: str, request: Request):
    member = getattr(request.state, "member", None)
    if member is None:
        return RedirectResponse(f"/signin?next=/game-creation/state-machines/{escape(game_id, quote=True)}", status_code=303)
    if not member.plan.has(GAME_CREATE):
        return RedirectResponse("/game-creation", status_code=303)

    safe_brand = escape(PRODUCT_FULL_NAME)
    safe_game_id = escape(game_id, quote=True)
    game_json = json.dumps(game_id)
    page = r"""<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><meta name='robots' content='noindex,nofollow'><title>State Machines — __BRAND__</title><style>
:root{--bg:#04050b;--panel:#0e1322;--line:#ffffff22;--gold:#efca6d;--violet:#986cff;--cyan:#5be1ff;--green:#79dda5;--red:#ff8fa5;--muted:#bcc5d5}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 8% 0,#42165f66,transparent 32%),radial-gradient(circle at 92% 8%,#0e4a6755,transparent 29%),var(--bg);color:#fff;font-family:Inter,system-ui,sans-serif}.wrap{width:min(1340px,calc(100% - 24px));margin:auto}.nav{position:sticky;top:0;z-index:20;background:#05070eef;border-bottom:1px solid var(--line);backdrop-filter:blur(14px)}.navin{min-height:66px;display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}.brand{font-weight:950;color:#fff;text-decoration:none}.brand small{display:block;color:var(--gold);font-size:.65rem;letter-spacing:.12em;text-transform:uppercase}.hero{padding:34px 0 18px}.eyebrow{color:var(--gold);font-size:.68rem;font-weight:950;letter-spacing:.14em;text-transform:uppercase}h1{font-size:clamp(2.5rem,6vw,5rem);line-height:.92;letter-spacing:-.05em;margin:.12em 0}.muted{color:var(--muted);line-height:1.55}.grid{display:grid;grid-template-columns:.9fr 1.1fr;gap:12px;padding-bottom:70px}.card{border:1px solid var(--line);border-radius:18px;background:linear-gradient(145deg,#111729e9,#090d18ee);padding:15px;margin-bottom:12px}.form{display:grid;gap:8px;margin-top:10px}.two{display:grid;grid-template-columns:1fr 1fr;gap:8px}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}input,select,button,textarea{font:inherit}input,select,textarea{width:100%;border:1px solid var(--line);background:#070a12;color:#fff;border-radius:10px;padding:9px}textarea{min-height:150px;resize:vertical}button,.btn{border:1px solid var(--line);background:#ffffff08;color:#fff;border-radius:10px;padding:9px 11px;font-weight:850;cursor:pointer;text-decoration:none}.primary{border:0;background:linear-gradient(120deg,var(--gold),var(--violet));color:#160c1d}.danger{border-color:#ff8fa566;color:#ffd6de}.entry{border:1px solid var(--line);border-radius:12px;padding:11px;margin-top:8px;background:#ffffff05}.row{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}.mini{font-size:.75rem;color:var(--muted)}.pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:3px 7px;font-size:.68rem;margin:2px}.notice{display:none;margin:10px 0;padding:10px;border:1px solid var(--line);border-radius:10px}.notice.show{display:block}.empty{color:var(--muted);padding:14px;border:1px dashed #ffffff2c;border-radius:10px}.safe{border-left:3px solid var(--green)}@media(max-width:920px){.grid{grid-template-columns:1fr}}@media(max-width:600px){.two,.three{grid-template-columns:1fr}}
</style></head><body><nav class='nav'><div class='wrap navin'><a class='brand' href='/game-creation'>__BRAND__<small>Aura Game Forge · State Machines</small></a><div><a class='btn' href='/game-creation/world-events/__GAME_ID__'>World Events</a> <a class='btn' href='/game-creation/adventure/__GAME_ID__'>Adventure State</a> <button id='scanBtn'>Scan</button> <button id='buildBtn' class='primary'>Build & Play</button></div></div></nav><main class='wrap'><section class='hero'><div class='eyebrow'>Bounded no-code state graphs</div><h1 id='title'>State Machines</h1><p class='muted'>Create deterministic actors whose state changes only from bounded timers, player proximity or declared Adventure flags. One transition is allowed per actor per frame; creator JavaScript, Python, expressions and callbacks are not accepted.</p><div id='notice' class='notice'></div></section><section class='grid'><div><div class='card'><div class='eyebrow'>Create Actor</div><h2>Safe state graph template</h2><form id='createForm' class='form'><input id='name' maxlength='160' placeholder='Actor name' required><div class='three'><input id='x' type='number' step='.1' value='0' aria-label='X'><input id='y' type='number' step='.1' value='0' aria-label='Y'><input id='z' type='number' step='.1' value='0' aria-label='Z'></div><select id='template'><option value='timed'>Timed two-state cycle</option><option value='proximity'>Player-near activation</option><option value='flag'>Adventure-flag activation</option></select><div class='two'><input id='seconds' type='number' min='.05' max='86400' step='.1' value='3' aria-label='Timer seconds'><input id='radius' type='number' min='.1' max='100000' step='.1' value='3' aria-label='Proximity radius'></div><select id='flag'><option value=''>Choose declared Adventure flag</option></select><button class='primary'>Create State Machine Actor</button></form></div><div class='card safe'><div class='eyebrow'>Runtime limits</div><h3>Closed transition model</h3><p class='muted'>Maximum 16 states and 64 transitions per machine. The runtime permits at most one transition per actor per animation frame. Adventure-flag conditions must reference a flag already declared by Adventure State DNA.</p></div></div><div><div class='card'><div class='row'><div><div class='eyebrow'>Current State Machines</div><h2>Integrity-bound actors</h2></div><button id='refreshBtn'>Refresh</button></div><div id='machines'><div class='empty'>Loading…</div></div></div><div class='card'><div class='eyebrow'>Advanced typed graph</div><h3>Replace selected machine</h3><p class='mini'>This editor accepts StateMachineDNA JSON only. Unknown fields, undefined states and missing trigger parameters are rejected by the server.</p><select id='entity'><option value=''>Choose State Machine actor</option></select><textarea id='machineJson' spellcheck='false' aria-label='Typed State Machine JSON'></textarea><button id='replaceBtn'>Validate & Replace Graph</button></div></div></section></main><script>
'use strict';const GAME_ID=__GAME_JSON__;const $=id=>document.getElementById(id);let STATE=null;function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function notice(v,bad=false){const e=$('notice');e.textContent=v;e.className='notice show';e.style.borderColor=bad?'#ff8fa566':'#79dda566';clearTimeout(window.__smNotice);window.__smNotice=setTimeout(()=>e.className='notice',6500)}async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(typeof b.detail==='string'?b.detail:(b.detail?.message||`Request failed (${r.status})`));return b}
function machineTemplate(){const kind=$('template').value,seconds=Math.max(.05,Number($('seconds').value||3)),radius=Math.max(.1,Number($('radius').value||3)),flag=$('flag').value;const states=[{state:'idle',label:'Idle',visible:true,offset:{x:0,y:0,z:0},message:''},{state:'active',label:'Active',visible:true,offset:{x:0,y:1,z:0},message:'State changed'}];let transitions;if(kind==='timed')transitions=[{from_state:'idle',to_state:'active',trigger:'timer',seconds,min_state_seconds:.1},{from_state:'active',to_state:'idle',trigger:'timer',seconds,min_state_seconds:.1}];else if(kind==='proximity')transitions=[{from_state:'idle',to_state:'active',trigger:'player_near',radius,min_state_seconds:.1},{from_state:'active',to_state:'idle',trigger:'timer',seconds,min_state_seconds:.1}];else{if(!flag)throw new Error('Choose a declared Adventure flag first.');transitions=[{from_state:'idle',to_state:'active',trigger:'adventure_flag',flag,flag_value:true,min_state_seconds:.1}]}return{initial_state:'idle',states,transitions}}
function render(state){STATE=state;const rows=state.entities||[];$('machines').innerHTML=rows.map(row=>`<article class='entry'><div class='row'><div><b>${esc(row.name)}</b><div class='mini'>${esc(row.id)}</div></div><button class='danger deleteMachine' data-id='${esc(row.id)}'>Delete</button></div><span class='pill'>${row.machine.states.length} states</span><span class='pill'>${row.machine.transitions.length} transitions</span><span class='pill'>Initial: ${esc(row.machine.initial_state)}</span></article>`).join('')||'<div class="empty">No State Machine actors authored yet.</div>';$('entity').innerHTML='<option value="">Choose State Machine actor</option>'+rows.map(row=>`<option value='${esc(row.id)}'>${esc(row.name)} · ${esc(row.id)}</option>`).join('');$('flag').innerHTML='<option value="">Choose declared Adventure flag</option>'+(state.declared_adventure_flags||[]).map(f=>`<option value='${esc(f)}'>${esc(f)}</option>`).join('');document.querySelectorAll('.deleteMachine').forEach(btn=>btn.addEventListener('click',()=>removeMachine(btn.dataset.id)))}
async function load(){try{const [game,state]=await Promise.all([api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}`),api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/state-machines`)]);$('title').textContent=`${game.title} · State Machines`;render(state)}catch(e){notice(e.message,true)}}
$('createForm').addEventListener('submit',async e=>{e.preventDefault();try{const body={name:$('name').value,position:{x:Number($('x').value||0),y:Number($('y').value||0),z:Number($('z').value||0)},machine:machineTemplate()};await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/state-machines/entities`,{method:'POST',body:JSON.stringify(body)});notice('State Machine created; previous build/rating invalidated.');$('name').value='';await load()}catch(err){notice(err.message,true)}});
$('entity').addEventListener('change',()=>{const row=(STATE?.entities||[]).find(x=>x.id===$('entity').value);$('machineJson').value=row?JSON.stringify(row.machine,null,2):''});$('replaceBtn').addEventListener('click',async()=>{if(!$('entity').value)return notice('Choose a State Machine actor.',true);try{const machine=JSON.parse($('machineJson').value||'{}');await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/state-machines/entities/${encodeURIComponent($('entity').value)}`,{method:'PUT',body:JSON.stringify({machine})});notice('State Machine graph validated and replaced.');await load()}catch(e){notice(e.message,true)}});async function removeMachine(id){if(!id||!confirm('Delete this dedicated State Machine actor?'))return;try{await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/state-machines/entities/${encodeURIComponent(id)}`,{method:'DELETE'});notice('State Machine deleted.');await load()}catch(e){notice(e.message,true)}}
$('refreshBtn').addEventListener('click',load);$('scanBtn').addEventListener('click',async()=>{try{const r=await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/scan`,{method:'POST'});notice(r.public_test_allowed?'Integrity/rating scan passed.':`Scan completed with ${(r.blockers||[]).length} blocker(s).`,!r.public_test_allowed)}catch(e){notice(e.message,true)}});$('buildBtn').addEventListener('click',async()=>{try{const r=await api(`/api/game-forge/games/${encodeURIComponent(GAME_ID)}/build`,{method:'POST'});notice(`Built ${r.runtime}. Opening private playtest…`);window.open(r.private_playtest_url,'_blank','noopener')}catch(e){notice(e.message,true)}});load();
</script></body></html>"""
    page = page.replace("__BRAND__", safe_brand).replace("__GAME_ID__", safe_game_id).replace("__GAME_JSON__", game_json)
    return HTMLResponse(page)


__all__ = ["router"]
