from __future__ import annotations

import os
import shlex
import shutil
import subprocess
from pathlib import Path

from .models import ProjectManifest
from .project import ProjectWorkspace


def ensure_score_guide(workspace: ProjectWorkspace, manifest: ProjectManifest) -> Path | None:
    """Return a time/harmony guide for cover-style neural rendering.

    Priority:
    1) project guide_file
    2) project guide_command
    3) MIDI/MusicXML -> MIDI -> FluidSynth when available
    4) no guide (text-to-music/original mode can continue)
    """
    target = workspace.work_dir / "score_guide.wav"

    if manifest.guide_file:
        source = workspace.resolve_asset(manifest.guide_file)
        if source and source.exists():
            if source.resolve() != target.resolve():
                shutil.copy2(source, target)
            workspace.log(f"Guide copied from {source}", "guide.log")
            return target

    if manifest.guide_command:
        env = os.environ.copy()
        env["AURA_GUIDE"] = str(target)
        env["AURA_PROJECT"] = str(workspace.root)
        env["AURA_BPM"] = str(manifest.tempo_bpm or "")
        env["AURA_KEY"] = manifest.key or ""
        cmd = shlex.split(manifest.guide_command)
        subprocess.run(cmd, cwd=workspace.root, env=env, check=True)
        if not target.exists():
            raise RuntimeError(f"guide_command did not produce {target}")
        workspace.log(f"Guide generated by command: {manifest.guide_command}", "guide.log")
        return target

    score_value = manifest.musicxml_file or manifest.midi_file
    score = workspace.resolve_asset(score_value)
    if score and score.exists():
        midi = workspace.work_dir / "score.mid"
        if score.suffix.lower() in {".mid", ".midi"}:
            shutil.copy2(score, midi)
        else:
            from music21 import converter
            parsed = converter.parse(str(score))
            parsed.write("midi", fp=str(midi))

        fluidsynth = shutil.which("fluidsynth")
        soundfont = _find_soundfont()
        if fluidsynth and soundfont:
            subprocess.run([
                fluidsynth, "-ni", str(soundfont), str(midi),
                "-F", str(target), "-r", "48000",
            ], check=True)
            workspace.log(f"Guide rendered from score with {soundfont}", "guide.log")
            return target
        workspace.log("MIDI guide exists but FluidSynth/SoundFont is unavailable.", "guide.log")

    return None


def _find_soundfont() -> Path | None:
    candidates = [
        os.getenv("AURA_SOUNDFONT", ""),
        "/usr/share/sounds/sf2/FluidR3_GM.sf2",
        "/usr/share/sounds/sf2/TimGM6mb.sf2",
        "/usr/share/soundfonts/FluidR3_GM.sf2",
    ]
    for candidate in candidates:
        if candidate and Path(candidate).exists():
            return Path(candidate)
    return None
