from __future__ import annotations

from html import escape
from urllib.parse import quote

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse, RedirectResponse

from .branding import PRODUCT_FULL_NAME
from .tenant_storage import project_path

router = APIRouter()


@router.get("/song-editor/{project_name}/alignment", response_class=HTMLResponse, include_in_schema=False)
def lyric_alignment_portal(project_name: str, request: Request):
    member = getattr(request.state, "member", None)
    if member is None:
        return RedirectResponse(
            f"/signin?next=/song-editor/{quote(project_name, safe='')}/alignment",
            status_code=303,
        )
    try:
        project_path(project_name, must_exist=True)
    except Exception:
        return HTMLResponse("<h1>Project not found</h1>", status_code=404)
    encoded = quote(project_name, safe="")
    brand = escape(PRODUCT_FULL_NAME)
    html = r"""<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><meta name='robots' content='noindex,nofollow'><title>Lyric Alignment — __BRAND__</title><style>
:root{--bg:#03040a;--panel:#0d1120;--line:#ffffff20;--gold:#e9c86f;--violet:#9a6dff;--green:#72e0a8;--red:#ff8fa5;--muted:#bac1d4;--text:#fff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 9% 0,#42186d66,transparent 28%),radial-gradient(circle at 93% 2%,#173d7566,transparent 25%),#03040a;color:#fff;font-family:Inter,ui-sans-serif,system-ui,sans-serif}.wrap{width:min(1300px,calc(100% - 28px));margin:auto}.nav{position:sticky;top:0;background:#05060bef;border-bottom:1px solid var(--line);backdrop-filter:blur(16px);z-index:10}.navin{min-height:70px;display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.brand{font-weight:950}.brand small{display:block;color:var(--gold);font-size:.65rem;text-transform:uppercase;letter-spacing:.08em}a{color:inherit;text-decoration:none}.btn,button{border:1px solid var(--line);background:#ffffff08;color:#fff;border-radius:11px;padding:9px 12px;font:inherit;font-weight:850;cursor:pointer}.primary{border:0!important;background:linear-gradient(115deg,var(--gold),var(--violet))!important;color:#160d1d!important}.hero{padding:38px 0 18px}.eyebrow{font-size:.7rem;letter-spacing:.16em;text-transform:uppercase;color:var(--gold);font-weight:950}h1{font-size:clamp(2.4rem,6vw,4.8rem);line-height:.94;letter-spacing:-.05em;margin:.14em 0 .2em}.lead,.muted{color:var(--muted);line-height:1.6}.card{border:1px solid var(--line);border-radius:18px;background:linear-gradient(145deg,#111628ed,#090c18f2);padding:16px;margin:10px 0}.line{display:grid;grid-template-columns:minmax(260px,1fr) 140px 140px auto;gap:9px;align-items:center;border-bottom:1px solid var(--line);padding:11px 0}.line:last-child{border-bottom:0}.field{width:100%;border:1px solid var(--line);background:#060912;color:#fff;border-radius:10px;padding:9px;font:inherit}.pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:4px 8px;font-size:.7rem;margin:2px}.pill.good{color:var(--green);border-color:#72e0a855}.pill.warn{color:#ffd285;border-color:#ffd28555}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.metric{border:1px solid var(--line);border-radius:13px;padding:11px;background:#ffffff05}.metric b{font-size:1.35rem;display:block}.notice{display:none;border:1px solid var(--line);border-radius:12px;padding:10px;margin:10px 0}.notice.show{display:block}.notice.bad{border-color:#ff8fa555;color:#ffd8df}@media(max-width:800px){.line{grid-template-columns:1fr 1fr}.line .text{grid-column:1/-1}.summary{grid-template-columns:1fr 1fr}}@media(max-width:500px){.line,.summary{grid-template-columns:1fr}}
</style></head><body><nav class='nav'><div class='wrap navin'><a class='brand' href='/song-editor/__PROJECT__'>__BRAND__<small>Lyric timing & phrase verification</small></a><div><a class='btn' href='/song-editor/__PROJECT__/audition'>Audition edits</a> <a class='btn' href='/song-editor/__PROJECT__'>Song DNA</a></div></div></nav><main class='wrap'><section class='hero'><div class='eyebrow'>Surgical vocal editing requires timing confidence</div><h1>Align the words to the real performance.</h1><p class='lead'>Aura may estimate line timing to speed setup, but an estimate is deliberately not enough to replace one vocal phrase. Verify the start/end manually or run a configured forced-aligner. Only verified/high-confidence lines become eligible for surgical lyric regeneration.</p><div id='notice' class='notice'></div></section><div class='card'><div class='summary' id='summary'></div><div style='display:flex;gap:8px;flex-wrap:wrap;margin-top:12px'><button class='primary' onclick='estimate()'>Create provisional timing</button><button onclick='forced()'>Run configured forced aligner</button><button onclick='load()'>Refresh</button></div></div><div class='card'><div class='eyebrow'>Lyric lines</div><div id='lines'><p class='muted'>Loading…</p></div></div></main><script>
const PROJECT='__PROJECT__', API=`/projects/${PROJECT}/lyric-alignment`,$=id=>document.getElementById(id);function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function notice(m,b=false){const n=$('notice');n.textContent=m;n.className='notice show'+(b?' bad':'');clearTimeout(window._n);window._n=setTimeout(()=>n.className='notice',6500)}async function req(url,opt={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let b={};try{b=await r.json()}catch(e){}if(!r.ok)throw new Error(b.detail||`Request failed (${r.status})`);return b}
async function load(){try{const d=await req(API);const s=d.summary;$('summary').innerHTML=`<div class="metric"><small class="muted">Lines</small><b>${s.total}</b></div><div class="metric"><small class="muted">Surgical ready</small><b>${s.surgical_ready}</b></div><div class="metric"><small class="muted">Estimated</small><b>${s.estimated}</b></div><div class="metric"><small class="muted">Verified</small><b>${s.verified}</b></div>`;$('lines').innerHTML=d.lines.length?d.lines.map(x=>`<div class="line"><div class="text"><b>${esc(x.text)}</b><div><span class="pill ${x.surgical_ready?'good':x.alignment_state==='estimated'?'warn':''}">${esc(x.alignment_state)}</span><span class="pill">confidence ${Math.round((x.alignment_confidence||0)*100)}%</span></div></div><input id="s_${x.id}" class="field" type="number" step="0.01" min="0" value="${x.start_seconds??''}" placeholder="Start sec"><input id="e_${x.id}" class="field" type="number" step="0.01" min="0" value="${x.end_seconds??''}" placeholder="End sec"><button class="primary" onclick="verify('${x.id}')">Verify</button></div>`).join(''):'<p class="muted">No lyrics in this project.</p>'}catch(e){notice(e.message,true)}}async function estimate(){try{await req(`${API}/estimate`,{method:'POST',body:JSON.stringify({start_seconds:0})});await load();notice('Provisional timing created. Verify lines before surgical edits.')}catch(e){notice(e.message,true)}}async function verify(id){const s=parseFloat($(`s_${id}`).value),e=parseFloat($(`e_${id}`).value);if(!Number.isFinite(s)||!Number.isFinite(e))return notice('Enter valid start and end times.',true);try{await req(`${API}/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({start_seconds:s,end_seconds:e})});await load();notice('Line timing verified.')}catch(err){notice(err.message,true)}}async function forced(){notice('Running configured forced aligner…');try{await req(`${API}/forced`,{method:'POST'});await load();notice('Forced alignment completed. Check confidence before editing.')}catch(e){notice(e.message,true)}}load();
</script></body></html>"""
    return HTMLResponse(html.replace("__PROJECT__", encoded).replace("__BRAND__", brand))
