from __future__ import annotations

import json
from html import escape

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse, RedirectResponse

from .accounts import AccountStore
from .branding import PRODUCT_FULL_NAME
from .plans import get_plan

router = APIRouter()
store = AccountStore()


@router.get("/production-suite", response_class=HTMLResponse)
def production_suite(request: Request):
    user = store.resolve_session(request.cookies.get("lss_session"))
    if not user:
        return RedirectResponse("/signin", status_code=303)
    if user.get("status") != "active":
        return RedirectResponse("/dashboard", status_code=303)
    plan = get_plan(user.get("plan_id") or "free")
    features = json.dumps(sorted(plan.features))
    name = escape(user.get("display_name") or "Member")
    return HTMLResponse(r"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Production Suite — __PRODUCT__</title><style>
:root{--bg:#08060d;--panel:#15101d;--panel2:#20142b;--line:#3b2b47;--gold:#e7bd63;--text:#fff;--muted:#c9bed1;--good:#7edda4;--bad:#ff91a4}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#28133d,#08060d 45%);color:var(--text);font-family:Inter,system-ui,sans-serif}button,input,select,textarea{font:inherit}.wrap{max-width:1450px;margin:auto;padding:20px}.top{display:flex;justify-content:space-between;gap:14px;align-items:center;flex-wrap:wrap}.brand b{color:var(--gold);font-size:.75rem;letter-spacing:.13em;text-transform:uppercase}.brand h1{margin:4px 0}.btn,button{border:1px solid var(--line);background:#24172e;color:#fff;padding:10px 13px;border-radius:10px;font-weight:800;cursor:pointer;text-decoration:none}.primary{background:linear-gradient(135deg,#f2d17a,#bd8d39);color:#180f1d;border:0}.layout{display:grid;grid-template-columns:280px 1fr;gap:16px;margin-top:18px}.panel{background:#120d19;border:1px solid var(--line);border-radius:18px;padding:16px}.side .field{margin-bottom:12px}.field label{display:block;font-size:.84rem;font-weight:800;margin-bottom:5px}input,select,textarea{width:100%;background:#09070d;color:#fff;border:1px solid var(--line);border-radius:9px;padding:10px}textarea{min-height:90px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.card{background:#18101f;border:1px solid var(--line);border-radius:14px;padding:14px}.card h3{margin:0 0 7px}.muted{color:var(--muted)}.status{background:#08060d;border:1px solid #33263c;border-radius:10px;padding:11px;min-height:48px;white-space:pre-wrap;overflow:auto}.asset{padding:8px;border:1px solid transparent;border-radius:8px;margin:4px 0;cursor:pointer}.asset:hover,.asset.selected{background:#291a34;border-color:#5c3c6e}.switches{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;max-height:380px;overflow:auto}.switch{border:1px solid #382944;border-radius:9px;padding:8px}.switch.locked{opacity:.45}.row{display:flex;gap:8px;flex-wrap:wrap}.row>*{flex:1}.row button{flex:0 0 auto}.gold{color:var(--gold)}.ok{color:var(--good)}.err{color:var(--bad)}.pill{display:inline-block;border:1px solid var(--line);border-radius:99px;padding:6px 10px;color:var(--gold);font-weight:900}@media(max-width:900px){.layout,.grid,.switches{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><div class="top"><div class="brand"><b>Elevate Souls Productions Presents</b><h1>Aura Production Suite</h1><span class="muted">Build around vocals or instruments · FX · Aura Tune · AutoMix · Split · Master</span></div><div><span class="pill">__PLAN__</span> <a class="btn" href="/studio">← Studio</a></div></div>
<div class="layout"><aside class="panel side"><h3>Session source</h3><p class="muted">Hello __NAME__. Choose a private project and an uploaded/created audio asset.</p><div class="field"><label>Project</label><select id="project" onchange="loadAssets()"></select></div><div id="assets"></div><div id="sourceStatus" class="status">Choose an audio asset.</div></aside>
<main><div class="grid">
<section class="card" style="grid-column:span 2"><h3>🎼 Build Around Upload</h3><p class="muted">Keep the uploaded vocal or instrument as the anchor while Aura creates the missing band around it.</p><div class="row"><div class="field"><label>Source role</label><select id="sourceRole"><option>vocals</option><option>guitar</option><option>bass</option><option>drums</option><option>piano</option><option>keyboard</option><option>synth</option><option>strings</option><option>brass</option><option>woodwinds</option><option>percussion</option><option>other</option></select></div><div class="field"><label>Genre</label><input id="genre" value="pop"></div><div class="field"><label>Mood</label><input id="mood" value="uplifting"></div></div><div class="row"><label><input id="leadVocal" type="checkbox" checked style="width:auto"> Add lead vocal when source is instrumental</label><label><input id="backingVocal" type="checkbox" checked style="width:auto"> Add backing harmonies</label></div><div class="field"><label>Lyrics (optional)</label><textarea id="buildLyrics" placeholder="Leave blank and Aura can draft original lyrics when a new lead vocal is requested."></textarea></div><div class="field"><label>Extra direction</label><input id="buildDirection" placeholder="Big live chorus, intimate verse, modern radio production..."></div><h4>Instrument switches</h4><div id="instrumentSwitches" class="switches"></div><br><button class="primary" onclick="buildAround()">Create Full Track Around Source</button><div id="buildStatus" class="status"></div></section>
<section class="card"><h3>🎚 FX Presets</h3><p class="muted">Vocal chains and pedal-style guitar/bass/drum/creative presets.</p><div class="field"><label>Preset</label><select id="fxPreset"></select></div><button onclick="applyFx()">Apply FX</button><div id="fxStatus" class="status"></div></section>
<section class="card"><h3>🎤 Aura Tune</h3><div class="row"><div class="field"><label>Mode</label><select id="tuneMode"><option>natural</option><option>classic</option><option>hard</option><option>robot</option><option>custom</option></select></div><div class="field"><label>Key</label><input id="tuneKey" placeholder="Auto"></div></div><div class="row"><div class="field"><label>Scale</label><select id="tuneScale"><option>major</option><option>minor</option><option>harmonic_minor</option><option>pentatonic_major</option><option>pentatonic_minor</option><option>chromatic</option></select></div><div class="field"><label>Strength 0–1</label><input id="tuneStrength" type="number" min="0" max="1" step=".05" value=".75"></div></div><button onclick="autoKey()">Detect Key</button> <button class="primary" onclick="tune()">Tune Vocal</button><div id="tuneStatus" class="status"></div></section>
<section class="card"><h3>🥁 AutoMix</h3><p class="muted">Genre-aware volume and pan suggestions remain editable in the multitrack session.</p><div class="field"><label>Genre</label><input id="mixGenre" value="pop"></div><div class="field"><label>Intensity</label><input id="mixIntensity" type="number" min="0" max="1" step=".05" value=".8"></div><button onclick="automix()">AutoMix Session</button><div id="mixStatus" class="status"></div></section>
<section class="card"><h3>🧬 Music Splitter</h3><div class="field"><label>Split depth</label><select id="splitMode"><option value="two_stems">2 stems — vocal / instrumental</option><option value="four_stems">4 stems — vocal / drums / bass / other</option><option value="six_stems">6 stems — adds guitar & piano</option><option value="detailed">Detailed — configured advanced separator</option></select></div><button onclick="splitAudio()">Split Source</button><div id="splitStatus" class="status"></div></section>
<section class="card" style="grid-column:span 2"><h3>💿 Aura Master</h3><div class="row"><div class="field"><label>Character</label><select id="masterPreset"></select></div><div class="field"><label>Intensity</label><input id="masterIntensity" type="number" min="0" max="1.5" step=".05" value="1"></div><div class="field"><label>Target LUFS (Pro)</label><input id="masterLufs" type="number" placeholder="Auto"></div></div><div class="row"><div class="field"><label>Low EQ dB (Pro)</label><input id="masterLow" type="number" step=".1" value="0"></div><div class="field"><label>Mid EQ dB (Pro)</label><input id="masterMid" type="number" step=".1" value="0"></div><div class="field"><label>High EQ dB (Pro)</label><input id="masterHigh" type="number" step=".1" value="0"></div><div class="field"><label>Stereo width (Pro)</label><input id="masterWidth" type="number" step=".05" placeholder="Preset"></div></div><button class="primary" onclick="masterAudio()">Master Source</button><div id="masterStatus" class="status"></div></section>
</div></main></div></div>
<script>
const FEATURES=new Set(__FEATURES__);let selectedAsset=null,projects=[];
async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options});let b;try{b=await r.json()}catch{b=await r.text()}if(!r.ok)throw new Error(typeof b==='string'?b:(b.detail||JSON.stringify(b)));return b}
function status(id,v,ok=true){const e=document.getElementById(id);e.textContent=typeof v==='string'?v:JSON.stringify(v,null,2);e.className='status '+(ok?'ok':'err')}
function project(){return document.getElementById('project').value}function audio(){if(!selectedAsset)throw new Error('Choose an audio asset first');return selectedAsset}
async function loadProjects(){projects=await api('/projects');const s=document.getElementById('project');s.innerHTML='';for(const p of projects){const o=document.createElement('option');o.value=p.name;o.textContent=p.name;s.appendChild(o)}if(projects.length)loadAssets()}
async function loadAssets(){selectedAsset=null;const root=document.getElementById('assets');root.innerHTML='';if(!project())return;const items=await api('/projects/'+encodeURIComponent(project())+'/assets');for(const a of items.filter(x=>x.kind==='audio')){const d=document.createElement('div');d.className='asset';d.textContent=a.name;d.onclick=()=>{document.querySelectorAll('.asset').forEach(x=>x.classList.remove('selected'));d.classList.add('selected');selectedAsset=a;status('sourceStatus',{name:a.name,id:a.id,analysis:a.analysis})};root.appendChild(d)}}
async function loadCatalogs(){const inst=await api('/production/instrument-catalog');const root=document.getElementById('instrumentSwitches');root.innerHTML='';for(const [family,items] of Object.entries(inst.families)){for(const item of items){const d=document.createElement('label');d.className='switch'+(item.locked?' locked':'');const cb=document.createElement('input');cb.type='checkbox';cb.style.width='auto';cb.dataset.family=family;cb.dataset.type=item.id;cb.disabled=item.locked;d.append(cb,document.createTextNode(' '+item.label+(item.locked?' · Pro':'')));root.appendChild(d)}}const fx=await api('/production/fx-presets');const fs=document.getElementById('fxPreset');for(const p of fx.presets){const o=document.createElement('option');o.value=p.id;o.disabled=p.locked;o.textContent=p.category+' · '+p.name+(p.locked?' · locked':'');fs.appendChild(o)}const ms=await api('/production/mastering-presets');const m=document.getElementById('masterPreset');for(const p of ms.presets){const o=document.createElement('option');o.value=p.id;o.disabled=p.locked;o.textContent=p.id+(p.locked?' · locked':'');m.appendChild(o)}}
function switches(){return [...document.querySelectorAll('#instrumentSwitches input:checked')].map(x=>({family:x.dataset.family,type_id:x.dataset.type,enabled:true,prominence:.65,custom_direction:''}))}
async function buildAround(){try{const a=audio();status('buildStatus','Aura is building the missing band around '+a.name+'...');const body={asset_id:a.id,source_role:document.getElementById('sourceRole').value,genre:document.getElementById('genre').value,mood:document.getElementById('mood').value,instrument_switches:switches(),include_lead_vocal:document.getElementById('leadVocal').checked,include_backing_vocals:document.getElementById('backingVocal').checked,lyrics:document.getElementById('buildLyrics').value,generate_lyrics_if_missing:true,extra_direction:document.getElementById('buildDirection').value};status('buildStatus',await api('/production/projects/'+encodeURIComponent(project())+'/build-around',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}))}catch(e){status('buildStatus',e.message,false)}}
async function applyFx(){try{const a=audio();status('fxStatus',await api('/production/projects/'+encodeURIComponent(project())+'/fx',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({asset_id:a.id,preset_id:document.getElementById('fxPreset').value})}))}catch(e){status('fxStatus',e.message,false)}}
async function autoKey(){try{const a=audio();const r=await api('/production/projects/'+encodeURIComponent(project())+'/autokey/'+encodeURIComponent(a.id));document.getElementById('tuneKey').value=r.key;document.getElementById('tuneScale').value=r.scale;status('tuneStatus',r)}catch(e){status('tuneStatus',e.message,false)}}
async function tune(){try{const a=audio();const settings={mode:document.getElementById('tuneMode').value,key:document.getElementById('tuneKey').value||null,scale:document.getElementById('tuneScale').value,strength:Number(document.getElementById('tuneStrength').value),retune_speed_ms:80,humanize:.65,formant_preserve:true,custom_pitch_classes:[]};status('tuneStatus',await api('/production/projects/'+encodeURIComponent(project())+'/autotune',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({asset_id:a.id,settings})}))}catch(e){status('tuneStatus',e.message,false)}}
async function automix(){try{await api('/projects/'+encodeURIComponent(project())+'/session');status('mixStatus',await api('/production/projects/'+encodeURIComponent(project())+'/automix',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({genre:document.getElementById('mixGenre').value,intensity:Number(document.getElementById('mixIntensity').value)})}))}catch(e){status('mixStatus',e.message,false)}}
async function splitAudio(){try{const a=audio();status('splitStatus','Separating...');status('splitStatus',await api('/production/projects/'+encodeURIComponent(project())+'/split',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({asset_id:a.id,mode:document.getElementById('splitMode').value})}))}catch(e){status('splitStatus',e.message,false)}}
async function masterAudio(){try{const a=audio(),w=document.getElementById('masterWidth').value,l=document.getElementById('masterLufs').value;const body={asset_id:a.id,preset:document.getElementById('masterPreset').value,intensity:Number(document.getElementById('masterIntensity').value),low_db:Number(document.getElementById('masterLow').value),mid_db:Number(document.getElementById('masterMid').value),high_db:Number(document.getElementById('masterHigh').value),stereo_width:w?Number(w):null,target_lufs:l?Number(l):null};status('masterStatus','Mastering...');status('masterStatus',await api('/production/projects/'+encodeURIComponent(project())+'/master',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}))}catch(e){status('masterStatus',e.message,false)}}
loadProjects().catch(e=>status('sourceStatus',e.message,false));loadCatalogs().catch(e=>status('sourceStatus',e.message,false));
</script></body></html>""".replace("__PRODUCT__", escape(PRODUCT_FULL_NAME)).replace("__PLAN__", escape(plan.name)).replace("__NAME__", name).replace("__FEATURES__", features))
