from __future__ import annotations

import json
from html import escape

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse, RedirectResponse

from .accounts import AccountStore
from .branding import PRODUCT_FULL_NAME
from .plans import get_plan

router = APIRouter()
store = AccountStore()


@router.get("/production-suite", response_class=HTMLResponse)
def production_suite(request: Request):
    user = store.resolve_session(request.cookies.get("lss_session"))
    if not user:
        return RedirectResponse("/signin", status_code=303)
    if user.get("status") != "active":
        return RedirectResponse("/dashboard", status_code=303)
    plan = get_plan(user.get("plan_id") or "free")
    features = json.dumps(sorted(plan.features))
    name = escape(user.get("display_name") or "Member")
    page = r"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Production Suite — __PRODUCT__</title><style>
:root{--bg:#08060d;--panel:#15101d;--line:#3b2b47;--gold:#e7bd63;--text:#fff;--muted:#c9bed1;--good:#7edda4;--bad:#ff91a4;--blue:#8ab9ff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#28133d,#08060d 45%);color:var(--text);font-family:Inter,system-ui,sans-serif}button,input,select,textarea{font:inherit}.wrap{max-width:1520px;margin:auto;padding:20px}.top{display:flex;justify-content:space-between;gap:14px;align-items:center;flex-wrap:wrap}.brand b{color:var(--gold);font-size:.75rem;letter-spacing:.13em;text-transform:uppercase}.brand h1{margin:4px 0}.btn,button{border:1px solid var(--line);background:#24172e;color:#fff;padding:10px 13px;border-radius:10px;font-weight:800;cursor:pointer;text-decoration:none}.primary{background:linear-gradient(135deg,#f2d17a,#bd8d39);color:#180f1d;border:0}.layout{display:grid;grid-template-columns:300px 1fr;gap:16px;margin-top:18px}.panel{background:#120d19;border:1px solid var(--line);border-radius:18px;padding:16px}.field{margin:9px 0}.field label{display:block;font-size:.84rem;font-weight:800;margin-bottom:5px}input,select,textarea{width:100%;background:#09070d;color:#fff;border:1px solid var(--line);border-radius:9px;padding:10px}textarea{min-height:85px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.span2{grid-column:span 2}.span3{grid-column:span 3}.card{background:#18101f;border:1px solid var(--line);border-radius:14px;padding:14px}.card h3{margin:0 0 7px}.muted{color:var(--muted)}.status{background:#08060d;border:1px solid #33263c;border-radius:10px;padding:11px;min-height:45px;white-space:pre-wrap;overflow:auto;max-height:300px}.asset{padding:8px;border:1px solid transparent;border-radius:8px;margin:4px 0;cursor:pointer}.asset:hover,.asset.selected{background:#291a34;border-color:#5c3c6e}.switches{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;max-height:360px;overflow:auto}.switch{border:1px solid #382944;border-radius:9px;padding:8px}.switch.locked{opacity:.45}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:end}.row>*{flex:1}.row button,.row .btn{flex:0 0 auto}.ok{color:var(--good)}.err{color:var(--bad)}.pill{display:inline-block;border:1px solid var(--line);border-radius:99px;padding:6px 10px;color:var(--gold);font-weight:900}.pro{color:var(--gold);font-size:.76rem;font-weight:900}.notegrid{display:grid;grid-template-columns:repeat(6,1fr);gap:5px}.notegrid label{border:1px solid var(--line);border-radius:7px;padding:6px;text-align:center}.output{border-top:1px solid #ffffff12;padding:10px 0}.output audio{width:100%;margin-top:7px}.tiny{font-size:.78rem}.disabled{opacity:.45;pointer-events:none}.rackitem{padding:7px;border:1px solid var(--line);border-radius:8px;margin:5px 0}.queuepulse{color:var(--blue);font-weight:800}@media(max-width:980px){.layout,.grid{grid-template-columns:1fr}.span2,.span3{grid-column:span 1}.switches{grid-template-columns:1fr}}
</style></head><body><div class="wrap">
<div class="top"><div class="brand"><b>Elevate Souls Productions Presents</b><h1>Aura Production Suite</h1><span class="muted">Build Around · Instrument Switchboard · FX · Aura Tune · AutoMix · Split · Master · Plugin Rack</span></div><div><span class="pill">__PLAN__</span> <a class="btn" href="/studio">← Studio</a></div></div>
<div class="layout"><aside class="panel"><h3>Project + source</h3><p class="muted">Hello __NAME__. Select a private project and audio source.</p><div class="field"><label>Project</label><select id="project" onchange="projectChanged()"></select></div><div id="assets"></div><div id="sourceStatus" class="status">Choose an audio asset.</div><h3>Outputs</h3><button onclick="loadOutputs()">Refresh outputs</button><div id="outputs"></div></aside>
<main><div class="grid">
<section id="buildCard" class="card span2"><h3>🎼 Build Around Upload</h3><p class="muted">Upload an isolated vocal and Aura builds the band. Upload an instrument and Aura builds the missing instruments plus optional lead/backing vocals.</p><div class="row"><div class="field"><label>Source role</label><select id="sourceRole"><option>vocals</option><option>guitar</option><option>bass</option><option>drums</option><option>piano</option><option>keyboard</option><option>synth</option><option>strings</option><option>brass</option><option>woodwinds</option><option>percussion</option><option>other</option></select></div><button onclick="detectSource()">Auto-detect</button><div class="field"><label>Genre</label><input id="genre" value="pop"></div><div class="field"><label>Mood</label><input id="mood" value="uplifting"></div><div class="field"><label>Output mode</label><select id="buildMode"><option value="complete_mix">Complete mix — Base+</option><option id="multitrackOption" value="multitrack">Editable multitrack — Pro</option></select></div></div><div class="row"><label><input id="leadVocal" type="checkbox" checked style="width:auto"> Add lead vocal when source is instrumental</label><label><input id="backingVocal" type="checkbox" checked style="width:auto"> Add backing harmonies</label><label><input id="autoMixBuild" type="checkbox" checked style="width:auto"> AutoMix generated multitrack</label></div><div class="field"><label>Lyrics (optional)</label><textarea id="buildLyrics" placeholder="Leave blank and Aura can draft original lyrics when generating a new lead vocal."></textarea></div><div class="field"><label>Extra production direction</label><input id="buildDirection" placeholder="Huge live chorus, intimate verse, real room drums, restrained guitar fills..."></div><h4>Instrument / performance switches</h4><p class="muted tiny">Leave all switches off for Aura's genre defaults. Pro-only performance types are locked on lower tiers.</p><div id="instrumentSwitches" class="switches"></div><br><button class="primary" onclick="buildAround()">Create Around Source</button><div id="buildStatus" class="status"></div></section>
<section class="card"><h3>🎚 FX Presets</h3><p class="muted">One-click vocal, guitar, bass, drums and creative pedal chains.</p><div class="field"><label>Preset</label><select id="fxPreset"></select></div><button onclick="applyFx()">Apply FX</button><div id="fxStatus" class="status"></div></section>
<section id="aiFxCard" class="card"><h3>✨ Aura AI FX Designer <span class="pro">PRO</span></h3><p class="muted">Describe a sound and Aura builds a validated safe insert chain.</p><div class="field"><label>Category</label><select id="fxCategory"><option>vocal</option><option>guitar</option><option>bass</option><option>drums</option><option>creative</option></select></div><div class="field"><label>Describe the sound</label><textarea id="fxDescription" placeholder="Warm intimate vocal, subtle double, short room, controlled sibilance..."></textarea></div><button class="primary" onclick="designFx()">Design + Render</button><div id="aiFxStatus" class="status"></div></section>
<section class="card span2"><h3>🎤 Aura Tune</h3><div class="row"><div class="field"><label>Mode</label><select id="tuneMode"><option value="natural">Natural — Free</option><option id="tuneClassic" value="classic">Classic — Base</option><option id="tuneHard" value="hard">Hard — Base</option><option id="tuneRobot" value="robot">Robot — Pro</option><option id="tuneCustom" value="custom">Custom scale — Pro</option></select></div><div class="field"><label>Key</label><input id="tuneKey" placeholder="Auto"></div><div class="field"><label>Scale</label><select id="tuneScale"><option>major</option><option>minor</option><option>harmonic_minor</option><option>pentatonic_major</option><option>pentatonic_minor</option><option>chromatic</option></select></div><div class="field"><label>Strength</label><input id="tuneStrength" type="number" min="0" max="1" step=".05" value=".75"></div></div><div class="row"><div class="field"><label>Retune speed ms</label><input id="retuneMs" type="number" min="0" max="500" value="80"></div><div class="field"><label>Humanize</label><input id="humanize" type="number" min="0" max="1" step=".05" value=".65"></div><div class="field"><label>Minimum note ms</label><input id="minNoteMs" type="number" min="20" max="1000" value="90"></div></div><div><span class="pro">PRO CUSTOM SCALE NOTES</span><div id="customNotes" class="notegrid"></div></div><br><button onclick="autoKey()">Detect Key</button> <button class="primary" onclick="tune()">Tune Vocal</button><div id="tuneStatus" class="status"></div></section>
<section class="card"><h3>🥁 AutoMix</h3><p class="muted">Genre-aware editable track gain and pan suggestions.</p><div class="field"><label>Genre</label><input id="mixGenre" value="pop"></div><div class="field"><label>Intensity</label><input id="mixIntensity" type="number" min="0" max="1" step=".05" value=".8"></div><button onclick="automix()">AutoMix Session</button><div id="mixStatus" class="status"></div></section>
<section class="card"><h3>🧬 Music Splitter</h3><div class="field"><label>Split depth</label><select id="splitMode"><option value="two_stems">2 stems — vocal / instrumental</option><option value="four_stems">4 stems — vocal / drums / bass / other</option><option id="sixStemOption" value="six_stems">6 stems — Pro</option><option id="detailedStemOption" value="detailed">Detailed — Pro advanced separator</option></select></div><button onclick="splitAudio()">Split Source</button><div id="splitStatus" class="status"></div></section>
<section class="card span2"><h3>💿 Aura Master</h3><div class="row"><div class="field"><label>Character</label><select id="masterPreset"></select></div><div class="field"><label>Intensity</label><input id="masterIntensity" type="number" min="0" max="1.5" step=".05" value="1"></div><div class="field"><label>Reference track <span class="pro">PRO</span></label><select id="masterReference"><option value="">None</option></select></div><div class="field"><label>Target LUFS <span class="pro">PRO</span></label><input id="masterLufs" type="number" placeholder="Auto"></div></div><div class="row"><div class="field"><label>Low EQ dB <span class="pro">PRO</span></label><input id="masterLow" type="number" step=".1" value="0"></div><div class="field"><label>Mid EQ dB <span class="pro">PRO</span></label><input id="masterMid" type="number" step=".1" value="0"></div><div class="field"><label>High EQ dB <span class="pro">PRO</span></label><input id="masterHigh" type="number" step=".1" value="0"></div><div class="field"><label>Stereo width <span class="pro">PRO</span></label><input id="masterWidth" type="number" step=".05" placeholder="Preset"></div></div><button class="primary" onclick="masterAudio()">Master Source</button><div id="masterStatus" class="status"></div></section>
<section id="albumCard" class="card"><h3>💽 Album / EP Master <span class="pro">PRO</span></h3><p class="muted">Apply one consistent mastering profile across multiple selected tracks.</p><div id="albumAssets"></div><div class="field"><label>Preset</label><select id="albumPreset"></select></div><button onclick="albumMaster()">Master Selected Set</button><div id="albumStatus" class="status"></div></section>
<section id="pluginCard" class="card span2"><h3>🔌 Trusted Plugin Rack <span class="pro">PRO</span></h3><p class="muted">Only ESP-owner-approved installed plugins can run. Members never supply executable paths.</p><div class="row"><div class="field"><label>Approved plugin</label><select id="pluginSelect"></select></div><div class="field"><label>Parameter JSON</label><input id="pluginParams" placeholder='{"mix":0.25}'></div><button onclick="addPlugin()">Add to Rack</button></div><div id="rackList"></div><button class="primary" onclick="renderPluginRack()">Render Rack</button><div id="pluginStatus" class="status"></div></section>
<section class="card span3"><h3>🎧 Project Outputs</h3><p class="muted">Audition and download finished masters and eligible stems without leaving the Production Suite.</p><button onclick="loadOutputs()">Refresh Outputs</button><div id="outputMain"></div></section>
</div></main></div></div>
<script>
const FEATURES=new Set(__FEATURES__);let selectedAsset=null,projects=[],assetCache=[],pluginRack=[],pluginCatalog=[];const NOTES=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options});let b;try{b=await r.json()}catch{b=await r.text()}if(!r.ok)throw new Error(typeof b==='string'?b:(b.detail||JSON.stringify(b)));return b}
function status(id,v,ok=true){const e=document.getElementById(id);e.textContent=typeof v==='string'?v:JSON.stringify(v,null,2);e.className='status '+(ok?'ok':'err')}
function project(){return document.getElementById('project').value}function audio(){if(!selectedAsset)throw new Error('Choose an audio asset first');return selectedAsset}
function gateUI(){const canBuild=FEATURES.has('build_around_upload'),proMulti=FEATURES.has('multitrack_daw'),stdTune=FEATURES.has('standard_autotune'),advTune=FEATURES.has('advanced_autotune'),proSplit=FEATURES.has('stem_splitter');if(!canBuild)document.getElementById('buildCard').classList.add('disabled');document.getElementById('multitrackOption').disabled=!proMulti;document.getElementById('tuneClassic').disabled=!stdTune;document.getElementById('tuneHard').disabled=!stdTune;document.getElementById('tuneRobot').disabled=!advTune;document.getElementById('tuneCustom').disabled=!advTune;document.querySelectorAll('#customNotes input').forEach(x=>x.disabled=!advTune);document.getElementById('sixStemOption').disabled=!proSplit;document.getElementById('detailedStemOption').disabled=!proSplit;if(!FEATURES.has('ai_fx_designer'))document.getElementById('aiFxCard').classList.add('disabled');if(!FEATURES.has('plugin_rack'))document.getElementById('pluginCard').classList.add('disabled');if(!FEATURES.has('album_mastering'))document.getElementById('albumCard').classList.add('disabled');const advancedMaster=FEATURES.has('advanced_mastering');['masterLufs','masterLow','masterMid','masterHigh','masterWidth'].forEach(id=>document.getElementById(id).disabled=!advancedMaster);document.getElementById('masterReference').disabled=!FEATURES.has('reference_mastering')}
function renderNotes(){const root=document.getElementById('customNotes');root.innerHTML='';NOTES.forEach((n,i)=>{const l=document.createElement('label');const c=document.createElement('input');c.type='checkbox';c.style.width='auto';c.value=i;l.append(c,document.createTextNode(' '+n));root.appendChild(l)})}
async function loadProjects(){projects=await api('/projects');const s=document.getElementById('project');s.innerHTML='';for(const p of projects){const o=document.createElement('option');o.value=p.name;o.textContent=p.name;s.appendChild(o)}if(projects.length)await projectChanged()}
async function projectChanged(){await loadAssets();await loadOutputs()}
async function loadAssets(){selectedAsset=null;assetCache=[];const root=document.getElementById('assets');root.innerHTML='';const ref=document.getElementById('masterReference');ref.innerHTML='<option value="">None</option>';const album=document.getElementById('albumAssets');album.innerHTML='';if(!project())return;const items=await api('/projects/'+encodeURIComponent(project())+'/assets');assetCache=items.filter(x=>x.kind==='audio');for(const a of assetCache){const d=document.createElement('div');d.className='asset';d.textContent=a.name;d.onclick=()=>{document.querySelectorAll('#assets .asset').forEach(x=>x.classList.remove('selected'));d.classList.add('selected');selectedAsset=a;status('sourceStatus',{name:a.name,id:a.id,analysis:a.analysis})};root.appendChild(d);const o=document.createElement('option');o.value=a.id;o.textContent=a.name;ref.appendChild(o);const l=document.createElement('label');l.className='asset';const cb=document.createElement('input');cb.type='checkbox';cb.style.width='auto';cb.value=a.id;l.append(cb,document.createTextNode(' '+a.name));album.appendChild(l)}if(assetCache.length){selectedAsset=assetCache[0];root.firstChild?.classList.add('selected');status('sourceStatus',{name:selectedAsset.name,id:selectedAsset.id,analysis:selectedAsset.analysis})}}
async function loadCatalogs(){const inst=await api('/production/instrument-catalog');const root=document.getElementById('instrumentSwitches');root.innerHTML='';for(const [family,items] of Object.entries(inst.families)){for(const item of items){const d=document.createElement('label');d.className='switch'+(item.locked?' locked':'');const cb=document.createElement('input');cb.type='checkbox';cb.style.width='auto';cb.dataset.family=family;cb.dataset.type=item.id;cb.disabled=item.locked;d.append(cb,document.createTextNode(' '+item.label+(item.locked?' · Pro':'')));root.appendChild(d)}}const fx=await api('/production/fx-presets');const fs=document.getElementById('fxPreset');fs.innerHTML='';for(const p of fx.presets){const o=document.createElement('option');o.value=p.id;o.disabled=p.locked;o.textContent=p.category+' · '+p.name+(p.locked?' · locked':'');fs.appendChild(o)}const ms=await api('/production/mastering-presets');const m=document.getElementById('masterPreset'),am=document.getElementById('albumPreset');m.innerHTML='';am.innerHTML='';for(const p of ms.presets){const o=document.createElement('option');o.value=p.id;o.disabled=p.locked;o.textContent=p.id+(p.locked?' · locked':'');m.appendChild(o);if(!p.locked){const a=document.createElement('option');a.value=p.id;a.textContent=p.id;am.appendChild(a)}}if(FEATURES.has('plugin_rack')){try{const r=await api('/production/plugin-catalog');pluginCatalog=r.plugins||[];renderPluginCatalog()}catch(e){status('pluginStatus',e.message,false)}}gateUI()}
function switches(){return [...document.querySelectorAll('#instrumentSwitches input:checked')].map(x=>({family:x.dataset.family,type_id:x.dataset.type,enabled:true,prominence:.65,custom_direction:''}))}
async function detectSource(){try{const a=audio();status('buildStatus','Aura is analyzing the uploaded source...');const r=await api('/production/projects/'+encodeURIComponent(project())+'/detect-source/'+encodeURIComponent(a.id));document.getElementById('sourceRole').value=r.role;status('buildStatus',r)}catch(e){status('buildStatus',e.message,false)}}
async function waitJob(jobId){for(let i=0;i<1800;i++){const j=await api('/jobs/'+encodeURIComponent(jobId));status('buildStatus',{job_id:j.id,status:j.status,project:j.project_name,error:j.error||null,result:j.result||null},j.status!=='failed');if(j.status==='completed'){await loadOutputs();return j}if(j.status==='failed'||j.status==='cancelled')return j;await new Promise(r=>setTimeout(r,2000))}throw new Error('Render is still running; use the Studio Render Queue to continue watching it.')}
async function buildAround(){try{const a=audio();const body={asset_id:a.id,source_role:document.getElementById('sourceRole').value,genre:document.getElementById('genre').value,mood:document.getElementById('mood').value,instrument_switches:switches(),include_lead_vocal:document.getElementById('leadVocal').checked,include_backing_vocals:document.getElementById('backingVocal').checked,lyrics:document.getElementById('buildLyrics').value,generate_lyrics_if_missing:true,extra_direction:document.getElementById('buildDirection').value,output_mode:document.getElementById('buildMode').value,automix_after_generation:document.getElementById('autoMixBuild').checked};status('buildStatus','Submitting '+body.output_mode+' to Aura production queue...');const job=await api('/production/projects/'+encodeURIComponent(project())+'/build-around',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});status('buildStatus','Queued '+job.id+' · '+job.status);waitJob(job.id).catch(e=>status('buildStatus',e.message,false))}catch(e){status('buildStatus',e.message,false)}}
async function applyFx(){try{const a=audio();const r=await api('/production/projects/'+encodeURIComponent(project())+'/fx',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({asset_id:a.id,preset_id:document.getElementById('fxPreset').value})});status('fxStatus',r);await loadOutputs()}catch(e){status('fxStatus',e.message,false)}}
async function designFx(){try{const a=audio();const body={asset_id:a.id,description:document.getElementById('fxDescription').value,category:document.getElementById('fxCategory').value,max_effects:8};status('aiFxStatus','Aura is designing the chain...');const r=await api('/production/projects/'+encodeURIComponent(project())+'/fx-design-render',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});status('aiFxStatus',r);await loadOutputs()}catch(e){status('aiFxStatus',e.message,false)}}
async function autoKey(){try{const a=audio();const r=await api('/production/projects/'+encodeURIComponent(project())+'/autokey/'+encodeURIComponent(a.id));document.getElementById('tuneKey').value=r.key;document.getElementById('tuneScale').value=r.scale;status('tuneStatus',r)}catch(e){status('tuneStatus',e.message,false)}}
function customPcs(){return [...document.querySelectorAll('#customNotes input:checked')].map(x=>Number(x.value))}
async function tune(){try{const a=audio();const settings={mode:document.getElementById('tuneMode').value,key:document.getElementById('tuneKey').value||null,scale:document.getElementById('tuneScale').value,strength:Number(document.getElementById('tuneStrength').value),retune_speed_ms:Number(document.getElementById('retuneMs').value),humanize:Number(document.getElementById('humanize').value),formant_preserve:true,min_note_ms:Number(document.getElementById('minNoteMs').value),custom_pitch_classes:customPcs()};const r=await api('/production/projects/'+encodeURIComponent(project())+'/autotune',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({asset_id:a.id,settings})});status('tuneStatus',r);await loadOutputs()}catch(e){status('tuneStatus',e.message,false)}}
async function automix(){try{await api('/projects/'+encodeURIComponent(project())+'/session');const r=await api('/production/projects/'+encodeURIComponent(project())+'/automix',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({genre:document.getElementById('mixGenre').value,intensity:Number(document.getElementById('mixIntensity').value)})});status('mixStatus',r)}catch(e){status('mixStatus',e.message,false)}}
async function splitAudio(){try{const a=audio();status('splitStatus','Separating...');const r=await api('/production/projects/'+encodeURIComponent(project())+'/split',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({asset_id:a.id,mode:document.getElementById('splitMode').value})});status('splitStatus',r)}catch(e){status('splitStatus',e.message,false)}}
async function masterAudio(){try{const a=audio(),w=document.getElementById('masterWidth').value,l=document.getElementById('masterLufs').value;const body={asset_id:a.id,preset:document.getElementById('masterPreset').value,intensity:Number(document.getElementById('masterIntensity').value),low_db:Number(document.getElementById('masterLow').value),mid_db:Number(document.getElementById('masterMid').value),high_db:Number(document.getElementById('masterHigh').value),stereo_width:w?Number(w):null,target_lufs:l?Number(l):null,reference_asset_id:document.getElementById('masterReference').value||null};status('masterStatus','Mastering...');const r=await api('/production/projects/'+encodeURIComponent(project())+'/master',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});status('masterStatus',r);await loadOutputs()}catch(e){status('masterStatus',e.message,false)}}
async function albumMaster(){try{const ids=[...document.querySelectorAll('#albumAssets input:checked')].map(x=>x.value);if(ids.length<2)throw new Error('Select at least two audio assets');const body={asset_ids:ids,preset:document.getElementById('albumPreset').value,intensity:1};status('albumStatus','Mastering set...');const r=await api('/production/projects/'+encodeURIComponent(project())+'/album-master',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});status('albumStatus',r);await loadOutputs()}catch(e){status('albumStatus',e.message,false)}}
function renderPluginCatalog(){const s=document.getElementById('pluginSelect');s.innerHTML='';if(!pluginCatalog.length){const o=document.createElement('option');o.value='';o.textContent='No owner-approved plugins installed';s.appendChild(o);return}for(const p of pluginCatalog){const o=document.createElement('option');o.value=p.id;o.disabled=!p.installed;o.textContent=p.name+' · '+p.format+(p.installed?'':' · not installed');s.appendChild(o)}}
function addPlugin(){try{const id=document.getElementById('pluginSelect').value;if(!id)throw new Error('Choose an installed approved plugin');let params={};const raw=document.getElementById('pluginParams').value.trim();if(raw)params=JSON.parse(raw);pluginRack.push({plugin_id:id,enabled:true,parameters:params});renderRack()}catch(e){status('pluginStatus',e.message,false)}}
function renderRack(){const root=document.getElementById('rackList');root.innerHTML='';pluginRack.forEach((x,i)=>{const d=document.createElement('div');d.className='rackitem';d.textContent=(i+1)+'. '+x.plugin_id+' '+JSON.stringify(x.parameters);const b=document.createElement('button');b.textContent='Remove';b.onclick=()=>{pluginRack.splice(i,1);renderRack()};d.appendChild(document.createTextNode(' '));d.appendChild(b);root.appendChild(d)})}
async function renderPluginRack(){try{const a=audio();if(!pluginRack.length)throw new Error('Add at least one approved plugin');status('pluginStatus','Rendering trusted rack...');const r=await api('/production/projects/'+encodeURIComponent(project())+'/plugin-rack',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({asset_id:a.id,rack:{instances:pluginRack}})});status('pluginStatus',r);await loadOutputs()}catch(e){status('pluginStatus',e.message,false)}}
async function loadOutputs(){const side=document.getElementById('outputs'),main=document.getElementById('outputMain');side.innerHTML='';main.innerHTML='';if(!project())return;try{const rows=await api('/projects/'+encodeURIComponent(project())+'/outputs');if(!rows.length){side.innerHTML='<p class="muted tiny">No outputs yet.</p>';main.innerHTML='<p class="muted">No outputs yet.</p>';return}for(const r of rows){const s=document.createElement('div');s.className='output tiny';s.textContent=r.name;side.appendChild(s);const d=document.createElement('div');d.className='output';const h=document.createElement('b');h.textContent=r.name;d.appendChild(h);if(r.audio&&r.stream_url){const a=document.createElement('audio');a.controls=true;a.preload='none';a.src=r.stream_url;d.appendChild(a)}if(r.download_url){const link=document.createElement('a');link.className='btn';link.href=r.download_url;link.textContent='Download';d.appendChild(document.createElement('br'));d.appendChild(link)}else{const m=document.createElement('span');m.className='muted tiny';m.textContent=' Download locked by membership tier';d.appendChild(document.createElement('br'));d.appendChild(m)}main.appendChild(d)}}catch(e){main.innerHTML='<p class="err">'+e.message+'</p>'}}
renderNotes();gateUI();Promise.all([loadProjects(),loadCatalogs()]).catch(e=>status('sourceStatus',e.message,false));
</script></body></html>"""
    return HTMLResponse(
        page.replace("__PRODUCT__", escape(PRODUCT_FULL_NAME))
        .replace("__PLAN__", escape(plan.name))
        .replace("__NAME__", name)
        .replace("__FEATURES__", features)
    )
