from __future__ import annotations

from html import escape

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse, RedirectResponse

from .accounts import AccountStore
from .branding import PRODUCT_NAME
from .plans import UPLOAD_AUDIO, get_plan

router = APIRouter()
store = AccountStore()


@router.get('/recording-studio', response_class=HTMLResponse)
def recording_studio(request: Request):
    user = store.resolve_session(request.cookies.get('lss_session'))
    if not user:
        return RedirectResponse('/signin', status_code=303)
    if user.get('status') != 'active':
        return RedirectResponse('/dashboard', status_code=303)
    plan = get_plan(user.get('plan_id') or 'free')
    allowed = plan.has(UPLOAD_AUDIO)
    locked = '' if allowed else "<div class='alert'>Direct recording and uploads unlock on Base.</div>"
    page = f"""<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>
<title>Recording Studio — {escape(PRODUCT_NAME)}</title><style>
*{{box-sizing:border-box}}body{{margin:0;font-family:Inter,system-ui,sans-serif;color:#fff}}.wrap{{max-width:1250px;margin:auto;padding:20px}}.top{{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}}.brand{{font-size:1.1rem;font-weight:950}}a{{color:inherit;text-decoration:none}}.btn,button{{border:1px solid #523263;background:#21102c;color:#fff;padding:10px 13px;border-radius:10px;font-weight:850;cursor:pointer}}.primary{{background:linear-gradient(135deg,#ffe7a6,#e8ba59,#b67a23);color:#160b18}}.danger{{background:#641f34!important}}.layout{{display:grid;grid-template-columns:330px 1fr;gap:16px;margin-top:18px}}.panel{{background:#140b1b;border:1px solid #523263;border-radius:18px;padding:17px}}.field{{margin:12px 0}}label{{display:block;font-size:.86rem;font-weight:850;margin-bottom:6px}}select,input,textarea{{width:100%;background:#09050d;color:#fff;border:1px solid #523263;border-radius:10px;padding:11px}}textarea{{min-height:75px}}.row{{display:flex;gap:8px;flex-wrap:wrap;align-items:center}}.row>*{{flex:1}}.row button{{flex:0 0 auto}}.meter{{height:15px;background:#24142c;border-radius:999px;overflow:hidden;margin:11px 0}}.meter i{{display:block;height:100%;width:0%;background:linear-gradient(90deg,#6f2aa8,#d12a9f,#e7b953);transition:width .06s linear}}.timer{{font-size:3rem;font-weight:950;text-align:center;margin:22px 0;color:#ffe29a}}.count{{font-size:5rem;font-weight:950;text-align:center;min-height:95px;color:#e7b953;text-shadow:0 0 28px #d12a9f88}}.status,.alert{{white-space:pre-wrap;background:#09060d;border:1px solid #523263;border-radius:11px;padding:12px;margin-top:12px}}audio{{width:100%;margin-top:12px}}.muted{{color:#cdbfd4}}.rec{{display:inline-block;width:12px;height:12px;background:#e12c42;border-radius:50%;margin-right:6px;box-shadow:0 0 14px #e12c42}}@media(max-width:850px){{.layout{{grid-template-columns:1fr}}}}
</style></head><body><div class='wrap'><div class='top'><a class='brand' href='/studio'>{escape(PRODUCT_NAME)}<small style='display:block;color:#e7b953'>ESP RECORDING STUDIO</small></a><div><span>{escape(plan.name)}</span> <a class='btn' href='/production-suite'>Production Suite</a> <a class='btn' href='/studio'>Studio</a></div></div>
<div class='layout'><aside class='panel'><h2>Recording setup</h2><p class='muted'>Capture dry first. Aura Tune, FX, harmonies and Build Around stay reversible afterward. Use headphones when the metronome is active.</p>{locked}<div class='field'><label>Project</label><select id='project'></select></div><div class='field'><label>Input</label><select id='device'></select></div><div class='field'><label>Recording role</label><select id='role'><option value='vocals'>Lead vocal</option><option value='backing_vocals'>Backing vocal</option><option value='guitar'>Guitar</option><option value='bass'>Bass</option><option value='drums'>Drums / percussion</option><option value='piano'>Piano</option><option value='keyboard'>Keyboard</option><option value='synth'>Synth</option><option value='strings'>Strings</option><option value='brass'>Brass</option><option value='woodwinds'>Woodwinds</option><option value='percussion'>Percussion</option><option value='other'>Other</option></select></div><div class='field'><label>Take name</label><input id='title' value='Studio Take'></div><div class='row'><div class='field'><label>BPM</label><input id='bpm' type='number' min='40' max='240' value='120'></div><div class='field'><label>Count-in beats</label><select id='countBeats'><option>0</option><option>2</option><option selected>4</option><option>8</option></select></div></div><label><input id='metronome' type='checkbox' style='width:auto' checked> Continue metronome while recording</label><div class='field'><label>Notes</label><textarea id='notes' placeholder='Verse take, acoustic guitar idea, lead vocal...'></textarea></div></aside><main class='panel'><h2>Capture</h2><div id='count' class='count'></div><div id='timer' class='timer'>00:00.0</div><div class='meter'><i id='level'></i></div><div class='row'><button id='prepare' onclick='prepare()' {'disabled' if not allowed else ''}>Enable Microphone</button><button id='start' class='primary' onclick='startRecording()' disabled>● Record</button><button id='stop' class='danger' onclick='stopRecording()' disabled>■ Stop</button></div><p id='state' class='muted'>Microphone is not enabled.</p><audio id='preview' controls></audio><div class='row' style='margin-top:12px'><button id='save' class='primary' onclick='saveRecording()' disabled>Save 48 kHz WAV to Project</button><button id='discard' onclick='discard()' disabled>Discard Take</button></div><div id='status' class='status'>Saved recordings become private project assets ready for Build Around, Aura Tune, FX and mastering.</div></main></div></div>
<script>
const ALLOWED={str(allowed).lower()};let stream=null,recorder=null,chunks=[],blob=null,audioCtx=null,analyser=null,sourceNode=null,meterRAF=null,metroTimer=null,recordStart=0,timerHandle=null;
async function api(url,options={{}}){{const r=await fetch(url,{{credentials:'same-origin',...options}});let b;try{{b=await r.json()}}catch{{b=await r.text()}}if(!r.ok)throw new Error(typeof b==='string'?b:(b.detail||JSON.stringify(b)));return b}}
function status(v,ok=true){{const e=document.getElementById('status');e.textContent=typeof v==='string'?v:JSON.stringify(v,null,2);e.style.color=ok?'#86e0a8':'#ff9aa9'}}
async function init(){{try{{const ps=await api('/projects');const s=document.getElementById('project');for(const p of ps){{const o=document.createElement('option');o.value=p.name;o.textContent=p.name;s.appendChild(o)}}if(!ps.length)status('Create a project before recording.',false)}}catch(e){{status(e.message,false)}}}}
function bestMime(){{for(const m of ['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/mp4','audio/webm'])if(window.MediaRecorder&&MediaRecorder.isTypeSupported(m))return m;return ''}}
async function prepare(){{if(!ALLOWED)return;try{{if(stream)stream.getTracks().forEach(t=>t.stop());const id=document.getElementById('device').value;stream=await navigator.mediaDevices.getUserMedia({{audio:{{deviceId:id?{{exact:id}}:undefined,echoCancellation:false,noiseSuppression:false,autoGainControl:false,channelCount:2}}}});await refreshDevices();audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();sourceNode=audioCtx.createMediaStreamSource(stream);analyser=audioCtx.createAnalyser();analyser.fftSize=512;sourceNode.connect(analyser);drawMeter();document.getElementById('start').disabled=false;document.getElementById('state').textContent='Microphone ready · dry capture';}}catch(e){{status('Microphone error: '+e.message,false)}}}}
async function refreshDevices(){{const devices=await navigator.mediaDevices.enumerateDevices();const sel=document.getElementById('device'),old=sel.value;sel.innerHTML='';for(const d of devices.filter(x=>x.kind==='audioinput')){{const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||'Audio input';sel.appendChild(o)}}if([...sel.options].some(o=>o.value===old))sel.value=old}}
function drawMeter(){{cancelAnimationFrame(meterRAF);const data=new Uint8Array(analyser.frequencyBinCount);function tick(){{if(!analyser)return;analyser.getByteTimeDomainData(data);let sum=0;for(const x of data){{const v=(x-128)/128;sum+=v*v}}const rms=Math.sqrt(sum/data.length);document.getElementById('level').style.width=Math.min(100,rms*320)+'%';meterRAF=requestAnimationFrame(tick)}}tick()}}
function clickBeat(accent=false){{if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=accent?1100:760;g.gain.setValueAtTime(.16,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.055);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.06)}}
async function countIn(){{const n=Number(document.getElementById('countBeats').value),bpm=Number(document.getElementById('bpm').value)||120,ms=60000/bpm;for(let i=0;i<n;i++){{document.getElementById('count').textContent=String(i+1);clickBeat(i===0);await new Promise(r=>setTimeout(r,ms))}}document.getElementById('count').textContent=''}}
function startMetronome(){{stopMetronome();if(!document.getElementById('metronome').checked)return;const bpm=Number(document.getElementById('bpm').value)||120,ms=60000/bpm;let beat=0;clickBeat(true);metroTimer=setInterval(()=>{{beat=(beat+1)%4;clickBeat(beat===0)}},ms)}}function stopMetronome(){{if(metroTimer)clearInterval(metroTimer);metroTimer=null}}
async function startRecording(){{if(!stream)return;document.getElementById('start').disabled=true;document.getElementById('prepare').disabled=true;await countIn();chunks=[];blob=null;const mime=bestMime();recorder=mime?new MediaRecorder(stream,{{mimeType:mime,audioBitsPerSecond:256000}}):new MediaRecorder(stream);recorder.ondataavailable=e=>{{if(e.data.size)chunks.push(e.data)}};recorder.onstop=()=>{{blob=new Blob(chunks,{{type:recorder.mimeType||'audio/webm'}});const url=URL.createObjectURL(blob);document.getElementById('preview').src=url;document.getElementById('save').disabled=false;document.getElementById('discard').disabled=false;document.getElementById('prepare').disabled=false;document.getElementById('state').textContent='Take captured · preview before saving';}};recorder.start(500);recordStart=performance.now();startMetronome();document.getElementById('stop').disabled=false;document.getElementById('state').innerHTML='<span class="rec"></span>Recording dry input';timerHandle=setInterval(updateTimer,50)}}
function updateTimer(){{const s=(performance.now()-recordStart)/1000,m=Math.floor(s/60),r=s-m*60;document.getElementById('timer').textContent=String(m).padStart(2,'0')+':'+r.toFixed(1).padStart(4,'0')}}
function stopRecording(){{if(recorder&&recorder.state!=='inactive')recorder.stop();stopMetronome();clearInterval(timerHandle);document.getElementById('stop').disabled=true;document.getElementById('start').disabled=false}}
function extForBlob(){{const t=(blob&&blob.type)||'';if(t.includes('ogg'))return '.ogg';if(t.includes('mp4'))return '.m4a';return '.webm'}}
async function saveRecording(){{if(!blob)return;const p=document.getElementById('project').value;if(!p)return status('Choose a project.',false);const form=new FormData();form.append('audio',blob,'capture'+extForBlob());form.append('role',document.getElementById('role').value);form.append('title',document.getElementById('title').value||'Studio Take');form.append('notes',document.getElementById('notes').value);form.append('rights_confirmation','I confirm this is my recording or I have permission to use it.');try{{document.getElementById('save').disabled=true;status('Converting to professional 48 kHz WAV and saving...');const r=await api('/projects/'+encodeURIComponent(p)+'/recordings',{{method:'POST',body:form}});status(r);document.getElementById('state').textContent='Saved · ready for production';}}catch(e){{document.getElementById('save').disabled=false;status(e.message,false)}}}}
function discard(){{blob=null;chunks=[];const a=document.getElementById('preview');if(a.src)URL.revokeObjectURL(a.src);a.removeAttribute('src');a.load();document.getElementById('save').disabled=true;document.getElementById('discard').disabled=true;document.getElementById('timer').textContent='00:00.0';document.getElementById('state').textContent='Take discarded · microphone remains ready'}}
window.addEventListener('beforeunload',()=>{{stopMetronome();if(stream)stream.getTracks().forEach(t=>t.stop())}});init();
</script></body></html>"""
    return HTMLResponse(page)
