from __future__ import annotations

import json
import os
import shlex
import shutil
import subprocess
import time
from pathlib import Path

import requests
from gradio_client import Client, handle_file

from .models import ArrangementPlan, ProjectManifest, RenderResult
from .project import ProjectWorkspace


AUDIO_EXTS = {".mp3", ".wav", ".flac", ".ogg", ".m4a"}


def _first_audio(value) -> Path | None:
    values = value if isinstance(value, (list, tuple)) else [value]
    for item in values:
        candidates = []
        if isinstance(item, str):
            candidates.append(item)
        elif isinstance(item, dict):
            for key in ("path", "name", "url"):
                if item.get(key):
                    candidates.append(item[key])
        else:
            p = getattr(item, "path", None)
            if p:
                candidates.append(p)
        for candidate in candidates:
            try:
                p = Path(candidate)
                if p.exists() and p.is_file() and p.suffix.lower() in AUDIO_EXTS:
                    return p
            except Exception:
                pass
    return None


class BaseRenderer:
    name = "base"

    def available(self) -> bool:
        return True

    def render(self, workspace: ProjectWorkspace, manifest: ProjectManifest, plan: ArrangementPlan) -> RenderResult:
        raise NotImplementedError


class DeapiRenderer(BaseRenderer):
    name = "deapi"

    def available(self) -> bool:
        return bool(os.getenv("DEAPI_API_KEY"))

    def render(self, workspace, manifest, plan):
        api_key = os.environ["DEAPI_API_KEY"]
        base = os.getenv("DEAPI_BASE_URL", "https://api.deapi.ai")
        headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
        duration = _target_duration(workspace, manifest, plan)
        payload = {
            "model": os.getenv("DEAPI_MUSIC_MODEL", "AceStep_1_5_XL_Turbo_INT8"),
            "caption": plan.render_prompt,
            "lyrics": "",
            "duration": min(duration, manifest.renderer.duration_limit_seconds),
            "bpm": round(plan.tempo_bpm),
            "key": plan.key,
            "time_signature": plan.meter,
            "format": "wav",
        }
        r = requests.post(f"{base}/api/v2/audio/music", headers=headers, json=payload, timeout=60)
        r.raise_for_status()
        job = r.json()
        request_id = job.get("request_id") or job.get("id")
        if not request_id:
            raise RuntimeError(f"deAPI returned no request id: {job}")
        deadline = time.time() + int(os.getenv("DEAPI_TIMEOUT_SECONDS", "1800"))
        while time.time() < deadline:
            s = requests.get(f"{base}/api/v2/jobs/{request_id}", headers=headers, timeout=60)
            s.raise_for_status()
            data = s.json()
            state = str(data.get("status", "")).lower()
            if state in {"done", "completed", "success", "succeeded"}:
                url = data.get("result_url") or data.get("url") or data.get("output_url")
                if not url:
                    raise RuntimeError(f"deAPI completed without an audio URL: {data}")
                out = workspace.work_dir / "neural_master_deapi.wav"
                with requests.get(url, stream=True, timeout=180) as audio:
                    audio.raise_for_status()
                    with out.open("wb") as f:
                        for chunk in audio.iter_content(1024 * 1024):
                            f.write(chunk)
                return RenderResult(renderer=self.name, audio_path=out, metadata=data)
            if state in {"failed", "error", "cancelled"}:
                raise RuntimeError(f"deAPI generation failed: {data}")
            time.sleep(8)
        raise TimeoutError("deAPI generation timed out")


class AceStepSpaceRenderer(BaseRenderer):
    name = "acestep_space"

    def available(self) -> bool:
        return True

    def render(self, workspace, manifest, plan):
        source = workspace.resolve_asset(manifest.reference_audio)
        if manifest.mode in {"cover", "remix", "backing_track"} and (not source or not source.exists()):
            # A score guide generated by Aura can also be used as the cover source.
            candidate = workspace.work_dir / "score_guide.wav"
            if candidate.exists():
                source = candidate

        hosts = [x.strip() for x in os.getenv(
            "AURA_ACESTEP_SPACES",
            "critesjosh/ace-step-music-studio,ACE-Step/Ace-Step-v1.5",
        ).split(",") if x.strip()]
        errors = []
        for cycle in range(manifest.renderer.max_attempts_per_host):
            for host in hosts:
                try:
                    result = self._render_host(host, source, manifest, plan)
                    src = _first_audio(result)
                    if not src:
                        raise RuntimeError("Space returned no downloadable local audio")
                    dst = workspace.work_dir / f"neural_master_{host.replace('/', '_')}{src.suffix}"
                    shutil.copy2(src, dst)
                    return RenderResult(renderer=f"{self.name}:{host}", audio_path=dst, metadata={"host": host})
                except Exception as exc:
                    errors.append(f"{host}: {type(exc).__name__}: {exc}")
                    workspace.log(errors[-1], "renderer.log")
            if cycle + 1 < manifest.renderer.max_attempts_per_host:
                time.sleep(manifest.renderer.retry_seconds)
        raise RuntimeError("All ACE-Step Spaces failed: " + " | ".join(errors[-8:]))

    def _render_host(self, host: str, source: Path | None, manifest: ProjectManifest, plan: ArrangementPlan):
        duration = min(_target_duration(None, manifest, plan), manifest.renderer.duration_limit_seconds)
        mode = "cover" if source and source.exists() else "text2music"
        source_arg = handle_file(str(source)) if source and source.exists() else None
        args = [
            manifest.renderer.model, mode, plan.render_prompt, "en", plan.render_prompt, "[Instrumental]",
            round(plan.tempo_bpm), plan.key or "", plan.meter.split("/")[0], "en",
            8, 7.0, True, "-1", None, duration, 1,
            source_arg, "", 0.0, -1,
            "Fill the audio semantic mask based on the given conditions:",
            manifest.renderer.cover_strength, mode, False, 0.0, 1.0, 3.0, "ode", "", "wav",
            0.75, False, 2.0, 0, 0.9, plan.negative_prompt,
            True, True, False, False, True, False, False, 0.5, 8, "guitar", [], False,
        ]
        if len(args) != 49:
            raise AssertionError("ACE-Step generation schema changed")
        client = Client(host)
        return client.predict(*args, api_name="/generation_wrapper")


class LocalCommandRenderer(BaseRenderer):
    """Adapter for local ACE-Step Studio, The Muser, YuE or another GPU command.

    The command is configured with AURA_LOCAL_RENDER_CMD and receives environment variables
    AURA_PROJECT, AURA_PROMPT, AURA_NEGATIVE_PROMPT, AURA_BPM, AURA_KEY and AURA_OUTPUT.
    """

    name = "local_acestep"

    def available(self) -> bool:
        return bool(os.getenv("AURA_LOCAL_RENDER_CMD"))

    def render(self, workspace, manifest, plan):
        out = workspace.work_dir / "neural_master_local.wav"
        env = os.environ.copy()
        env.update({
            "AURA_PROJECT": str(workspace.root),
            "AURA_PROMPT": plan.render_prompt,
            "AURA_NEGATIVE_PROMPT": plan.negative_prompt,
            "AURA_BPM": str(plan.tempo_bpm),
            "AURA_KEY": plan.key or "",
            "AURA_OUTPUT": str(out),
        })
        cmd = shlex.split(os.environ["AURA_LOCAL_RENDER_CMD"])
        subprocess.run(cmd, cwd=workspace.root, env=env, check=True)
        if not out.exists():
            raise RuntimeError(f"Local renderer completed but did not create {out}")
        return RenderResult(renderer=self.name, audio_path=out)


def _target_duration(workspace: ProjectWorkspace | None, manifest: ProjectManifest, plan: ArrangementPlan) -> int:
    if manifest.total_measures and plan.tempo_bpm:
        beats_per_bar = int(manifest.meter.split("/")[0])
        return int(round(manifest.total_measures * beats_per_bar * 60.0 / plan.tempo_bpm))
    if workspace:
        reference = workspace.resolve_asset(manifest.reference_audio)
        if reference and reference.exists():
            try:
                import soundfile as sf
                info = sf.info(reference)
                return int(round(info.frames / info.samplerate))
            except Exception:
                pass
    return min(180, manifest.renderer.duration_limit_seconds)


def render_with_failover(workspace: ProjectWorkspace, manifest: ProjectManifest, plan: ArrangementPlan) -> RenderResult:
    renderers = {
        "deapi": DeapiRenderer(),
        "acestep_space": AceStepSpaceRenderer(),
        "local_acestep": LocalCommandRenderer(),
    }
    errors = []
    for name in manifest.renderer.preferred:
        renderer = renderers.get(name)
        if not renderer:
            errors.append(f"Unknown renderer: {name}")
            continue
        if not renderer.available():
            errors.append(f"Renderer unavailable: {name}")
            continue
        try:
            result = renderer.render(workspace, manifest, plan)
            workspace.log(f"Renderer success: {result.renderer}", "renderer.log")
            return result
        except Exception as exc:
            msg = f"Renderer failed {name}: {type(exc).__name__}: {exc}"
            errors.append(msg)
            workspace.log(msg, "renderer.log")
    raise RuntimeError("No renderer completed successfully. " + " | ".join(errors))
