from __future__ import annotations

from html import escape

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse

from .branding import PRODUCT_FULL_NAME, TAGLINE

router = APIRouter()


@router.get("/aura", response_class=HTMLResponse, include_in_schema=False)
@router.get("/rhiannon", response_class=HTMLResponse)
def rhiannon_control_room(request: Request):
    """Rhiannon speech control room with explicit browser degraded-mode fallbacks.

    `/aura` remains a compatibility URL only. Browser speech synthesis/recognition are
    accessibility/degraded fallbacks and are never represented as cloned-voice capability.
    """
    member = getattr(request.state, "member", None)
    name = escape(member.user.get("display_name") if member else "Member")
    plan = escape(member.plan.name if member else "Member")
    return HTMLResponse(f"""<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>
<title>Rhiannon Voice — {escape(PRODUCT_FULL_NAME)}</title><style>
:root{{--bg:#09060e;--panel:#18101f;--line:#422b51;--gold:#e9bd63;--muted:#cabfd2}}*{{box-sizing:border-box}}body{{margin:0;background:radial-gradient(circle at top,#301444,#09060e 55%);color:white;font-family:Inter,system-ui,sans-serif}}.wrap{{max-width:920px;margin:auto;padding:25px}}.card{{background:#160f1e;border:1px solid var(--line);border-radius:24px;padding:25px;margin:16px 0}}h1{{font-size:clamp(2.3rem,7vw,4.5rem);margin:.2em 0}}.gold{{color:var(--gold)}}.muted{{color:var(--muted)}}button,.btn,select,input{{font:inherit;border:1px solid var(--line);background:#251630;color:white;border-radius:12px;padding:12px 16px;font-weight:800}}button{{cursor:pointer}}.primary{{background:linear-gradient(135deg,#f0ce78,#bd8b32);color:#170e1d;border:0}}.recording{{background:#6d2035!important}}.orb{{width:180px;height:180px;border-radius:50%;margin:28px auto;background:radial-gradient(circle at 35% 30%,#f6d98d,#9a4fd2 45%,#261034 75%);box-shadow:0 0 80px #9b4bd466;display:grid;place-items:center;font-size:3rem}}.status{{white-space:pre-wrap;background:#0b0710;border:1px solid #31213c;border-radius:14px;padding:15px;min-height:100px}}.row{{display:flex;gap:10px;flex-wrap:wrap;align-items:center}}.row>*{{flex:1;min-width:150px}}audio{{width:100%;margin-top:14px}}.fallback{{border-color:#604276;background:#120d18}}label{{display:grid;gap:6px;font-size:.9rem;color:var(--muted)}}input[type=range]{{padding:8px}}
</style></head><body><div class='wrap'><div class='row'><div><div class='gold'><b>SHARED SKIES MEDIA · MUSIC STUDIO</b></div><div class='muted'>Rhiannon Voice · {plan}</div></div><a class='btn' href='/studio'>Back to Studio</a></div>
<div class='card' style='text-align:center'><h1>Talk to <span class='gold'>Rhiannon</span></h1><p class='muted'>Hello {name}. Speak naturally: “make the chorus bigger”, “split this track”, “clean the vocal”, “master this”, or describe the music you want to create.</p><div class='orb'>✦</div><div class='row'><select id='project'><option value=''>No project selected</option></select><button id='record' class='primary'>Start listening</button></div><p id='micState' class='muted'>Microphone idle.</p></div>
<div class='card fallback'><h3>Browser fallback · synthetic speech, not voice cloning</h3><p class='muted'>Used only when the configured Rhiannon speech/STT runtime is unavailable or when you choose a low-resource browser mode. Browser voice quality and privacy behaviour depend on the browser/device.</p><div class='row'><label>Browser voice<select id='browserVoice'><option value=''>System default</option></select></label><label>Language<select id='browserLanguage'><option value='en-GB'>English (UK)</option><option value='en-US'>English (US)</option><option value='es-ES'>Español</option></select></label><label>Rate<input id='browserRate' type='range' min='0.6' max='1.6' step='0.05' value='1'></label><label>Pitch<input id='browserPitch' type='range' min='0.5' max='1.5' step='0.05' value='1'></label></div><div class='row' style='margin-top:12px'><button id='browserListen'>Use browser speech recognition</button><button id='stopSpeech'>Stop speech</button></div><p id='fallbackState' class='muted'>Browser fallback idle.</p></div>
<div class='card'><h3>What Rhiannon heard</h3><div id='transcript' class='status'></div><h3>Rhiannon's plan</h3><div id='plan' class='status'></div><h3>Rhiannon says</h3><div id='reply' class='status'></div><audio id='voice' data-aura-speech-media='1' controls></audio></div><p class='muted'>{escape(TAGLINE)}</p></div>
<script>
let recorder=null, chunks=[], stream=null, browserRecognition=null, currentVoiceUrl=null;
const $=id=>document.getElementById(id);
function auraState(state,detail={{}}){{try{{window.AuraHost?.setState?.(state,{{source:'rhiannon_voice',...detail}})}}catch(e){{}}}}
function releaseVoiceUrl(){{if(currentVoiceUrl){{URL.revokeObjectURL(currentVoiceUrl);currentVoiceUrl=null}}}}
function bindVoiceState(){{const a=$('voice');a.addEventListener('playing',()=>auraState('speaking',{{phase:'configured_audio'}}));a.addEventListener('pause',()=>{{if(!a.ended)auraState('idle',{{phase:'configured_audio_paused'}})}});a.addEventListener('ended',()=>{{releaseVoiceUrl();auraState('idle',{{phase:'configured_audio_ended'}})}});a.addEventListener('error',()=>{{releaseVoiceUrl();auraState('warning',{{phase:'configured_audio_error'}})}})}}
async function loadProjects(){{try{{const r=await fetch('/projects',{{credentials:'same-origin'}});if(!r.ok)return;const items=await r.json();const s=$('project');for(const p of items){{const o=document.createElement('option');o.value=p.name;o.textContent=p.name;s.appendChild(o)}}}}catch(e){{}}}}
function loadBrowserVoices(){{if(!('speechSynthesis' in window))return;const voices=window.speechSynthesis.getVoices();const s=$('browserVoice');const selected=s.value;s.innerHTML='<option value="">System default</option>';voices.forEach((v,i)=>{{const o=document.createElement('option');o.value=String(i);o.textContent=`${{v.name}} · ${{v.lang}}`;s.appendChild(o)}});if(selected)s.value=selected}}
function browserSpeak(text,reason='Browser fallback selected.'){{if(!('speechSynthesis' in window)||!window.SpeechSynthesisUtterance){{$('fallbackState').textContent='Browser synthetic speech is unavailable on this device.';return false}}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const voices=window.speechSynthesis.getVoices();const idx=Number($('browserVoice').value);if(Number.isInteger(idx)&&voices[idx])u.voice=voices[idx];u.lang=$('browserLanguage').value||'en-GB';u.rate=Number($('browserRate').value)||1;u.pitch=Number($('browserPitch').value)||1;u.onstart=()=>{{auraState('speaking',{{phase:'browser_fallback'}});$('fallbackState').textContent=reason+' Speaking with browser synthetic voice — not a cloned voice.'}};u.onend=()=>{{auraState('idle',{{phase:'browser_fallback_ended'}});$('fallbackState').textContent='Browser fallback ready.'}};u.onerror=e=>{{auraState('warning',{{phase:'browser_fallback_error'}});$('fallbackState').textContent='Browser speech failed: '+(e.error||'unknown error')}};window.speechSynthesis.speak(u);return true}}
async function speak(text){{try{{auraState('thinking',{{phase:'speech_synthesis'}});const r=await fetch('/speech/synthesize',{{method:'POST',credentials:'same-origin',headers:{{'Content-Type':'application/json'}},body:JSON.stringify({{text}})}});if(!r.ok)throw new Error(`server speech unavailable (${{r.status}})`);const blob=await r.blob();releaseVoiceUrl();currentVoiceUrl=URL.createObjectURL(blob);const a=$('voice');a.src=currentVoiceUrl;await a.play().catch(()=>{{auraState('idle',{{phase:'configured_audio_autoplay_blocked'}})}});$('fallbackState').textContent='Configured Rhiannon speech runtime used.'}}catch(e){{auraState('idle',{{phase:'speech_synthesis_fallback'}});browserSpeak(text,'Configured Rhiannon speech runtime unavailable.')}}}}
function renderResult(data){{$('transcript').textContent=data.transcript||'';$('plan').textContent=JSON.stringify(data.plan,null,2);$('reply').textContent=data.spoken_text||'';$('micState').textContent='Ready.';if(data.spoken_text)speak(data.spoken_text);else auraState('idle',{{phase:'empty_reply'}})}}
async function sendText(text){{const p=$('project').value;$('micState').textContent='Rhiannon is processing browser-recognised text...';auraState('thinking',{{phase:'text_command'}});try{{const r=await fetch('/speech/text-command',{{method:'POST',credentials:'same-origin',headers:{{'Content-Type':'application/json'}},body:JSON.stringify({{text,project_name:p||null}})}});const data=await r.json();if(!r.ok)throw new Error(data.detail||JSON.stringify(data));renderResult(data)}}catch(e){{auraState('warning',{{phase:'text_command_error'}});$('micState').textContent='Rhiannon could not process browser-recognised text: '+e.message}}}}
async function send(blob){{const f=new FormData();f.append('audio',blob,'rhiannon-command.webm');const p=$('project').value;if(p)f.append('project_name',p);f.append('speak_reply','false');$('micState').textContent='Rhiannon is listening to what you said...';auraState('thinking',{{phase:'speech_command'}});try{{const r=await fetch('/speech/command',{{method:'POST',credentials:'same-origin',body:f}});const data=await r.json();if(!r.ok)throw new Error(data.detail||JSON.stringify(data));renderResult(data)}}catch(e){{auraState('warning',{{phase:'speech_command_error'}});$('micState').textContent='Configured speech recognition unavailable: '+e.message+' Use browser speech recognition fallback if supported.'}}}}
$('record').onclick=async()=>{{const b=$('record');if(recorder&&recorder.state==='recording'){{recorder.stop();b.textContent='Start listening';b.classList.remove('recording');$('micState').textContent='Processing...';auraState('thinking',{{phase:'capture_complete'}});return}}try{{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('MediaRecorder capture is not available');stream=await navigator.mediaDevices.getUserMedia({{audio:true}});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{{if(e.data.size)chunks.push(e.data)}};recorder.onstop=()=>{{stream.getTracks().forEach(t=>t.stop());send(new Blob(chunks,{{type:recorder.mimeType||'audio/webm'}}))}};recorder.start();b.textContent='Stop & send';b.classList.add('recording');$('micState').textContent='Listening...';auraState('listening',{{phase:'microphone_capture'}})}}catch(e){{auraState('warning',{{phase:'microphone_error'}});$('micState').textContent='Microphone capture unavailable: '+e.message+' Browser recognition fallback may still work.'}}}};
$('browserListen').onclick=()=>{{const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){{$('fallbackState').textContent='Browser speech recognition is unavailable on this device.';return}}if(browserRecognition){{try{{browserRecognition.abort()}}catch(e){{}}}}browserRecognition=new Recognition();browserRecognition.lang=$('browserLanguage').value||'en-GB';browserRecognition.continuous=false;browserRecognition.interimResults=false;browserRecognition.maxAlternatives=1;browserRecognition.onstart=()=>{{auraState('listening',{{phase:'browser_recognition'}});$('fallbackState').textContent='Browser speech recognition listening…'}};browserRecognition.onerror=e=>{{auraState('warning',{{phase:'browser_recognition_error'}});$('fallbackState').textContent='Browser speech recognition failed: '+(e.error||'unknown error')}};browserRecognition.onend=()=>{{if($('fallbackState').textContent.includes('listening')){{$('fallbackState').textContent='Browser fallback ready.';auraState('idle',{{phase:'browser_recognition_ended'}})}}}};browserRecognition.onresult=e=>{{const text=e.results?.[0]?.[0]?.transcript?.trim()||'';if(!text){{$('fallbackState').textContent='Browser recognition returned no speech.';auraState('idle',{{phase:'browser_recognition_empty'}});return}}$('fallbackState').textContent='Browser recognition captured text; sending through canonical Rhiannon command planning.';auraState('thinking',{{phase:'browser_recognition_result'}});sendText(text)}};browserRecognition.start()}};
$('stopSpeech').onclick=()=>{{if('speechSynthesis' in window)window.speechSynthesis.cancel();if(browserRecognition){{try{{browserRecognition.abort()}}catch(e){{}}}}const a=$('voice');a.pause();a.removeAttribute('src');releaseVoiceUrl();auraState('idle',{{phase:'speech_stopped'}});$('fallbackState').textContent='Speech stopped.'}};
if('speechSynthesis' in window){{loadBrowserVoices();window.speechSynthesis.onvoiceschanged=loadBrowserVoices}}
bindVoiceState();
loadProjects();
</script></body></html>""")
