from __future__ import annotations

import hashlib

from fastapi import APIRouter, HTTPException, Request

from .plans import VIDEO_SYNC
from .song_dna import SongDNAStore
from .video_music_sync import SyncMarker, _read as read_sync, _validate_markers, _write as write_sync
from .video_scene_render import _member_identity
from .video_scene_timeline import _project_dir
from .video_verified_captions import router as video_verified_captions_router

router = APIRouter(prefix="/creative", tags=["video-music-sync"])
router.include_router(video_verified_captions_router)

_GENERATED_SOURCE = "song-dna-verified-lyrics"
_ALLOWED_ALIGNMENT_STATES = {"verified", "forced_aligned"}


def _require_pro_video_sync(request: Request):
    _member_identity(request)
    member = getattr(request.state, "member", None)
    if member is None:
        raise HTTPException(401, "Membership context unavailable")
    if not member.plan.has(VIDEO_SYNC):
        raise HTTPException(403, "Video/music synchronization requires Pro")
    return member


def _marker_id(line_id: str) -> str:
    digest = hashlib.sha256(str(line_id).encode("utf-8")).hexdigest()[:24]
    return f"songdna.lyric.{digest}"


def _verified_lyric_markers(project_name: str) -> tuple[list[dict], dict]:
    project = _project_dir(project_name)
    try:
        dna = SongDNAStore(project).load()
    except FileNotFoundError as exc:
        raise HTTPException(404, "Song DNA not found for this project") from exc
    except Exception as exc:
        raise HTTPException(500, "Song DNA could not be read") from exc

    markers: list[dict] = []
    skipped_unverified = 0
    skipped_untimed = 0
    for line in sorted(dna.lyric_lines, key=lambda item: (int(item.order), str(item.id))):
        state = str(line.metadata.get("alignment_state") or "unaligned")
        if state not in _ALLOWED_ALIGNMENT_STATES:
            skipped_unverified += 1
            continue
        if line.start_seconds is None:
            skipped_untimed += 1
            continue
        text = str(line.text or "").strip()
        if not text:
            continue
        marker = SyncMarker(
            id=_marker_id(line.id),
            kind="lyric",
            time_seconds=float(line.start_seconds),
            end_seconds=float(line.end_seconds) if line.end_seconds is not None else None,
            text=text,
            source_element_id=_GENERATED_SOURCE,
        )
        markers.append(marker.model_dump(mode="json"))

    return markers, {
        "song_dna_version": int(dna.version),
        "eligible_alignment_states": sorted(_ALLOWED_ALIGNMENT_STATES),
        "skipped_unverified": skipped_unverified,
        "skipped_untimed": skipped_untimed,
    }


@router.post("/projects/{project_name}/video-music-sync/import-verified-lyrics")
def import_verified_lyrics(project_name: str, request: Request):
    """Import only verified/forced-aligned Song DNA lyric timings into the sync map.

    Estimated or unaligned timings are deliberately excluded so downstream scene planning cannot
    silently treat setup estimates as exact synchronization evidence. Re-import replaces only
    markers generated by this bridge; manual lyric/beat/onset/section markers remain untouched.
    """

    _require_pro_video_sync(request)
    generated, evidence = _verified_lyric_markers(project_name)
    if not generated:
        raise HTTPException(
            409,
            {
                "message": "No verified timed lyric lines are available to import",
                **evidence,
            },
        )

    current = read_sync(project_name)
    retained = [
        marker
        for marker in current["markers"]
        if not (
            marker.get("kind") == "lyric"
            and marker.get("source_element_id") == _GENERATED_SOURCE
        )
    ]
    combined = retained + generated
    _validate_markers(combined)
    combined.sort(key=lambda item: (float(item["time_seconds"]), str(item["id"])))
    saved = write_sync(project_name, {"markers": combined})

    return {
        "project_name": project_name,
        "imported_lyric_markers": len(generated),
        "replaced_generated_markers": len(current["markers"]) - len(retained),
        "preserved_existing_markers": len(retained),
        "marker_count": len(saved["markers"]),
        "alignment_evidence": evidence,
        "estimated_timings_imported": False,
        "raw_filesystem_paths_exposed": False,
        "frame_accurate_renderer_sync_guaranteed": False,
        "grants_esp_role_or_permission": False,
        "alters_billing_membership_or_creation_coins": False,
    }


__all__ = ["import_verified_lyrics", "router"]
