from __future__ import annotations

import json
from html import escape

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse, RedirectResponse

from .accounts import AccountStore
from .branding import PRODUCT_NAME
from .plans import (
    ADVANCED_IMAGE_GENERATION,
    ADVANCED_VIDEO_GENERATION,
    IMAGE_GENERATION,
    IMAGE_HIGH_QUALITY,
    IMAGE_PROVIDER_CONTROL,
    IMAGE_TRANSPARENT_BACKGROUND,
    VIDEO_EXTENDED_DURATION,
    VIDEO_GENERATION,
    VIDEO_HIGH_QUALITY,
    VIDEO_PROVIDER_CONTROL,
    VIDEO_TO_VIDEO,
    VISUAL_FX_STUDIO,
    get_plan,
)

router = APIRouter()
store = AccountStore()


@router.get("/visual-studio", response_class=HTMLResponse)
def visual_studio(request: Request):
    user = store.resolve_session(request.cookies.get("lss_session"))
    if not user:
        return RedirectResponse("/signin", status_code=303)
    if user.get("status") != "active":
        return RedirectResponse("/dashboard", status_code=303)
    plan = get_plan(user.get("plan_id") or "free")
    flags = {
        "image": plan.has(IMAGE_GENERATION),
        "video": plan.has(VIDEO_GENERATION),
        "fx": plan.has(VISUAL_FX_STUDIO),
        "advanced_image": plan.has(ADVANCED_IMAGE_GENERATION),
        "image_hq": plan.has(IMAGE_HIGH_QUALITY),
        "image_provider": plan.has(IMAGE_PROVIDER_CONTROL),
        "transparent": plan.has(IMAGE_TRANSPARENT_BACKGROUND),
        "advanced_video": plan.has(ADVANCED_VIDEO_GENERATION),
        "video_to_video": plan.has(VIDEO_TO_VIDEO),
        "video_long": plan.has(VIDEO_EXTENDED_DURATION),
        "video_hq": plan.has(VIDEO_HIGH_QUALITY),
        "video_provider": plan.has(VIDEO_PROVIDER_CONTROL),
    }
    page = r"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Visual Studio — __PRODUCT__</title><style>
:root{--bg:#09060e;--panel:#15101d;--line:#463351;--gold:#e8bd63;--muted:#c9bed1;--good:#7fe0a5;--bad:#ff95a8}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#311449,#09060e 42%);color:#fff;font-family:Inter,system-ui,sans-serif}a{color:inherit;text-decoration:none}button,input,textarea,select{font:inherit}.wrap{max-width:1500px;margin:auto;padding:18px}.top{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-bottom:16px}.brand b{display:block;color:var(--gold);font-size:.78rem;letter-spacing:.12em}.brand h1{margin:4px 0}.pill,.btn,button{border:1px solid var(--line);background:#24162d;color:#fff;border-radius:11px;padding:10px 13px;font-weight:850}.primary{background:linear-gradient(135deg,#f0d078,#bd8530);border:0;color:#180d1d}.tabs{display:flex;gap:8px;overflow:auto;margin-bottom:14px}.tabs button.active{color:#1b0e1f;background:var(--gold)}.view{display:none}.view.active{display:block}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.grid3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.panel,.card{background:#140d1b;border:1px solid var(--line);border-radius:18px;padding:17px}.field{margin:10px 0}.field label{display:block;font-weight:800;font-size:.85rem;margin-bottom:6px}input,textarea,select{width:100%;background:#09060e;color:#fff;border:1px solid var(--line);border-radius:10px;padding:11px}textarea{min-height:105px}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.row>*{flex:1}.row button,.row .btn{flex:0 0 auto}.muted{color:var(--muted)}.locked{opacity:.55}.status{white-space:pre-wrap;background:#08050c;border:1px solid #35263e;border-radius:12px;padding:12px;min-height:55px;margin-top:10px}.job{border-left:4px solid #73518a}.job.completed{border-color:var(--good)}.job.failed{border-color:var(--bad)}.job b{color:var(--gold)}.tag{display:inline-block;font-size:.72rem;padding:4px 7px;border:1px solid var(--line);border-radius:99px;margin:2px}.fxgrid{display:grid;grid-template-columns:330px 1fr;gap:12px}.timeline{min-height:360px;background:#0a0710;border:1px solid var(--line);border-radius:14px;padding:12px}.layer{padding:9px;border:1px solid #3c2a49;border-radius:9px;margin:6px 0;background:#1d1226}@media(max-width:850px){.grid,.grid3,.fxgrid{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><div class="top"><div class="brand"><b>ELEVATE SOULS PRODUCTIONS PRESENTS</b><h1>Visual Studio</h1><div class="muted">Images · Posters · Video · Pro Visual FX</div></div><div class="row"><span class="pill">__PLAN__</span><a class="btn" href="/studio">Music Studio</a><a class="btn" href="/production-suite">Production Suite</a><a class="btn" href="/dashboard">Account</a></div></div>
<div class="tabs"><button class="active" data-view="image">🖼 Image & Poster</button><button data-view="video">🎬 Video</button><button data-view="jobs">📦 Creations</button><button data-view="fx">✨ FX Studio · Pro</button></div>
<section id="view-image" class="view active"><div class="grid"><div class="panel"><h2>Generate image or poster</h2><p class="muted">Real AI generation. Poster artwork can move into the Pro layer compositor so text, logos and CTAs remain editable.</p><div id="imageLock" class="status"></div><div class="field"><label>Type</label><select id="imode"><option value="image">Image</option><option value="poster">Poster</option><option value="cover_art">Cover art</option><option value="social_graphic">Social graphic</option><option value="thumbnail">Thumbnail</option></select></div><div class="field"><label>Describe the visual</label><textarea id="iprompt" placeholder="Cinematic premium poster, dramatic stage lighting..."></textarea></div><div class="row"><div class="field"><label>Aspect ratio</label><select id="iratio"><option>1:1</option><option>4:5</option><option>9:16</option><option>16:9</option><option>3:2</option><option>2:3</option></select></div><div class="field"><label>Quality</label><select id="iquality"><option value="standard">Standard</option><option value="high">High · Pro</option><option value="professional">Professional · Pro</option></select></div></div><div class="field"><label>Title text</label><input id="ititle" placeholder="Optional poster title"></div><div id="imageAdvanced"><div class="field"><label>Subtitle · Pro</label><input id="isubtitle"></div><div class="field"><label>Call to action · Pro</label><input id="icta"></div><div class="field"><label>Brand direction · Pro</label><textarea id="ibrand" placeholder="Palette, typography direction, visual identity..."></textarea></div><div class="row"><div class="field"><label>Background</label><select id="ibg"><option value="opaque">Opaque</option><option value="auto">Auto</option><option value="transparent">Transparent · Pro</option></select></div><div class="field"><label>Engine</label><select id="iprovider"><option value="auto">Aura automatic</option><option value="openai">GPT Image 2 · Pro control</option><option value="local">Local renderer · Pro control</option></select></div></div></div><button id="imageGo" class="primary" onclick="generateImage()">Generate visual</button><div id="imageStatus" class="status"></div></div><div class="panel"><h2>Professional poster workflow</h2><div class="grid3"><div class="card"><b>1 · Generate</b><p class="muted">Create the art direction and background.</p></div><div class="card"><b>2 · Layer</b><p class="muted">Pro keeps titles, logos, CTAs, overlays and adjustments independently editable.</p></div><div class="card"><b>3 · Finish</b><p class="muted">Keyframe, mask, grade and export in the FX Studio.</p></div></div><div id="imageJobs"></div></div></div></section>
<section id="view-video" class="view"><div class="grid"><div class="panel"><h2>Generate video</h2><div id="videoLock" class="status"></div><div class="field"><label>Prompt</label><textarea id="vprompt" placeholder="Cinematic music video scene..."></textarea></div><div class="row"><div class="field"><label>Mode</label><select id="vmode"><option value="text_to_video">Text → video</option><option value="image_to_video">Image → video</option><option value="video_to_video">Video → video · Pro</option></select></div><div class="field"><label>Ratio</label><select id="vratio"><option>9:16</option><option>16:9</option><option>1:1</option></select></div></div><div class="row"><div class="field"><label>Seconds</label><input id="vduration" type="number" min="1" max="60" value="8"></div><div class="field"><label>Quality</label><select id="vquality"><option value="standard">Standard</option><option value="high">High · Pro</option><option value="professional">Professional · Pro</option></select></div></div><div class="field"><label>Reference URL / asset</label><input id="vref" placeholder="Required for image/video-to-video"></div><div id="videoAdvanced"><div class="field"><label>Negative prompt · Pro</label><textarea id="vnegative"></textarea></div><div class="field"><label>Engine · Pro control</label><select id="vprovider"><option value="auto">Aura automatic</option><option value="openai">OpenAI</option><option value="runway">Runway</option><option value="local">Local renderer</option></select></div></div><button id="videoGo" class="primary" onclick="generateVideo()">Generate video</button><div id="videoStatus" class="status"></div></div><div class="panel"><h2>Aura Video Director · Pro</h2><p class="muted">Shot-by-shot music-video planning, continuity, beat-aware transitions and advanced edit controls are reserved for Pro.</p><div class="card"><span class="tag">music video</span><span class="tag">lyric video</span><span class="tag">visualizer</span><span class="tag">cover animation</span><span class="tag">short-form</span><span class="tag">release video</span></div><div id="videoJobs"></div></div></div></section>
<section id="view-jobs" class="view"><div class="grid"><div class="panel"><div class="row"><h2>Image / poster creations</h2><button onclick="loadImageJobs()">Refresh</button></div><div id="allImageJobs"></div></div><div class="panel"><div class="row"><h2>Video creations</h2><button onclick="loadVideoJobs()">Refresh</button></div><div id="allVideoJobs"></div></div></div></section>
<section id="view-fx" class="view"><div class="panel"><h2>Visual FX Studio</h2><p class="muted">A non-destructive Pro workspace for layered image/video/text/audio composition, masks, blend modes, keyframes, effect stacks, color work and production export.</p><div id="fxLock" class="status"></div><div class="fxgrid"><aside><div class="field"><label>Project name</label><input id="fxname" value="Visual Project"></div><div class="row"><div class="field"><label>Width</label><input id="fxw" type="number" value="1080"></div><div class="field"><label>Height</label><input id="fxh" type="number" value="1920"></div></div><div class="row"><div class="field"><label>FPS</label><input id="fxfps" type="number" value="30"></div><div class="field"><label>Duration</label><input id="fxdur" type="number" value="15"></div></div><button id="fxCreate" class="primary" onclick="createFxProject()">Create FX project</button><div class="field"><label>Projects</label><select id="fxprojects" onchange="selectFxProject()"></select></div><hr style="border-color:#3d2b47"><div class="field"><label>Layer type</label><select id="fltype"><option>image</option><option>video</option><option>text</option><option>audio</option><option>shape</option><option>adjustment</option><option>effect</option></select></div><div class="field"><label>Layer name</label><input id="flname" value="Layer"></div><div class="field"><label>Source / URL</label><input id="flsource"></div><div class="field"><label>Text</label><input id="fltext"></div><div class="row"><div class="field"><label>Start</label><input id="flstart" type="number" value="0" step="0.1"></div><div class="field"><label>End</label><input id="flend" type="number" value="5" step="0.1"></div></div><div class="row"><div class="field"><label>Z layer</label><input id="flz" type="number" value="0"></div><div class="field"><label>Blend</label><select id="flblend"><option>normal</option><option>multiply</option><option>screen</option><option>overlay</option><option>soft_light</option><option>hard_light</option><option>add</option><option>difference</option></select></div></div><button onclick="addFxLayer()">Add layer</button></aside><main><div class="timeline"><h3 id="fxTitle">No FX project selected</h3><div id="fxLayers"></div></div><div class="row" style="margin-top:10px"><button onclick="renderFx('mp4')">Export MP4</button><button onclick="renderFx('png')">Export PNG</button></div><div id="fxStatus" class="status"></div></main></div></div></section>
</div><script>
const FLAGS=__FLAGS__;let fxProject=null;
function el(id){return document.getElementById(id)}function show(id,v,ok=true){const e=el(id);e.textContent=typeof v==='string'?v:JSON.stringify(v,null,2);e.style.color=ok?'#8ee7ad':'#ff9aae'}async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options});let b;try{b=await r.json()}catch{b=await r.text()}if(!r.ok)throw new Error(typeof b==='string'?b:(b.detail||JSON.stringify(b)));return b}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');el('view-'+b.dataset.view).classList.add('active');if(b.dataset.view==='jobs'){loadImageJobs();loadVideoJobs()}if(b.dataset.view==='fx')loadFxProjects()});
function locks(){if(!FLAGS.image){el('imageLock').textContent='Image & Poster generation unlocks on Base ($4.99/month).';el('imageGo').disabled=true}else el('imageLock').textContent='Image & Poster generation active.';if(!FLAGS.video){el('videoLock').textContent='Video generation unlocks on Base ($4.99/month).';el('videoGo').disabled=true}else el('videoLock').textContent='Video generation active.';if(!FLAGS.fx){el('fxLock').textContent='The layered Visual FX Studio is a Pro feature.';el('fxCreate').disabled=true}else el('fxLock').textContent='Pro Visual FX Studio active.';if(!FLAGS.advanced_image){['isubtitle','icta','ibrand'].forEach(x=>el(x).disabled=true)}if(!FLAGS.image_hq)el('iquality').querySelectorAll('option').forEach(o=>{if(o.value!=='standard')o.disabled=true});if(!FLAGS.image_provider)el('iprovider').querySelectorAll('option').forEach(o=>{if(o.value!=='auto')o.disabled=true});if(!FLAGS.transparent)el('ibg').querySelector('option[value=transparent]').disabled=true;if(!FLAGS.advanced_video)el('vnegative').disabled=true;if(!FLAGS.video_provider)el('vprovider').querySelectorAll('option').forEach(o=>{if(o.value!=='auto')o.disabled=true});if(!FLAGS.video_hq)el('vquality').querySelectorAll('option').forEach(o=>{if(o.value!=='standard')o.disabled=true});if(!FLAGS.video_to_video)el('vmode').querySelector('option[value=video_to_video]').disabled=true;if(!FLAGS.video_long)el('vduration').max=12}
async function generateImage(){try{show('imageStatus','Generating...');const p={prompt:el('iprompt').value,mode:el('imode').value,aspect_ratio:el('iratio').value,quality:el('iquality').value,provider:el('iprovider').value,background:el('ibg').value,title_text:el('ititle').value||null,subtitle_text:el('isubtitle').value||null,call_to_action:el('icta').value||null,brand_direction:el('ibrand').value||null};const r=await api('/api/image/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});show('imageStatus',r);loadImageJobs()}catch(e){show('imageStatus',e.message,false)}}
async function generateVideo(){try{show('videoStatus','Submitting real video generation...');const p={prompt:el('vprompt').value,mode:el('vmode').value,aspect_ratio:el('vratio').value,duration_seconds:Number(el('vduration').value),quality:el('vquality').value,provider:el('vprovider').value,reference_url:el('vref').value||null,negative_prompt:el('vnegative').value||null};const r=await api('/api/video/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});show('videoStatus',r);loadVideoJobs()}catch(e){show('videoStatus',e.message,false)}}
function jobHtml(j,type){const done=j.status==='completed';const dl=done?`<a class="btn" href="/api/${type}/jobs/${j.id}/download">Download</a>`:'';const refresh=type==='video'&&!done?`<button onclick="refreshVideo('${j.id}')">Refresh</button>`:'';return `<div class="card job ${j.status}"><b>${j.mode||type}</b><div class="muted">${j.status} · ${j.provider||''} ${j.model||''}</div><p>${(j.prompt||'').replace(/[<>]/g,'')}</p>${dl}${refresh}</div>`}
async function loadImageJobs(){if(!FLAGS.image)return;try{const r=await api('/api/image/jobs');const h=r.jobs.map(j=>jobHtml(j,'image')).join('')||'<p class="muted">No images yet.</p>';el('imageJobs').innerHTML=h;el('allImageJobs').innerHTML=h}catch(e){show('imageStatus',e.message,false)}}
async function loadVideoJobs(){if(!FLAGS.video)return;try{const r=await api('/api/video/jobs');const h=r.jobs.map(j=>jobHtml(j,'video')).join('')||'<p class="muted">No videos yet.</p>';el('videoJobs').innerHTML=h;el('allVideoJobs').innerHTML=h}catch(e){show('videoStatus',e.message,false)}}
async function refreshVideo(id){try{await api('/api/video/jobs/'+id+'/refresh',{method:'POST'});loadVideoJobs()}catch(e){show('videoStatus',e.message,false)}}
async function createFxProject(){if(!FLAGS.fx)return;try{const p={name:el('fxname').value,width:Number(el('fxw').value),height:Number(el('fxh').value),fps:Number(el('fxfps').value),duration_seconds:Number(el('fxdur').value)};fxProject=await api('/api/visual-fx/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});show('fxStatus',fxProject);await loadFxProjects();el('fxprojects').value=fxProject.id;drawFx()}catch(e){show('fxStatus',e.message,false)}}
async function loadFxProjects(){if(!FLAGS.fx)return;try{const r=await api('/api/visual-fx/projects');el('fxprojects').innerHTML=r.projects.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');if(r.projects.length&&!fxProject){el('fxprojects').value=r.projects[0].id;await selectFxProject()}}catch(e){show('fxStatus',e.message,false)}}
async function selectFxProject(){const id=el('fxprojects').value;if(!id)return;try{fxProject=await api('/api/visual-fx/projects/'+id);drawFx()}catch(e){show('fxStatus',e.message,false)}}
function drawFx(){if(!fxProject)return;el('fxTitle').textContent=fxProject.name+' · '+fxProject.width+'×'+fxProject.height+' · '+fxProject.fps+'fps';el('fxLayers').innerHTML=(fxProject.layers||[]).map(l=>`<div class="layer"><b>${l.z_index} · ${l.name}</b><div class="muted">${l.layer_type} · ${l.start_seconds}s–${l.end_seconds}s · ${l.blend_mode}</div></div>`).join('')||'<p class="muted">Add the first layer.</p>'}
async function addFxLayer(){if(!fxProject)return show('fxStatus','Create or select a project first.',false);try{const p={name:el('flname').value,layer_type:el('fltype').value,source:el('flsource').value||null,text:el('fltext').value||null,start_seconds:Number(el('flstart').value),end_seconds:Number(el('flend').value),z_index:Number(el('flz').value),blend_mode:el('flblend').value};fxProject=await api('/api/visual-fx/projects/'+fxProject.id+'/layers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});drawFx();show('fxStatus','Layer added.')}catch(e){show('fxStatus',e.message,false)}}
async function renderFx(kind){if(!fxProject)return;try{show('fxStatus','Rendering through configured production compositor...');const r=await api('/api/visual-fx/projects/'+fxProject.id+'/render',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({output_kind:kind})});show('fxStatus',r)}catch(e){show('fxStatus',e.message,false)}}
locks();loadImageJobs();loadVideoJobs();
</script></body></html>"""
    return HTMLResponse(
        page.replace("__PRODUCT__", escape(PRODUCT_NAME))
        .replace("__PLAN__", escape(plan.name))
        .replace("__FLAGS__", json.dumps(flags))
    )
